set define off

prompt AFMA 010 - Create CSIRO CAAB foundation tables

declare
  l_count number;

  procedure create_index_if_missing(
    p_index_name in varchar2,
    p_sql        in varchar2
  ) is
    l_index_count number;
  begin
    select count(*)
      into l_index_count
      from user_indexes
     where index_name = upper(p_index_name);

    if l_index_count = 0 then
      execute immediate p_sql;
    end if;
  end create_index_if_missing;
begin
  select count(*)
    into l_count
    from user_tables
   where table_name = 'CSIRO_CAAB_LOADS';

  if l_count = 0 then
    execute immediate q'[
      create table csiro_caab_loads (
        load_id             number generated by default on null as identity,
        source_name         varchar2(100 char) default 'CSIRO CAAB' not null,
        source_url          varchar2(1000 char),
        source_file_name    varchar2(512 char),
        source_file_sha256  varchar2(64 char),
        source_file_bytes   number,
        source_record_count number,
        loaded_record_count number,
        data_as_at_text     varchar2(100 char),
        downloaded_at       timestamp with local time zone,
        loaded_at           timestamp with local time zone default systimestamp not null,
        load_status         varchar2(30 char) default 'LOADED' not null,
        notes               clob,
        created_at          timestamp with local time zone default systimestamp not null,
        created_by          varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        updated_at          timestamp with local time zone default systimestamp not null,
        updated_by          varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint csiro_caab_loads_pk primary key (load_id),
        constraint csiro_caab_loads_ck_status check (load_status in ('LOADED','FAILED','SUPERSEDED','PARTIAL'))
      )
    ]';
  end if;

  select count(*)
    into l_count
    from user_tables
   where table_name = 'CSIRO_CAAB_CONFIG';

  if l_count = 0 then
    execute immediate q'[
      create table csiro_caab_config (
        config_key   varchar2(100 char) not null,
        config_value varchar2(4000 char),
        notes        varchar2(1000 char),
        created_at   timestamp with local time zone default systimestamp not null,
        created_by   varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        updated_at   timestamp with local time zone default systimestamp not null,
        updated_by   varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint csiro_caab_config_pk primary key (config_key)
      )
    ]';
  end if;

  select count(*)
    into l_count
    from user_tables
   where table_name = 'CSIRO_CAAB_TAXA';

  if l_count = 0 then
    execute immediate q'[
      create table csiro_caab_taxa (
        spcode                   varchar2(20 char) not null,
        scientific_name          varchar2(300 char),
        authority                varchar2(250 char),
        common_name              varchar2(200 char),
        family                   varchar2(250 char),
        family_sequence          number,
        assigned_family_code     varchar2(20 char),
        assigned_family_sequence number,
        recent_synonyms          clob,
        common_names_list        varchar2(500 char),
        kingdom                  varchar2(50 char),
        phylum                   varchar2(80 char),
        subphylum                varchar2(80 char),
        class_name               varchar2(80 char),
        subclass                 varchar2(80 char),
        order_name               varchar2(100 char),
        suborder                 varchar2(80 char),
        infraorder               varchar2(80 char),
        genus                    varchar2(120 char),
        species                  varchar2(120 char),
        sciname_informal         varchar2(300 char),
        subgenus                 varchar2(120 char),
        subspecies               varchar2(120 char),
        variety                  varchar2(120 char),
        date_last_modified       timestamp,
        undescribed_sp_flag      varchar2(1 char),
        habitat_code             varchar2(50 char),
        obis_classification_code varchar2(50 char),
        date_extracted           timestamp,
        list_status_code         varchar2(1 char),
        itis_identifier          varchar2(40 char),
        parent_id                varchar2(20 char),
        display_name             varchar2(250 char),
        taxon_rank               varchar2(50 char),
        non_current_flag         varchar2(1 char),
        superseded_by            varchar2(20 char),
        taxon_www_notes          clob,
        load_id                  number,
        source_file_name         varchar2(512 char),
        source_row_number        number,
        created_at               timestamp with local time zone default systimestamp not null,
        updated_at               timestamp with local time zone default systimestamp not null,
        constraint csiro_caab_taxa_pk primary key (spcode),
        constraint csiro_caab_taxa_fk_load foreign key (load_id)
          references csiro_caab_loads (load_id)
      )
    ]';
  end if;

  create_index_if_missing(
    'CSIRO_CAAB_TAXA_IX_NAME',
    'create index csiro_caab_taxa_ix_name on csiro_caab_taxa (lower(scientific_name), lower(common_name))'
  );

  create_index_if_missing(
    'CSIRO_CAAB_TAXA_IX_FAMILY',
    'create index csiro_caab_taxa_ix_family on csiro_caab_taxa (family, genus, species)'
  );

  create_index_if_missing(
    'CSIRO_CAAB_TAXA_IX_TAXONOMY',
    'create index csiro_caab_taxa_ix_taxonomy on csiro_caab_taxa (kingdom, phylum, class_name, order_name)'
  );

  create_index_if_missing(
    'CSIRO_CAAB_TAXA_IX_STATUS',
    'create index csiro_caab_taxa_ix_status on csiro_caab_taxa (list_status_code, non_current_flag, habitat_code)'
  );

  create_index_if_missing(
    'CSIRO_CAAB_TAXA_IX_PARENT',
    'create index csiro_caab_taxa_ix_parent on csiro_caab_taxa (parent_id, taxon_rank)'
  );
end;
/

create or replace trigger csiro_caab_loads_biu
  before insert or update on csiro_caab_loads
  for each row
begin
  if inserting then
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, coalesce(sys_context('APEX$SESSION','APP_USER'), user));
  end if;

  :new.updated_at := systimestamp;
  :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), user);
  :new.load_status := upper(:new.load_status);
end;
/

create or replace trigger csiro_caab_config_biu
  before insert or update on csiro_caab_config
  for each row
begin
  :new.config_key := upper(trim(:new.config_key));

  if inserting then
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, coalesce(sys_context('APEX$SESSION','APP_USER'), user));
  end if;

  :new.updated_at := systimestamp;
  :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), user);
end;
/

merge into csiro_caab_config target
using (
  select 'CAAB_DUMP_URL' as config_key,
         'https://www.cmar.csiro.au/data/caab/create_caab_extract.cfm' as config_value,
         'CSIRO CAAB dump endpoint discovered from the public CAAB page.' as notes
    from dual
  union all
  select 'AI_AGENT_STATIC_ID',
         'AFMA_CAAB_AGENT',
         'APEX AI Agent static id to use when the AFMA app agent is configured.'
    from dual
  union all
  select 'AI_CONFIG_STATIC_ID',
         'AFMA_CAAB_AGENT',
         'APEX 24.2 AI Config static id. Kept aligned with the future APEX AI Agent static id.'
    from dual
  union all
  select 'AI_AGENT_DISPLAY_NAME',
         'AFMA CAAB Agent',
         'Configured agent/display name. Uses the AI Hub agent naming convention with the Agent suffix.'
    from dual
  union all
  select 'AI_SERVICE_STATIC_ID',
         null,
         'Optional APEX Generative AI Service static id. Set this after AFMA workspace web credentials and service are created.'
    from dual
) source
on (target.config_key = source.config_key)
when not matched then
  insert (config_key, config_value, notes)
  values (source.config_key, source.config_value, source.notes);
/

create or replace view csiro_caab_taxa_active_v as
select *
  from csiro_caab_taxa
 where coalesce(non_current_flag, 'N') not in ('Y', 'T')
   and coalesce(list_status_code, 'A') = 'A';
/

create or replace view csiro_caab_taxa_summary_v as
select kingdom,
       phylum,
       class_name,
       taxon_rank,
       habitat_code,
       list_status_code,
       coalesce(non_current_flag, 'N') non_current_flag,
       count(*) taxon_count
  from csiro_caab_taxa
 group by kingdom,
          phylum,
          class_name,
          taxon_rank,
          habitat_code,
          list_status_code,
          coalesce(non_current_flag, 'N');
/

comment on table csiro_caab_loads is 'Load ledger for CSIRO Codes for Australian Aquatic Biota (CAAB) source extracts.';
/
comment on table csiro_caab_config is 'Configuration values for the AFMA CAAB demo, including source and optional APEX AI service ids.';
/
comment on table csiro_caab_taxa is 'Current CSIRO CAAB taxon records loaded for AFMA demo exploration.';
/
comment on column csiro_caab_taxa.spcode is 'CAAB SPCODE. Unique in the 2026-06-11 downloaded workbook.';
/
comment on column csiro_caab_taxa.class_name is 'Original CAAB spreadsheet column CLASS.';
/
comment on column csiro_caab_taxa.taxon_rank is 'Original CAAB spreadsheet column RANK.';
/
comment on column csiro_caab_taxa.taxon_www_notes is 'HTML-capable notes from the CAAB TAXON_WWW_NOTES column.';
/

prompt AFMA 010 complete
