set define off

prompt AFMA 025 - Create CSIRO fish common-name tables and seed data

create or replace function csiro_caab_normalize_name(
  p_value in varchar2
) return varchar2 deterministic is
  l_value varchar2(4000);
begin
  l_value := lower(trim(coalesce(p_value, '')));
  l_value := regexp_replace(l_value, '[^[:alnum:]]+', ' ');
  l_value := regexp_replace(trim(l_value), ' +', ' ');
  return nullif(l_value, '');
end csiro_caab_normalize_name;
/

declare
  l_count number;

  procedure create_index_if_missing(
    p_index_name in varchar2,
    p_sql        in varchar2
  ) is
    l_index_count number;
  begin
    select count(*)
      into l_index_count
      from user_indexes
     where index_name = upper(p_index_name);

    if l_index_count = 0 then
      execute immediate p_sql;
    end if;
  end create_index_if_missing;
begin
  select count(*)
    into l_count
    from user_tables
   where table_name = 'CSIRO_CAAB_FISHING_REGIONS';

  if l_count = 0 then
    execute immediate q'[
      create table csiro_caab_fishing_regions (
        region_code  varchar2(40 char) not null,
        region_name  varchar2(120 char) not null,
        jurisdiction varchar2(40 char) not null,
        region_group varchar2(80 char),
        notes        varchar2(1000 char),
        source_name  varchar2(200 char),
        source_url   varchar2(1000 char),
        created_at   timestamp with local time zone default systimestamp not null,
        created_by   varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        updated_at   timestamp with local time zone default systimestamp not null,
        updated_by   varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint csiro_caab_fishing_regions_pk primary key (region_code)
      )
    ]';
  end if;

  select count(*)
    into l_count
    from user_tables
   where table_name = 'CSIRO_CAAB_COMMON_NAMES';

  if l_count = 0 then
    execute immediate q'[
      create table csiro_caab_common_names (
        common_name_id        number generated by default on null as identity,
        spcode                varchar2(20 char) not null,
        common_name           varchar2(200 char) not null,
        normalized_common_name varchar2(200 char),
        name_kind             varchar2(30 char) not null,
        jurisdiction          varchar2(40 char),
        region_code           varchar2(40 char),
        locality              varchar2(200 char),
        first_observed_year   number(4),
        last_observed_year    number(4),
        season_start_month    number(2),
        season_end_month      number(2),
        source_name           varchar2(200 char),
        source_url            varchar2(1000 char),
        source_confidence     varchar2(30 char) default 'REFERENCE' not null,
        synthetic_flag        varchar2(1 char) default 'N' not null,
        seed_batch            varchar2(100 char),
        notes                 varchar2(1000 char),
        created_at            timestamp with local time zone default systimestamp not null,
        created_by            varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        updated_at            timestamp with local time zone default systimestamp not null,
        updated_by            varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint csiro_caab_common_names_pk primary key (common_name_id),
        constraint csiro_caab_common_names_fk_taxa foreign key (spcode)
          references csiro_caab_taxa (spcode),
        constraint csiro_caab_common_names_fk_region foreign key (region_code)
          references csiro_caab_fishing_regions (region_code),
        constraint csiro_caab_common_names_ck_kind check (
          name_kind in (
            'CSIRO_PRIMARY',
            'CSIRO_ALT',
            'STANDARD',
            'LOCAL_ALIAS',
            'MARKET_ALIAS',
            'LEGACY_ALIAS',
            'SYNTHETIC_DEMO'
          )
        ),
        constraint csiro_caab_common_names_ck_conf check (
          source_confidence in ('CSIRO', 'REFERENCE', 'SYNTHETIC', 'LEGACY', 'USER_REPORTED')
        ),
        constraint csiro_caab_common_names_ck_syn check (synthetic_flag in ('Y', 'N')),
        constraint csiro_caab_common_names_ck_months check (
          (season_start_month is null or season_start_month between 1 and 12)
          and (season_end_month is null or season_end_month between 1 and 12)
        )
      )
    ]';
  end if;

  create_index_if_missing(
    'CSIRO_CAAB_COMMON_NAMES_UK1',
    q'[create unique index csiro_caab_common_names_uk1
         on csiro_caab_common_names (
           spcode,
           normalized_common_name,
           name_kind,
           nvl(region_code, '~'),
           nvl(locality, '~'),
           nvl(first_observed_year, -1),
           nvl(last_observed_year, -1)
         )]'
  );

  create_index_if_missing(
    'CSIRO_CAAB_COMMON_NAMES_IX1',
    'create index csiro_caab_common_names_ix1 on csiro_caab_common_names (normalized_common_name, jurisdiction, region_code)'
  );

  create_index_if_missing(
    'CSIRO_CAAB_COMMON_NAMES_IX2',
    'create index csiro_caab_common_names_ix2 on csiro_caab_common_names (spcode, name_kind, source_confidence)'
  );
end;
/

create or replace trigger csiro_caab_regions_biu
  before insert or update on csiro_caab_fishing_regions
  for each row
begin
  :new.region_code := upper(trim(:new.region_code));
  :new.jurisdiction := upper(trim(:new.jurisdiction));

  if inserting then
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, coalesce(sys_context('APEX$SESSION','APP_USER'), user));
  end if;

  :new.updated_at := systimestamp;
  :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), user);
end;
/

create or replace trigger csiro_caab_common_names_biu
  before insert or update on csiro_caab_common_names
  for each row
begin
  :new.name_kind := upper(trim(:new.name_kind));
  :new.jurisdiction := upper(trim(:new.jurisdiction));
  :new.region_code := upper(trim(:new.region_code));
  :new.source_confidence := upper(trim(coalesce(:new.source_confidence, 'REFERENCE')));
  :new.synthetic_flag := upper(trim(coalesce(:new.synthetic_flag, 'N')));
  :new.normalized_common_name := csiro_caab_normalize_name(:new.common_name);

  if inserting then
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, coalesce(sys_context('APEX$SESSION','APP_USER'), user));
  end if;

  :new.updated_at := systimestamp;
  :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), user);
end;
/

merge into csiro_caab_fishing_regions target
using (
  select 'NATIONAL' region_code, 'Australia national seafood naming context' region_name, 'AU' jurisdiction, 'National' region_group,
         'National reference context for standard Australian fish names and stock reporting.' notes,
         'fish.gov.au and Australian Fish Names Database' source_name,
         'https://fish.gov.au/' source_url from dual
  union all select 'NSW_COAST', 'New South Wales coast', 'NSW', 'State coastal',
         'State coastal fisheries and stock-reporting context including NSW Ocean Trap and Line species.',
         'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales' from dual
  union all select 'QLD_GBR', 'Queensland east coast and reef line fisheries', 'QLD', 'State coastal',
         'Queensland commercial line fisheries context for reef fish, Spanish mackerel, redthroat emperor, tropical snappers, and coral trout.',
         'FRDC Fishfiles QLD Commercial Line Fisheries', 'https://www.fishfiles.com.au/fisheries-and-farms/qld-fisheries-and-farms/commercial-line-fisheries' from dual
  union all select 'QLD_GULF', 'Queensland Gulf of Carpentaria', 'QLD', 'Northern inshore',
         'Gulf and northern waters context for threadfins, barramundi, mackerel, and inshore finfish.',
         'FRDC Fishfiles QLD Commercial Line Fisheries', 'https://www.fishfiles.com.au/fisheries-and-farms/qld-fisheries-and-farms/commercial-line-fisheries' from dual
  union all select 'NT_TOP_END', 'Northern Territory Top End', 'NT', 'Northern inshore',
         'Top End barramundi fishery context including mud flats, river mouths, Barramundi, King Threadfin, Black Jewfish, and Blue Threadfin.',
         'FRDC Fishfiles NT Wild Barramundi Fishery', 'https://www.fishfiles.com.au/fisheries-and-farms/nt-fisheries-and-farms/wild-barramundi-fishery' from dual
  union all select 'SA_GULFS', 'South Australian gulfs and coastal waters', 'SA', 'Southern inshore',
         'South Australian Marine Scalefish context for King George Whiting, Snapper, Southern Garfish, and other coastal species.',
         'FRDC Fishfiles SA Marine Scale Fishery', 'https://www.fishfiles.com.au/fisheries-and-farms/sa-fisheries-and-farms/marine-scale-fishery' from dual
  union all select 'SA_GAB', 'South Australian Great Australian Bight and Eyre Peninsula', 'SA', 'Southern offshore',
         'South Australian west coast and Great Australian Bight context including Port Lincoln and tuna landing/holding activity.',
         'AFMA Southern Bluefin Tuna Fishery', 'https://www.afma.gov.au/fisheries/southern-bluefin-tuna-fishery' from dual
  union all select 'WA_KIMBERLEY', 'Western Australia Kimberley coast', 'WA', 'Northern inshore',
         'Northern Western Australia context for barramundi, threadfins, tropical snappers, and mackerels.',
         'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia' from dual
  union all select 'WA_PILBARA', 'Western Australia Pilbara coast', 'WA', 'Northern inshore',
         'Pilbara and north-west coastal context for mackerels, emperors, tropical snappers, and demersal line species.',
         'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia' from dual
  union all select 'WA_WEST_COAST', 'Western Australia West Coast Bioregion', 'WA', 'West coast demersal',
         'West Coast Demersal Scale Fish Resource context including West Australian Dhufish, Snapper, Redthroat Emperor, Hapuku, and Blue-eye Trevalla.',
         'FRDC Fishfiles WA West Coast Demersal Scale Fish Resource', 'https://www.fishfiles.com.au/fisheries-and-farms/wa-fisheries-and-farms/west-coast-demersal-scale-fish-resource' from dual
  union all select 'WA_SOUTH_COAST', 'Western Australia south coast', 'WA', 'Southern inshore',
         'South coast context for Western Australian Salmon, King George Whiting, herring, and southern coastal species.',
         'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia' from dual
  union all select 'VIC_BASS_STRAIT', 'Victoria and Bass Strait', 'VIC', 'Southern offshore',
         'Bass Strait and Victorian landing context for southern scalefish, shark, King George Whiting, flathead, and tuna.',
         'AFMA Southern and Eastern Scalefish and Shark Fishery', 'https://www.afma.gov.au/fisheries/southern-and-eastern-scalefish-and-shark-fishery' from dual
  union all select 'TAS_EAST_COAST', 'Tasmania east coast', 'TAS', 'Southern offshore',
         'Tasmanian east coast context for tuna, flathead, scalefish, and southern marine species.',
         'AFMA Southern and Eastern Scalefish and Shark Fishery', 'https://www.afma.gov.au/fisheries/southern-and-eastern-scalefish-and-shark-fishery' from dual
  union all select 'TAS_BASS_STRAIT', 'Tasmania and Bass Strait', 'TAS', 'Southern offshore',
         'Tasmania and Bass Strait context for southern scalefish, shark, Australian salmon, and flathead.',
         'AFMA Southern and Eastern Scalefish and Shark Fishery', 'https://www.afma.gov.au/fisheries/southern-and-eastern-scalefish-and-shark-fishery' from dual
  union all select 'COMMONWEALTH_ETBF', 'Eastern Tuna and Billfish Fishery', 'COMMONWEALTH', 'Commonwealth pelagic',
         'AFMA fishery from Cape York to the South Australia/Victoria border, with Cairns, Mooloolaba, Southport, Coffs Harbour, Ulladulla, and Bermagui landing context.',
         'AFMA Eastern Tuna and Billfish Fishery', 'https://www.afma.gov.au/fisheries/eastern-tuna-and-billfish-fishery' from dual
  union all select 'COMMONWEALTH_WTBF', 'Western Tuna and Billfish Fishery', 'COMMONWEALTH', 'Commonwealth pelagic',
         'AFMA fishery west from Cape York around Western Australia to the Victoria/South Australia border.',
         'AFMA Western Tuna and Billfish Fishery', 'https://www.afma.gov.au/fisheries/western-tuna-and-billfish-fishery' from dual
  union all select 'COMMONWEALTH_SBT', 'Southern Bluefin Tuna Fishery', 'COMMONWEALTH', 'Commonwealth pelagic',
         'AFMA fishery covering the sea area around Australia out to 200 nautical miles, with Port Lincoln, Ulladulla, and Bermagui landing context.',
         'AFMA Southern Bluefin Tuna Fishery', 'https://www.afma.gov.au/fisheries/southern-bluefin-tuna-fishery' from dual
  union all select 'COMMONWEALTH_SESSF', 'Southern and Eastern Scalefish and Shark Fishery', 'COMMONWEALTH', 'Commonwealth demersal',
         'AFMA multi-sector, multi-species fishery covering almost half of the Australian Fishing Zone from Fraser Island around Tasmania to Cape Leeuwin.',
         'AFMA Southern and Eastern Scalefish and Shark Fishery', 'https://www.afma.gov.au/fisheries/southern-and-eastern-scalefish-and-shark-fishery' from dual
) source
on (target.region_code = source.region_code)
when matched then
  update set region_name = source.region_name,
             jurisdiction = source.jurisdiction,
             region_group = source.region_group,
             notes = source.notes,
             source_name = source.source_name,
             source_url = source.source_url
when not matched then
  insert (region_code, region_name, jurisdiction, region_group, notes, source_name, source_url)
  values (source.region_code, source.region_name, source.jurisdiction, source.region_group, source.notes, source.source_name, source.source_url);
/

create or replace view csiro_caab_fish_taxa_v as
select t.*
  from csiro_caab_taxa t
 where t.phylum = 'Chordata'
   and t.class_name in (
         'Actinopterygii',
         'Elasmobranchii',
         'Holocephali',
         'Myxini',
         'Cephalaspidomorphi',
         'Sarcopterygii'
       );
/

create or replace view csiro_caab_common_name_search_v as
select cn.common_name_id,
       cn.spcode,
       cn.common_name,
       cn.normalized_common_name,
       cn.name_kind,
       cn.jurisdiction,
       cn.region_code,
       r.region_name,
       cn.locality,
       cn.first_observed_year,
       cn.last_observed_year,
       cn.season_start_month,
       cn.season_end_month,
       cn.source_name,
       cn.source_url,
       cn.source_confidence,
       cn.synthetic_flag,
       cn.notes,
       t.scientific_name,
       t.authority,
       t.family,
       t.class_name,
       t.order_name,
       t.taxon_rank,
       t.common_name caab_common_name
  from csiro_caab_common_names cn
  join csiro_caab_taxa t
    on t.spcode = cn.spcode
  left join csiro_caab_fishing_regions r
    on r.region_code = cn.region_code;
/

create or replace package csiro_caab_common_name_api as
  procedure rebuild_from_caab_data;
  procedure seed_curated_demo_names;
  procedure rebuild_all;
end csiro_caab_common_name_api;
/

create or replace package body csiro_caab_common_name_api as
  function current_year return number is
  begin
    return to_number(to_char(sysdate, 'YYYY'));
  end current_year;

  procedure upsert_curated(
    p_scientific_name      in varchar2,
    p_common_name          in varchar2,
    p_name_kind            in varchar2,
    p_region_code          in varchar2 default 'NATIONAL',
    p_jurisdiction         in varchar2 default null,
    p_locality             in varchar2 default null,
    p_first_observed_year  in number default 1990,
    p_last_observed_year   in number default null,
    p_season_start_month   in number default null,
    p_season_end_month     in number default null,
    p_source_name          in varchar2 default 'AFMA demo curated alias research',
    p_source_url           in varchar2 default null,
    p_source_confidence    in varchar2 default 'SYNTHETIC',
    p_synthetic_flag       in varchar2 default 'Y',
    p_notes                in varchar2 default null
  ) is
    l_spcode csiro_caab_taxa.spcode%type;
    l_region csiro_caab_fishing_regions%rowtype;
    l_jurisdiction varchar2(40);
    l_last_observed_year number(4);
  begin
    if p_scientific_name is null or p_common_name is null then
      return;
    end if;

    begin
      select spcode
        into l_spcode
        from (
          select spcode,
                 case
                   when coalesce(non_current_flag, 'N') in ('Y', 'T') then 1
                   else 0
                 end non_current_sort
            from csiro_caab_taxa
           where lower(scientific_name) = lower(p_scientific_name)
           order by non_current_sort, spcode
        )
       where rownum = 1;
    exception
      when no_data_found then
        return;
    end;

    begin
      select *
        into l_region
        from csiro_caab_fishing_regions
       where region_code = upper(p_region_code);

      l_jurisdiction := coalesce(upper(p_jurisdiction), l_region.jurisdiction);
    exception
      when no_data_found then
        l_jurisdiction := upper(p_jurisdiction);
    end;

    l_last_observed_year := coalesce(p_last_observed_year, current_year);

    merge into csiro_caab_common_names target
    using (
      select l_spcode spcode,
             trim(p_common_name) common_name,
             csiro_caab_normalize_name(p_common_name) normalized_common_name,
             upper(trim(p_name_kind)) name_kind,
             l_jurisdiction jurisdiction,
             upper(trim(p_region_code)) region_code,
             trim(p_locality) locality,
             p_first_observed_year first_observed_year,
             l_last_observed_year last_observed_year,
             p_season_start_month season_start_month,
             p_season_end_month season_end_month,
             p_source_name source_name,
             p_source_url source_url,
             upper(coalesce(p_source_confidence, 'SYNTHETIC')) source_confidence,
             upper(coalesce(p_synthetic_flag, 'Y')) synthetic_flag,
             'AFMA_CURATED_DEMO' seed_batch,
             p_notes notes
        from dual
    ) source
    on (
      target.spcode = source.spcode
      and target.normalized_common_name = source.normalized_common_name
      and target.name_kind = source.name_kind
      and nvl(target.region_code, '~') = nvl(source.region_code, '~')
      and nvl(target.locality, '~') = nvl(source.locality, '~')
      and nvl(target.first_observed_year, -1) = nvl(source.first_observed_year, -1)
      and nvl(target.last_observed_year, -1) = nvl(source.last_observed_year, -1)
    )
    when matched then
      update set common_name = source.common_name,
                 jurisdiction = source.jurisdiction,
                 season_start_month = source.season_start_month,
                 season_end_month = source.season_end_month,
                 source_name = source.source_name,
                 source_url = source.source_url,
                 source_confidence = source.source_confidence,
                 synthetic_flag = source.synthetic_flag,
                 seed_batch = source.seed_batch,
                 notes = source.notes
    when not matched then
      insert (
        spcode,
        common_name,
        normalized_common_name,
        name_kind,
        jurisdiction,
        region_code,
        locality,
        first_observed_year,
        last_observed_year,
        season_start_month,
        season_end_month,
        source_name,
        source_url,
        source_confidence,
        synthetic_flag,
        seed_batch,
        notes
      ) values (
        source.spcode,
        source.common_name,
        source.normalized_common_name,
        source.name_kind,
        source.jurisdiction,
        source.region_code,
        source.locality,
        source.first_observed_year,
        source.last_observed_year,
        source.season_start_month,
        source.season_end_month,
        source.source_name,
        source.source_url,
        source.source_confidence,
        source.synthetic_flag,
        source.seed_batch,
        source.notes
      );
  exception
    when no_data_found then
      null;
  end upsert_curated;

  procedure rebuild_from_caab_data is
  begin
    delete from csiro_caab_common_names
     where seed_batch in ('CAAB_CURRENT_PRIMARY', 'CAAB_CURRENT_ALT');

    insert into csiro_caab_common_names (
      spcode,
      common_name,
      normalized_common_name,
      name_kind,
      jurisdiction,
      region_code,
      source_name,
      source_url,
      source_confidence,
      synthetic_flag,
      seed_batch,
      notes
    )
    select t.spcode,
           trim(t.common_name),
           csiro_caab_normalize_name(t.common_name),
           'CSIRO_PRIMARY',
           'AU',
           'NATIONAL',
           'CSIRO CAAB workbook COMMON_NAME column',
           'https://www.cmar.csiro.au/data/caab/',
           'CSIRO',
           'N',
           'CAAB_CURRENT_PRIMARY',
           'Directly loaded from the CSIRO CAAB source extract.'
      from csiro_caab_fish_taxa_v t
     where t.common_name is not null
       and csiro_caab_normalize_name(t.common_name) is not null;

    insert into csiro_caab_common_names (
      spcode,
      common_name,
      normalized_common_name,
      name_kind,
      jurisdiction,
      region_code,
      source_name,
      source_url,
      source_confidence,
      synthetic_flag,
      seed_batch,
      notes
    )
    with lists as (
      select spcode,
             regexp_replace(common_names_list, '<[^>]*>', '|') cleaned_list
        from csiro_caab_fish_taxa_v
       where common_names_list is not null
    ),
    parts as (
      select spcode,
             regexp_replace(trim(regexp_substr(cleaned_list, '[^|,;/]+', 1, level)), ' +', ' ') common_name
        from lists
      connect by prior spcode = spcode
             and prior sys_guid() is not null
             and level <= regexp_count(cleaned_list, '[|,;/]') + 1
    ),
    raw_clean_parts as (
      select distinct spcode,
             common_name,
             csiro_caab_normalize_name(common_name) normalized_common_name
        from parts
       where common_name is not null
         and csiro_caab_normalize_name(common_name) is not null
         and length(common_name) <= 200
    ),
    clean_parts as (
      select spcode,
             min(common_name) keep (dense_rank first order by length(common_name), common_name) common_name,
             normalized_common_name
        from raw_clean_parts
       group by spcode,
                normalized_common_name
    )
    select p.spcode,
           p.common_name,
           p.normalized_common_name,
           'CSIRO_ALT',
           'AU',
           'NATIONAL',
           'CSIRO CAAB workbook COMMON_NAMES_LIST column',
           'https://www.cmar.csiro.au/data/caab/',
           'CSIRO',
           'N',
           'CAAB_CURRENT_ALT',
           'Alternative name parsed from CSIRO CAAB COMMON_NAMES_LIST. Source annotations in angle brackets were removed.'
      from clean_parts p
     where not exists (
             select 1
               from csiro_caab_common_names cn
              where cn.spcode = p.spcode
                and cn.normalized_common_name = p.normalized_common_name
           );
  end rebuild_from_caab_data;

  procedure seed_curated_demo_names is
    c_fish_gov constant varchar2(1000) := 'https://fish.gov.au/';
    c_nsw constant varchar2(1000) := 'https://www.fishfiles.com.au/fisheries-and-farms/nsw-fisheries-and-farms/ocean-trap-and-line-fishery';
    c_nt_barra constant varchar2(1000) := 'https://www.fishfiles.com.au/fisheries-and-farms/nt-fisheries-and-farms/wild-barramundi-fishery';
    c_sa_msf constant varchar2(1000) := 'https://www.fishfiles.com.au/fisheries-and-farms/sa-fisheries-and-farms/marine-scale-fishery';
    c_wa_dem constant varchar2(1000) := 'https://www.fishfiles.com.au/fisheries-and-farms/wa-fisheries-and-farms/west-coast-demersal-scale-fish-resource';
    c_qld_line constant varchar2(1000) := 'https://www.fishfiles.com.au/fisheries-and-farms/qld-fisheries-and-farms/commercial-line-fisheries';
    c_etbf constant varchar2(1000) := 'https://www.afma.gov.au/fisheries/eastern-tuna-and-billfish-fishery';
    c_wtbf constant varchar2(1000) := 'https://www.afma.gov.au/fisheries/western-tuna-and-billfish-fishery';
    c_sbt constant varchar2(1000) := 'https://www.afma.gov.au/fisheries/southern-bluefin-tuna-fishery';
    c_sessf constant varchar2(1000) := 'https://www.afma.gov.au/fisheries/southern-and-eastern-scalefish-and-shark-fishery';
  begin
    delete from csiro_caab_common_names
     where seed_batch = 'AFMA_CURATED_DEMO';

    upsert_curated('Lates calcarifer', 'barra', 'LOCAL_ALIAS', 'NT_TOP_END', null, 'Top End rivers and mud flats', 1980, null, 2, 9, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Demo-curated local alias based on widely recognised Australian barramundi usage and NT fishery context.');
    upsert_curated('Lates calcarifer', 'saltwater barra', 'LOCAL_ALIAS', 'QLD_GULF', null, 'Gulf of Carpentaria', 1990, null, 2, 9, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Demo-curated regional alias for northern saltwater barramundi discussions.');
    upsert_curated('Lates calcarifer', 'runoff barra', 'LOCAL_ALIAS', 'NT_TOP_END', null, 'Top End wet-season runoff', 2000, null, 2, 5, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Demo-curated seasonal recreational phrase; not an official market name.');
    upsert_curated('Lates calcarifer', 'wild barra', 'MARKET_ALIAS', 'NT_TOP_END', null, null, 2000, null, 2, 9, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Demo-curated market-style label distinguishing wild fishery context from farmed product.');

    upsert_curated('Polydactylus macrochir', 'king salmon', 'LOCAL_ALIAS', 'NT_TOP_END', null, 'Northern Territory barramundi fishery bycatch context', 1980, null, 2, 9, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Local alias often used in northern Australia for King Threadfin; demo-curated for regional search.');
    upsert_curated('Polydactylus macrochir', 'threadie', 'LOCAL_ALIAS', 'QLD_GULF', null, 'Gulf and northern estuaries', 1990, null, null, null, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Short fisher alias for threadfin species.');
    upsert_curated('Eleutheronema tetradactylum', 'blue salmon', 'LOCAL_ALIAS', 'NT_TOP_END', null, null, 1980, null, null, null, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Regional alias for Blue Threadfin in northern fishery conversations.');
    upsert_curated('Eleutheronema tetradactylum', 'blue threadie', 'LOCAL_ALIAS', 'QLD_GULF', null, null, 1990, null, null, null, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Demo-curated shorthand for Blue Threadfin.');
    upsert_curated('Protonibea diacanthus', 'black jew', 'LOCAL_ALIAS', 'NT_TOP_END', null, null, 1980, null, null, null, 'FRDC Fishfiles NT Wild Barramundi Fishery', c_nt_barra, 'SYNTHETIC', 'Y', 'Shortened local alias for Black Jewfish.');
    upsert_curated('Protonibea diacanthus', 'jewie', 'LOCAL_ALIAS', 'WA_KIMBERLEY', null, null, 1990, null, null, null, 'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia', 'SYNTHETIC', 'Y', 'Ambiguous local shorthand; region and species context are required.');

    upsert_curated('Argyrosomus japonicus', 'jewfish', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Estuaries and nearshore coast', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'REFERENCE', 'N', 'CAAB also lists jewfish as an alternative for Mulloway.');
    upsert_curated('Argyrosomus japonicus', 'jewie', 'LOCAL_ALIAS', 'NSW_COAST', null, null, 1990, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Short fisher alias for Mulloway; ambiguous without region/species context.');
    upsert_curated('Argyrosomus japonicus', 'mulla', 'LOCAL_ALIAS', 'NSW_COAST', null, null, 2000, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Demo-curated shorthand for Mulloway.');

    upsert_curated('Chrysophrys auratus', 'pink snapper', 'LOCAL_ALIAS', 'WA_WEST_COAST', null, 'West Coast Bioregion', 1980, null, null, null, 'FRDC Fishfiles WA West Coast Demersal Scale Fish Resource', c_wa_dem, 'SYNTHETIC', 'Y', 'Regional alias often used in WA context to distinguish snapper from tropical snappers.');
    upsert_curated('Chrysophrys auratus', 'reds', 'LOCAL_ALIAS', 'SA_GULFS', null, 'South Australian coastal waters', 1980, null, null, null, 'FRDC Fishfiles SA Marine Scale Fishery', c_sa_msf, 'SYNTHETIC', 'Y', 'Ambiguous fisher shorthand; used here with Snapper region context.');
    upsert_curated('Chrysophrys auratus', 'squire', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Juvenile or small snapper context', 1980, null, null, null, 'FRDC Fishfiles NSW Ocean Trap and Line Fishery', c_nsw, 'SYNTHETIC', 'Y', 'Demo-curated size-class alias for Snapper conversations.');
    upsert_curated('Chrysophrys auratus', 'knobby snapper', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Large snapper context', 1990, null, null, null, 'FRDC Fishfiles NSW Ocean Trap and Line Fishery', c_nsw, 'SYNTHETIC', 'Y', 'Demo-curated alias for larger Snapper commonly described by fishers.');

    upsert_curated('Seriola lalandi', 'kingie', 'LOCAL_ALIAS', 'NSW_COAST', null, 'NSW Ocean Trap and Line', 1980, null, null, null, 'FRDC Fishfiles NSW Ocean Trap and Line Fishery', c_nsw, 'SYNTHETIC', 'Y', 'Widely recognised fisher shorthand for Yellowtail Kingfish.');
    upsert_curated('Seriola lalandi', 'hoodlum king', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Large kingfish context', 1990, null, null, null, 'FRDC Fishfiles NSW Ocean Trap and Line Fishery', c_nsw, 'SYNTHETIC', 'Y', 'Demo-curated large-fish alias; not an official common name.');
    upsert_curated('Seriola lalandi', 'yellowtail', 'LOCAL_ALIAS', 'SA_GULFS', null, null, 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Ambiguous shorthand that requires species context.');

    upsert_curated('Thunnus maccoyii', 'SBT', 'LOCAL_ALIAS', 'COMMONWEALTH_SBT', null, 'Commonwealth quota and landing context', 1990, null, 12, 11, 'AFMA Southern Bluefin Tuna Fishery', c_sbt, 'REFERENCE', 'N', 'Industry abbreviation for Southern Bluefin Tuna used in fishery context.');
    upsert_curated('Thunnus maccoyii', 'bluefin', 'LOCAL_ALIAS', 'COMMONWEALTH_SBT', null, null, 1980, null, 12, 11, 'AFMA Southern Bluefin Tuna Fishery', c_sbt, 'SYNTHETIC', 'Y', 'Ambiguous shorthand; this row is scoped to Southern Bluefin Tuna.');
    upsert_curated('Thunnus maccoyii', 'barrel tuna', 'LOCAL_ALIAS', 'SA_GAB', null, 'Port Lincoln and Great Australian Bight context', 2000, null, null, null, 'AFMA Southern Bluefin Tuna Fishery', c_sbt, 'SYNTHETIC', 'Y', 'Demo-curated recreational descriptor for large Southern Bluefin Tuna.');
    upsert_curated('Thunnus maccoyii', 'Port Lincoln bluefin', 'MARKET_ALIAS', 'SA_GAB', null, 'Port Lincoln', 2000, null, 12, 11, 'AFMA Southern Bluefin Tuna Fishery', c_sbt, 'SYNTHETIC', 'Y', 'Demo-curated market/geographic label grounded in AFMA landing-port context.');

    upsert_curated('Scomberomorus commerson', 'spanish', 'LOCAL_ALIAS', 'QLD_GBR', null, 'Queensland offshore waters', 1980, null, null, null, 'FRDC Fishfiles QLD Commercial Line Fisheries', c_qld_line, 'SYNTHETIC', 'Y', 'Short fisher alias for Spanish Mackerel.');
    upsert_curated('Scomberomorus commerson', 'spanno', 'LOCAL_ALIAS', 'WA_PILBARA', null, 'North-west coast', 1990, null, null, null, 'FRDC Fishfiles QLD Commercial Line Fisheries', c_qld_line, 'SYNTHETIC', 'Y', 'Demo-curated shorthand for Spanish Mackerel.');
    upsert_curated('Scomberomorus commerson', 'narrow-barred mackerel', 'STANDARD', 'QLD_GBR', null, null, 1990, null, null, null, 'CSIRO CAAB COMMON_NAMES_LIST', 'https://www.cmar.csiro.au/data/caab/', 'CSIRO', 'N', 'CAAB alternative name for Spanish Mackerel.');
    upsert_curated('Scomberomorus queenslandicus', 'schoolie', 'LOCAL_ALIAS', 'QLD_GBR', null, null, 1990, null, null, null, 'fish.gov.au Queensland', 'https://fish.gov.au/jurisdiction/queensland', 'SYNTHETIC', 'Y', 'Fisher shorthand for School Mackerel.');
    upsert_curated('Scomberomorus semifasciatus', 'grey mack', 'LOCAL_ALIAS', 'QLD_GULF', null, null, 1990, null, null, null, 'fish.gov.au Queensland', 'https://fish.gov.au/jurisdiction/queensland', 'SYNTHETIC', 'Y', 'Fisher shorthand for Grey Mackerel.');

    upsert_curated('Pomatomus saltatrix', 'greenback', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Surf beach and estuary context', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Common fisher alias for larger Tailor.');
    upsert_curated('Pomatomus saltatrix', 'chopper tailor', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Small tailor context', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Demo-curated size-class alias for Tailor.');
    upsert_curated('Pomatomus saltatrix', 'bluefish', 'LEGACY_ALIAS', 'NATIONAL', 'AU', null, 1980, null, null, null, 'fish.gov.au', c_fish_gov, 'LEGACY', 'N', 'Global/legacy alias for the same species; not preferred for Australian demos without context.');

    upsert_curated('Arripis trutta', 'aussie salmon', 'LOCAL_ALIAS', 'NSW_COAST', null, null, 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Local shorthand for Eastern Australian Salmon.');
    upsert_curated('Arripis trutta', 'cocky salmon', 'LOCAL_ALIAS', 'TAS_BASS_STRAIT', null, null, 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Demo-curated older/local Australian salmon alias.');
    upsert_curated('Arripis truttaceus', 'WA salmon', 'LOCAL_ALIAS', 'WA_SOUTH_COAST', null, 'WA south coast', 1980, null, null, null, 'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia', 'REFERENCE', 'N', 'Region-scoped shorthand for Western Australian Salmon.');
    upsert_curated('Arripis truttaceus', 'salmon trout', 'LOCAL_ALIAS', 'WA_SOUTH_COAST', null, 'Juvenile or smaller fish context', 1980, null, null, null, 'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia', 'SYNTHETIC', 'Y', 'Demo-curated size-class alias for Western Australian Salmon.');

    upsert_curated('Sillaginodes punctatus', 'KGW', 'LOCAL_ALIAS', 'SA_GULFS', null, 'Gulf St Vincent and Spencer Gulf context', 1980, null, null, null, 'FRDC Fishfiles SA Marine Scale Fishery', c_sa_msf, 'SYNTHETIC', 'Y', 'Common abbreviation for King George Whiting.');
    upsert_curated('Sillaginodes punctatus', 'king george', 'LOCAL_ALIAS', 'SA_GULFS', null, null, 1980, null, null, null, 'FRDC Fishfiles SA Marine Scale Fishery', c_sa_msf, 'SYNTHETIC', 'Y', 'Short fisher/market alias for King George Whiting.');
    upsert_curated('Sillaginodes punctatus', 'spotted whiting', 'STANDARD', 'WA_SOUTH_COAST', null, null, 1980, null, null, null, 'FRDC Fishfiles SA Marine Scale Fishery', c_sa_msf, 'REFERENCE', 'N', 'Recognisable alternative name for King George Whiting.');
    upsert_curated('Sillago ciliata', 'sandies', 'LOCAL_ALIAS', 'NSW_COAST', null, null, 1990, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Fisher shorthand for Sand Whiting.');
    upsert_curated('Sillago ciliata', 'summer whiting', 'LOCAL_ALIAS', 'QLD_GBR', null, 'Queensland coast', 1980, null, null, null, 'fish.gov.au Queensland', 'https://fish.gov.au/jurisdiction/queensland', 'SYNTHETIC', 'Y', 'Queensland-style market/local alias for Sand Whiting.');

    upsert_curated('Platycephalus fuscus', 'flatty', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Estuary and inshore flathead context', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Common fisher shorthand for Dusky Flathead.');
    upsert_curated('Platycephalus fuscus', 'lizard', 'LOCAL_ALIAS', 'NSW_COAST', null, null, 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Fisher slang for flathead species, scoped here to Dusky Flathead.');
    upsert_curated('Platycephalus bassensis', 'sandy flathead', 'LOCAL_ALIAS', 'TAS_BASS_STRAIT', null, 'Bass Strait and Tasmania', 1980, null, null, null, 'AFMA Southern and Eastern Scalefish and Shark Fishery', c_sessf, 'SYNTHETIC', 'Y', 'Demo-curated shorthand for Southern Sand Flathead.');

    upsert_curated('Glaucosoma hebraicum', 'dhufish', 'LOCAL_ALIAS', 'WA_WEST_COAST', null, 'West Coast Bioregion', 1980, null, null, null, 'FRDC Fishfiles WA West Coast Demersal Scale Fish Resource', c_wa_dem, 'REFERENCE', 'N', 'Short local name for West Australian Dhufish.');
    upsert_curated('Glaucosoma hebraicum', 'dhuie', 'LOCAL_ALIAS', 'WA_WEST_COAST', null, 'West Coast Bioregion', 1990, null, null, null, 'FRDC Fishfiles WA West Coast Demersal Scale Fish Resource', c_wa_dem, 'SYNTHETIC', 'Y', 'WA fisher shorthand for West Australian Dhufish.');
    upsert_curated('Glaucosoma hebraicum', 'westralian jewfish', 'LEGACY_ALIAS', 'WA_WEST_COAST', null, 'West Coast Bioregion', 1980, null, null, null, 'CSIRO CAAB COMMON_NAMES_LIST', 'https://www.cmar.csiro.au/data/caab/', 'CSIRO', 'N', 'CAAB alternative/legacy name for West Australian Dhufish.');

    upsert_curated('Lutjanus sebae', 'red emp', 'LOCAL_ALIAS', 'WA_PILBARA', null, 'North-west demersal context', 1990, null, null, null, 'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia', 'SYNTHETIC', 'Y', 'Fisher shorthand for Red Emperor.');
    upsert_curated('Lutjanus sebae', 'reds', 'LOCAL_ALIAS', 'WA_PILBARA', null, null, 1980, null, null, null, 'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia', 'SYNTHETIC', 'Y', 'Ambiguous shorthand scoped here to Red Emperor in north-west context.');
    upsert_curated('Lutjanus malabaricus', 'large-mouth nannygai', 'STANDARD', 'QLD_GBR', null, null, 1980, null, null, null, 'fish.gov.au Queensland', 'https://fish.gov.au/jurisdiction/queensland', 'REFERENCE', 'N', 'Common market/fishery alias for Saddletail Snapper.');
    upsert_curated('Lutjanus erythropterus', 'small-mouth nannygai', 'STANDARD', 'QLD_GBR', null, null, 1980, null, null, null, 'fish.gov.au Queensland', 'https://fish.gov.au/jurisdiction/queensland', 'REFERENCE', 'N', 'Common market/fishery alias for Crimson Snapper.');
    upsert_curated('Pristipomoides multidens', 'goldband', 'LOCAL_ALIAS', 'WA_PILBARA', null, null, 1990, null, null, null, 'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia', 'SYNTHETIC', 'Y', 'Short fisher/market alias for Goldband Snapper.');
    upsert_curated('Lethrinus miniatus', 'red throat', 'LOCAL_ALIAS', 'QLD_GBR', null, 'Queensland line fishery context', 1990, null, null, null, 'FRDC Fishfiles QLD Commercial Line Fisheries', c_qld_line, 'SYNTHETIC', 'Y', 'Short fisher alias for Redthroat Emperor.');
    upsert_curated('Lethrinus nebulosus', 'spango', 'LOCAL_ALIAS', 'WA_PILBARA', null, null, 1990, null, null, null, 'fish.gov.au Western Australia', 'https://fish.gov.au/jurisdiction/western-australia', 'SYNTHETIC', 'Y', 'Demo-curated shorthand for Spangled Emperor.');

    upsert_curated('Hyperoglyphe antarctica', 'blue-eye', 'LOCAL_ALIAS', 'COMMONWEALTH_SESSF', null, 'Southern and eastern slope waters', 1980, null, null, null, 'AFMA Southern and Eastern Scalefish and Shark Fishery', c_sessf, 'SYNTHETIC', 'Y', 'Common shorthand for Blue-eye Trevalla.');
    upsert_curated('Hyperoglyphe antarctica', 'deepsea trevalla', 'MARKET_ALIAS', 'COMMONWEALTH_SESSF', null, null, 1990, null, null, null, 'FRDC Fishfiles WA West Coast Demersal Scale Fish Resource', c_wa_dem, 'SYNTHETIC', 'Y', 'Market-style descriptor for deepwater trevalla context.');
    upsert_curated('Helicolenus barathri', 'ocean perch', 'LOCAL_ALIAS', 'COMMONWEALTH_SESSF', null, 'South-east trawl and slope context', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'REFERENCE', 'N', 'Shortened name for Bigeye Ocean Perch.');
    upsert_curated('Rexea solandri', 'gemmie', 'LOCAL_ALIAS', 'COMMONWEALTH_SESSF', null, null, 1980, null, null, null, 'AFMA Southern and Eastern Scalefish and Shark Fishery', c_sessf, 'SYNTHETIC', 'Y', 'Fisher shorthand for Gemfish.');

    upsert_curated('Mustelus antarcticus', 'flake', 'MARKET_ALIAS', 'COMMONWEALTH_SESSF', null, 'Southern shark fishery and fish-and-chip market context', 1980, null, null, null, 'AFMA Southern and Eastern Scalefish and Shark Fishery', c_sessf, 'REFERENCE', 'N', 'Australian market label commonly associated with Gummy Shark; ambiguous without species verification.');
    upsert_curated('Mustelus antarcticus', 'gummy flake', 'MARKET_ALIAS', 'VIC_BASS_STRAIT', null, null, 1990, null, null, null, 'AFMA Southern and Eastern Scalefish and Shark Fishery', c_sessf, 'SYNTHETIC', 'Y', 'Demo-curated market label that makes the shark species explicit.');
    upsert_curated('Galeorhinus galeus', 'flake', 'LEGACY_ALIAS', 'COMMONWEALTH_SESSF', null, 'Legacy/ambiguous shark market context', 1980, 2026, null, null, 'AFMA Southern and Eastern Scalefish and Shark Fishery', c_sessf, 'LEGACY', 'N', 'Ambiguous legacy market label; school shark is subject to rebuilding context and should not be used without care.');

    upsert_curated('Nemadactylus valenciennesi', 'queen snapper', 'LOCAL_ALIAS', 'NSW_COAST', null, null, 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Legacy/local alias for Blue Morwong.');
    upsert_curated('Rachycentron canadum', 'black kingfish', 'STANDARD', 'QLD_GBR', null, null, 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'REFERENCE', 'N', 'Recognised alternative name for Cobia.');
    upsert_curated('Mugil cephalus', 'bully mullet', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Estuary hauling and coastal context', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Regional alias for Sea Mullet discussions.');
    upsert_curated('Girella tricuspidata', 'blackfish', 'LOCAL_ALIAS', 'NSW_COAST', null, 'Estuary and rock platform context', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'REFERENCE', 'N', 'Common local name for Luderick.');
    upsert_curated('Zeus faber', 'dory', 'LOCAL_ALIAS', 'NSW_COAST', null, null, 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'SYNTHETIC', 'Y', 'Short market/fisher alias for John Dory.');
    upsert_curated('Sardinops sagax', 'pilchard', 'STANDARD', 'SA_GAB', null, 'South Australian sardine and baitfish context', 1980, null, null, null, 'fish.gov.au New South Wales', 'https://fish.gov.au/jurisdiction/new-south-wales', 'REFERENCE', 'N', 'Common alternative name for Australian Sardine.');
    upsert_curated('Sarda australis', 'bonito', 'LOCAL_ALIAS', 'NSW_COAST', null, 'NSW Ocean Trap and Line context', 1980, null, null, null, 'FRDC Fishfiles NSW Ocean Trap and Line Fishery', c_nsw, 'REFERENCE', 'N', 'Shortened common name for Australian Bonito.');

    upsert_curated('Thunnus albacares', 'yellowfin', 'LOCAL_ALIAS', 'COMMONWEALTH_ETBF', null, 'Eastern tuna ports', 1980, null, 1, 12, 'AFMA Eastern Tuna and Billfish Fishery', c_etbf, 'SYNTHETIC', 'Y', 'Fishery shorthand for Yellowfin Tuna.');
    upsert_curated('Thunnus obesus', 'bigeye', 'LOCAL_ALIAS', 'COMMONWEALTH_ETBF', null, 'Eastern tuna ports', 1980, null, 1, 12, 'AFMA Eastern Tuna and Billfish Fishery', c_etbf, 'SYNTHETIC', 'Y', 'Fishery shorthand for Bigeye Tuna.');
    upsert_curated('Thunnus alalunga', 'albacore', 'LOCAL_ALIAS', 'COMMONWEALTH_ETBF', null, 'Eastern tuna ports', 1980, null, 1, 12, 'AFMA Eastern Tuna and Billfish Fishery', c_etbf, 'REFERENCE', 'N', 'Fishery common name for Albacore Tuna.');
    upsert_curated('Xiphias gladius', 'broadbill', 'LOCAL_ALIAS', 'COMMONWEALTH_ETBF', null, 'Eastern tuna and billfish ports', 1980, null, 1, 12, 'AFMA Eastern Tuna and Billfish Fishery', c_etbf, 'REFERENCE', 'N', 'Short common name for Broadbill Swordfish.');
    upsert_curated('Kajikia audax', 'stripey', 'LOCAL_ALIAS', 'COMMONWEALTH_ETBF', null, 'Eastern tuna and billfish ports', 1990, null, 1, 12, 'AFMA Eastern Tuna and Billfish Fishery', c_etbf, 'SYNTHETIC', 'Y', 'Demo-curated shorthand for Striped Marlin.');
    upsert_curated('Thunnus albacares', 'yellowfin', 'LOCAL_ALIAS', 'COMMONWEALTH_WTBF', null, 'Western tuna ports', 1980, null, 2, 1, 'AFMA Western Tuna and Billfish Fishery', c_wtbf, 'SYNTHETIC', 'Y', 'Fishery shorthand for Yellowfin Tuna in western fishery context.');
  end seed_curated_demo_names;

  procedure rebuild_all is
  begin
    rebuild_from_caab_data;
    seed_curated_demo_names;
  end rebuild_all;
end csiro_caab_common_name_api;
/

begin
  csiro_caab_common_name_api.rebuild_all;
end;
/

comment on table csiro_caab_fishing_regions is 'Australian fishing regions used to scope demo common-name aliases for CSIRO CAAB taxa.';
/
comment on table csiro_caab_common_names is 'CSIRO-derived and AFMA demo-curated common names, market names, local aliases, and legacy aliases keyed to CSIRO CAAB SPCODE.';
/
comment on column csiro_caab_common_names.synthetic_flag is 'Y when the row is demo-curated or synthetic rather than directly sourced from CSIRO/reference material.';
/

prompt AFMA 025 complete
