set define off

-- Execution authority: AFMA parsing schema owner through the verified AFMA APEX SQL Commands session.
-- Target: AIDEMODB workspace/schema AFMA; additive database objects for application 101.
prompt AFMA 100 - Create Catch Monitor foundation

declare
  procedure create_table_if_missing(
    p_table_name in varchar2,
    p_sql        in clob
  ) is
    l_count number;
  begin
    select count(*)
      into l_count
      from user_tables
     where table_name = upper(p_table_name);

    if l_count = 0 then
      execute immediate p_sql;
    end if;
  end create_table_if_missing;
begin
  create_table_if_missing('AFMA_CM_TRIPS', q'[
    create table afma_cm_trips (
      trip_id              number generated by default on null as identity,
      trip_ref             varchar2(40 char) not null,
      source_type          varchar2(30 char) default 'SYNTHETIC_DEMO' not null,
      fishery_name         varchar2(200 char) not null,
      gear_method          varchar2(120 char),
      region_name          varchar2(160 char),
      vessel_ref           varchar2(120 char),
      trip_start_at        timestamp with local time zone,
      trip_end_at          timestamp with local time zone,
      status               varchar2(30 char) default 'READY_FOR_REVIEW' not null,
      retention_review_at  date,
      notes                varchar2(2000 char),
      created_at           timestamp with local time zone default systimestamp not null,
      created_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      updated_at           timestamp with local time zone default systimestamp not null,
      updated_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      constraint afma_cm_trips_pk primary key (trip_id),
      constraint afma_cm_trips_uq_ref unique (trip_ref),
      constraint afma_cm_trips_ck_source check (source_type in ('SYNTHETIC_DEMO','RECEIVED_RECORD')),
      constraint afma_cm_trips_ck_status check (status in ('DRAFT','READY_FOR_REVIEW','IN_REVIEW','REVIEW_COMPLETE','ARCHIVED'))
    )
  ]');

  create_table_if_missing('AFMA_CM_REPORT_VERSIONS', q'[
    create table afma_cm_report_versions (
      report_version_id    number generated by default on null as identity,
      trip_id              number not null,
      version_no           number not null,
      report_status        varchar2(30 char) default 'DRAFT' not null,
      source_type          varchar2(30 char) default 'SYNTHETIC_DEMO' not null,
      source_provenance    varchar2(1000 char),
      amendment_reason     varchar2(1000 char),
      parent_version_id    number,
      recorded_at          timestamp with local time zone default systimestamp not null,
      frozen_at            timestamp with local time zone,
      frozen_by            varchar2(255 char),
      created_at           timestamp with local time zone default systimestamp not null,
      created_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      constraint afma_cm_report_versions_pk primary key (report_version_id),
      constraint afma_cm_report_versions_uq unique (trip_id, version_no),
      constraint afma_cm_report_versions_fk_trip foreign key (trip_id) references afma_cm_trips (trip_id),
      constraint afma_cm_report_versions_fk_parent foreign key (parent_version_id) references afma_cm_report_versions (report_version_id),
      constraint afma_cm_report_versions_ck_status check (report_status in ('DRAFT','RECORDED','FROZEN_FOR_REVIEW','AMENDED')),
      constraint afma_cm_report_versions_ck_source check (source_type in ('SYNTHETIC_DEMO','RECEIVED_RECORD'))
    )
  ]');

  create_table_if_missing('AFMA_CM_OPERATIONS', q'[
    create table afma_cm_operations (
      operation_id         number generated by default on null as identity,
      report_version_id    number not null,
      operation_no         number not null,
      set_at               timestamp with local time zone,
      haul_at              timestamp with local time zone,
      location_text        varchar2(240 char),
      gear_method          varchar2(120 char),
      effort_text          varchar2(500 char),
      constraint afma_cm_operations_pk primary key (operation_id),
      constraint afma_cm_operations_uq unique (report_version_id, operation_no),
      constraint afma_cm_operations_fk_report foreign key (report_version_id) references afma_cm_report_versions (report_version_id)
    )
  ]');

  create_table_if_missing('AFMA_CM_REPORTED_CATCH', q'[
    create table afma_cm_reported_catch (
      reported_catch_id    number generated by default on null as identity,
      operation_id         number not null,
      original_taxon_text  varchar2(300 char) not null,
      spcode                varchar2(20 char),
      mapping_status        varchar2(30 char) default 'UNRESOLVED' not null,
      mapping_method        varchar2(60 char),
      mapping_confidence    number,
      reported_count       number,
      reported_weight_kg   number,
      catch_state          varchar2(30 char) default 'UNKNOWN' not null,
      discard_reason       varchar2(500 char),
      processing_state     varchar2(120 char),
      notes                 varchar2(1000 char),
      created_at            timestamp with local time zone default systimestamp not null,
      created_by            varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      constraint afma_cm_reported_catch_pk primary key (reported_catch_id),
      constraint afma_cm_reported_catch_fk_operation foreign key (operation_id) references afma_cm_operations (operation_id),
      constraint afma_cm_reported_catch_fk_caab foreign key (spcode) references csiro_caab_taxa (spcode),
      constraint afma_cm_reported_catch_ck_mapping check (mapping_status in ('MATCHED','MULTIPLE_CANDIDATES','HIGHER_TAXON','NOT_IN_CAAB','UNRESOLVED')),
      constraint afma_cm_reported_catch_ck_state check (catch_state in ('RETAINED','DISCARDED_ALIVE','DISCARDED_DEAD','UNKNOWN','NOT_CATCH'))
    )
  ]');

  create_table_if_missing('AFMA_CM_REPORTED_INTERACTIONS', q'[
    create table afma_cm_reported_interactions (
      reported_interaction_id number generated by default on null as identity,
      operation_id             number not null,
      original_taxon_text      varchar2(300 char) not null,
      spcode                    varchar2(20 char),
      reported_count           number,
      event_at                  timestamp with local time zone,
      fishing_stage             varchar2(120 char),
      interaction_kind          varchar2(80 char),
      life_injury_status        varchar2(120 char),
      release_action            varchar2(500 char),
      notes                     varchar2(1000 char),
      constraint afma_cm_reported_interactions_pk primary key (reported_interaction_id),
      constraint afma_cm_reported_interactions_fk_op foreign key (operation_id) references afma_cm_operations (operation_id),
      constraint afma_cm_reported_interactions_fk_caab foreign key (spcode) references csiro_caab_taxa (spcode)
    )
  ]');

  create_table_if_missing('AFMA_CM_MEDIA_ASSETS', q'[
    create table afma_cm_media_assets (
      media_asset_id       number generated by default on null as identity,
      trip_id              number,
      spcode                varchar2(20 char),
      original_taxon_text  varchar2(300 char),
      asset_type           varchar2(30 char) not null,
      asset_role           varchar2(40 char) not null,
      title                varchar2(500 char) not null,
      source_system        varchar2(120 char),
      source_record_url    varchar2(2000 char) not null,
      embed_url            varchar2(2000 char),
      creator_provider     varchar2(500 char),
      australian_region    varchar2(200 char),
      rights_status        varchar2(40 char) not null,
      licence_text         varchar2(500 char),
      attribution_text     varchar2(1000 char),
      approved_purposes    varchar2(500 char),
      restrictions         varchar2(1000 char),
      rights_checked_at    date,
      private_object_uri   varchar2(2000 char),
      mime_type            varchar2(120 char),
      duration_seconds     number,
      file_bytes           number,
      sha256               varchar2(64 char),
      view_type            varchar2(80 char),
      quality_rating       varchar2(30 char),
      expert_review_status varchar2(30 char) default 'PENDING' not null,
      dataset_split        varchar2(30 char) default 'REFERENCE' not null,
      coverage_status      varchar2(40 char) default 'MEDIA_GAP' not null,
      created_at           timestamp with local time zone default systimestamp not null,
      constraint afma_cm_media_assets_pk primary key (media_asset_id),
      constraint afma_cm_media_assets_fk_trip foreign key (trip_id) references afma_cm_trips (trip_id),
      constraint afma_cm_media_assets_fk_caab foreign key (spcode) references csiro_caab_taxa (spcode),
      constraint afma_cm_media_assets_ck_type check (asset_type in ('VIDEO','IMAGE','CLIP','FRAME','GUIDE')),
      constraint afma_cm_media_assets_ck_rights check (rights_status in ('CONFIRMED','UNCONFIRMED_INTERNAL_ONLY','RESTRICTED','PROHIBITED','TAKEDOWN')),
      constraint afma_cm_media_assets_ck_split check (dataset_split in ('REFERENCE','TRAIN','VALIDATION','TEST','DEMO')),
      constraint afma_cm_media_assets_ck_coverage check (coverage_status in ('COVERED','MEDIA_GAP','NEEDS_TAXON_REVIEW','UNCONFIRMED_INTERNAL_ONLY'))
    )
  ]');

  create_table_if_missing('AFMA_CM_ANALYSIS_RUNS', q'[
    create table afma_cm_analysis_runs (
      analysis_run_id      number generated by default on null as identity,
      trip_id              number not null,
      report_version_id    number not null,
      media_asset_id       number not null,
      analysis_mode        varchar2(40 char) not null,
      model_version        varchar2(200 char) not null,
      media_manifest       varchar2(200 char) not null,
      run_status           varchar2(30 char) default 'COMPLETE' not null,
      started_at           timestamp with local time zone default systimestamp not null,
      completed_at         timestamp with local time zone,
      run_notes            varchar2(2000 char),
      constraint afma_cm_analysis_runs_pk primary key (analysis_run_id),
      constraint afma_cm_analysis_runs_fk_trip foreign key (trip_id) references afma_cm_trips (trip_id),
      constraint afma_cm_analysis_runs_fk_report foreign key (report_version_id) references afma_cm_report_versions (report_version_id),
      constraint afma_cm_analysis_runs_fk_media foreign key (media_asset_id) references afma_cm_media_assets (media_asset_id),
      constraint afma_cm_analysis_runs_ck_mode check (analysis_mode in ('SIMULATED_DEMO','VISION_MODEL')),
      constraint afma_cm_analysis_runs_ck_status check (run_status in ('QUEUED','RUNNING','COMPLETE','FAILED'))
    )
  ]');

  create_table_if_missing('AFMA_CM_OBSERVATIONS', q'[
    create table afma_cm_observations (
      observation_id       number generated by default on null as identity,
      analysis_run_id      number not null,
      observation_type     varchar2(30 char) not null,
      start_second         number not null,
      end_second           number,
      ai_taxon_text        varchar2(300 char),
      ai_spcode            varchar2(20 char),
      ai_count             number,
      ai_confidence        number,
      ai_catch_state       varchar2(30 char),
      ai_interaction_class varchar2(40 char),
      evidence_text        varchar2(1000 char),
      reviewer_status      varchar2(30 char) default 'NEEDS_REVIEW' not null,
      reviewed_spcode      varchar2(20 char),
      reviewed_count       number,
      reviewed_interaction_class varchar2(40 char),
      reviewer_notes       varchar2(2000 char),
      reviewed_at          timestamp with local time zone,
      reviewed_by          varchar2(255 char),
      constraint afma_cm_observations_pk primary key (observation_id),
      constraint afma_cm_observations_fk_run foreign key (analysis_run_id) references afma_cm_analysis_runs (analysis_run_id),
      constraint afma_cm_observations_fk_ai_caab foreign key (ai_spcode) references csiro_caab_taxa (spcode),
      constraint afma_cm_observations_fk_review_caab foreign key (reviewed_spcode) references csiro_caab_taxa (spcode),
      constraint afma_cm_observations_ck_type check (observation_type in ('CATCH','WILDLIFE')),
      constraint afma_cm_observations_ck_review check (reviewer_status in ('NEEDS_REVIEW','CONFIRMED','CORRECTED','REJECTED','ESCALATED')),
      constraint afma_cm_observations_ck_interaction check (ai_interaction_class in ('NOT_APPLICABLE','SIGHTING','POSSIBLE_INTERACTION','CONFIRMED_INTERACTION','INCONCLUSIVE')),
      constraint afma_cm_observations_ck_r_interaction check (reviewed_interaction_class is null or reviewed_interaction_class in ('NOT_APPLICABLE','SIGHTING','POSSIBLE_INTERACTION','CONFIRMED_INTERACTION','INCONCLUSIVE'))
    )
  ]');

  create_table_if_missing('AFMA_CM_AUDIT_EVENTS', q'[
    create table afma_cm_audit_events (
      audit_event_id       number generated by default on null as identity,
      trip_id              number,
      entity_type          varchar2(60 char) not null,
      entity_id            number,
      action_name          varchar2(80 char) not null,
      detail_text          varchar2(2000 char),
      occurred_at          timestamp with local time zone default systimestamp not null,
      occurred_by          varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
      constraint afma_cm_audit_events_pk primary key (audit_event_id),
      constraint afma_cm_audit_events_fk_trip foreign key (trip_id) references afma_cm_trips (trip_id)
    )
  ]');
end;
/

create or replace trigger afma_cm_trips_biu
  before insert or update on afma_cm_trips
  for each row
begin
  if inserting then
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, coalesce(sys_context('APEX$SESSION','APP_USER'), user));
  end if;
  :new.updated_at := systimestamp;
  :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), user);
end;
/

create or replace view afma_cm_trip_summary_v as
with latest_report as (
  select rv.*,
         row_number() over (partition by rv.trip_id order by rv.version_no desc) rn
    from afma_cm_report_versions rv
)
select t.trip_id,
       t.trip_ref,
       t.source_type,
       t.fishery_name,
       t.gear_method,
       t.region_name,
       t.status,
       rv.report_version_id,
       rv.version_no,
       rv.report_status,
       count(distinct rc.reported_catch_id) reported_lines,
       count(distinct o.observation_id) observations,
       count(distinct case when o.reviewer_status = 'NEEDS_REVIEW' then o.observation_id end) needs_review
  from afma_cm_trips t
  left join latest_report rv
    on rv.trip_id = t.trip_id
   and rv.rn = 1
  left join afma_cm_operations op on op.report_version_id = rv.report_version_id
  left join afma_cm_reported_catch rc on rc.operation_id = op.operation_id
  left join afma_cm_analysis_runs ar on ar.trip_id = t.trip_id and ar.report_version_id = rv.report_version_id
  left join afma_cm_observations o on o.analysis_run_id = ar.analysis_run_id
 group by t.trip_id, t.trip_ref, t.source_type, t.fishery_name, t.gear_method,
          t.region_name, t.status, rv.report_version_id, rv.version_no, rv.report_status;
/

create or replace view afma_cm_media_coverage_v as
select coalesce(m.spcode, '(unresolved)') spcode,
       coalesce(t.scientific_name, m.original_taxon_text, '(not supplied)') scientific_or_original_name,
       coalesce(t.common_name, m.original_taxon_text, '(not supplied)') display_name,
       m.coverage_status,
       m.rights_status,
       count(*) asset_count,
       count(case when instr(',' || upper(m.approved_purposes) || ',', ',REFERENCE_DISPLAY,') > 0 then 1 end) reference_assets,
       count(case when instr(',' || upper(m.approved_purposes) || ',', ',TRAINING,') > 0 then 1 end) training_assets
  from afma_cm_media_assets m
  left join csiro_caab_taxa t on t.spcode = m.spcode
 group by coalesce(m.spcode, '(unresolved)'),
          coalesce(t.scientific_name, m.original_taxon_text, '(not supplied)'),
          coalesce(t.common_name, m.original_taxon_text, '(not supplied)'),
          m.coverage_status,
          m.rights_status;
/

comment on table afma_cm_trips is 'AFMA Catch Monitor review cases. Fishers are source subjects, not application users.';
/
comment on table afma_cm_report_versions is 'Versioned reported-data baseline; frozen versions are immutable comparison evidence.';
/
comment on table afma_cm_media_assets is 'Governed CAAB-linked media metadata. Binary video and images remain in approved private storage.';
/
comment on table afma_cm_observations is 'AI-proposed evidence events kept separate from authorised reviewer decisions.';
/

prompt AFMA 100 complete
