set define off

-- Execution authority: AFMA parsing schema owner through the verified AFMA APEX SQL Commands session.
-- Target: AIDEMODB workspace/schema AFMA; authorised tester video intake for application 101.
prompt AFMA 115 - Add Catch Monitor video intake

declare
  l_count number;
begin
  select count(*)
    into l_count
    from user_tables
   where table_name = 'AFMA_CM_VIDEO_SUBMISSIONS';

  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_video_submissions (
        submission_id             number generated by default on null as identity,
        submission_ref            varchar2(40 char) not null,
        input_method              varchar2(10 char) not null,
        submitted_title           varchar2(500 char),
        submitted_description     varchar2(2000 char),
        display_title             varchar2(500 char) not null,
        description_text          varchar2(2000 char),
        region_text               varchar2(500 char),
        fishery_text              varchar2(500 char),
        gear_method_text          varchar2(500 char),
        ai_display_title          varchar2(500 char),
        ai_description_text       varchar2(2000 char),
        ai_region_text            varchar2(500 char),
        ai_fishery_text           varchar2(500 char),
        ai_gear_method_text       varchar2(500 char),
        ai_video_summary          varchar2(4000 char),
        ai_metadata_confidence    number,
        metadata_status           varchar2(30 char) default 'NOT_REQUESTED' not null,
        metadata_model_id         varchar2(200 char),
        metadata_prompt_version   varchar2(100 char),
        metadata_response_json    clob,
        metadata_generated_at     timestamp with local time zone,
        metadata_reviewed_at      timestamp with local time zone,
        metadata_reviewed_by      varchar2(255 char),
        source_url                varchar2(2000 char),
        original_filename         varchar2(500 char),
        mime_type                 varchar2(200 char),
        video_blob                blob,
        file_bytes                number,
        processing_status         varchar2(40 char) default 'AWAITING_PROMPT_APPROVAL' not null,
        processing_stage          varchar2(40 char) default 'RECEIVED' not null,
        progress_percent          number default 0 not null,
        processing_message        varchar2(1000 char),
        processing_started_at     timestamp with local time zone,
        processing_completed_at   timestamp with local time zone,
        last_progress_at          timestamp with local time zone,
        worker_job_ref            varchar2(200 char),
        model_id                  varchar2(200 char) default 'google.gemini-2.5-pro' not null,
        storage_region            varchar2(40 char) default 'ap-sydney-1' not null,
        inference_entry_region    varchar2(40 char) default 'us-chicago-1' not null,
        processor_location        varchar2(80 char) default 'GOOGLE_AMERICAS' not null,
        handling_notice_version   varchar2(80 char) default 'OCI-GEMINI-DISCLOSURE-2026-09-28-V1' not null,
        rights_confirmed_yn       varchar2(1 char) not null,
        handling_acknowledged_yn varchar2(1 char) not null,
        retention_review_at       date default trunc(sysdate) + 30 not null,
        analysis_run_id           number,
        created_at                timestamp with local time zone default systimestamp not null,
        created_by                varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        updated_at                timestamp with local time zone default systimestamp not null,
        updated_by                varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        deleted_at                timestamp with local time zone,
        deleted_by                varchar2(255 char),
        constraint afma_cm_video_submissions_pk primary key (submission_id),
        constraint afma_cm_video_submissions_uq unique (submission_ref),
        constraint afma_cm_video_submissions_fk_run foreign key (analysis_run_id) references afma_cm_analysis_runs (analysis_run_id),
        constraint afma_cm_video_submissions_ck_method check (input_method in ('UPLOAD','URL')),
        constraint afma_cm_video_submissions_ck_status check (processing_status in ('AWAITING_PROMPT_APPROVAL','AWAITING_IMPORT','READY_FOR_ANALYSIS','ANALYSING','ANALYSIS_COMPLETE','ANALYSIS_FAILED','DELETED')),
        constraint afma_cm_video_submissions_ck_progress check (progress_percent between 0 and 100),
        constraint afma_cm_video_submissions_ck_rights check (rights_confirmed_yn in ('Y','N')),
        constraint afma_cm_video_submissions_ck_notice check (handling_acknowledged_yn in ('Y','N')),
        constraint afma_cm_video_submissions_ck_meta_status check (metadata_status in ('NOT_REQUESTED','AWAITING_PROMPT_APPROVAL','ANALYSING','NEEDS_REVIEW','CONFIRMED','CORRECTED','FAILED')),
        constraint afma_cm_video_submissions_ck_meta_conf check (ai_metadata_confidence between 0 and 1),
        constraint afma_cm_video_submissions_ck_payload check (
          (input_method = 'UPLOAD' and video_blob is not null and source_url is null)
          or (input_method = 'URL' and source_url is not null and video_blob is null)
          or processing_status = 'DELETED'
        )
      )
    ]';
  end if;
end;
/

-- The script is rerunnable against the live demo table created by an earlier
-- iteration of this feature. New AI-proposal and reviewer-final columns are
-- added without replacing any submitted metadata.
declare
  procedure add_column_if_missing(
    p_column_name in varchar2,
    p_definition  in varchar2
  ) is
    l_count number;
  begin
    select count(*)
      into l_count
      from user_tab_columns
     where table_name = 'AFMA_CM_VIDEO_SUBMISSIONS'
       and column_name = upper(p_column_name);
    if l_count = 0 then
      execute immediate 'alter table afma_cm_video_submissions add (' || p_definition || ')';
    end if;
  end add_column_if_missing;
begin
  add_column_if_missing('SUBMITTED_TITLE', 'submitted_title varchar2(500 char)');
  add_column_if_missing('SUBMITTED_DESCRIPTION', 'submitted_description varchar2(2000 char)');
  add_column_if_missing('REGION_TEXT', 'region_text varchar2(500 char)');
  add_column_if_missing('FISHERY_TEXT', 'fishery_text varchar2(500 char)');
  add_column_if_missing('GEAR_METHOD_TEXT', 'gear_method_text varchar2(500 char)');
  add_column_if_missing('AI_DISPLAY_TITLE', 'ai_display_title varchar2(500 char)');
  add_column_if_missing('AI_DESCRIPTION_TEXT', 'ai_description_text varchar2(2000 char)');
  add_column_if_missing('AI_REGION_TEXT', 'ai_region_text varchar2(500 char)');
  add_column_if_missing('AI_FISHERY_TEXT', 'ai_fishery_text varchar2(500 char)');
  add_column_if_missing('AI_GEAR_METHOD_TEXT', 'ai_gear_method_text varchar2(500 char)');
  add_column_if_missing('AI_VIDEO_SUMMARY', 'ai_video_summary varchar2(4000 char)');
  add_column_if_missing('AI_METADATA_CONFIDENCE', 'ai_metadata_confidence number');
  add_column_if_missing('METADATA_STATUS', q'[metadata_status varchar2(30 char) default 'NOT_REQUESTED' not null]');
  add_column_if_missing('METADATA_MODEL_ID', 'metadata_model_id varchar2(200 char)');
  add_column_if_missing('METADATA_PROMPT_VERSION', 'metadata_prompt_version varchar2(100 char)');
  add_column_if_missing('METADATA_RESPONSE_JSON', 'metadata_response_json clob');
  add_column_if_missing('METADATA_GENERATED_AT', 'metadata_generated_at timestamp with local time zone');
  add_column_if_missing('METADATA_REVIEWED_AT', 'metadata_reviewed_at timestamp with local time zone');
  add_column_if_missing('METADATA_REVIEWED_BY', 'metadata_reviewed_by varchar2(255 char)');
  add_column_if_missing('PROCESSING_STAGE', q'[processing_stage varchar2(40 char) default 'RECEIVED' not null]');
  add_column_if_missing('PROGRESS_PERCENT', 'progress_percent number default 0 not null');
  add_column_if_missing('PROCESSING_MESSAGE', 'processing_message varchar2(1000 char)');
  add_column_if_missing('PROCESSING_STARTED_AT', 'processing_started_at timestamp with local time zone');
  add_column_if_missing('PROCESSING_COMPLETED_AT', 'processing_completed_at timestamp with local time zone');
  add_column_if_missing('LAST_PROGRESS_AT', 'last_progress_at timestamp with local time zone');
  add_column_if_missing('WORKER_JOB_REF', 'worker_job_ref varchar2(200 char)');

end;
/

update afma_cm_video_submissions
   set submitted_title = coalesce(submitted_title, display_title),
       submitted_description = coalesce(submitted_description, description_text),
       metadata_status = coalesce(metadata_status, 'NOT_REQUESTED');

declare
  l_count number;
begin
  select count(*) into l_count from user_constraints where constraint_name = 'AFMA_CM_VIDEO_SUBMISSIONS_CK_META_STATUS';
  if l_count = 0 then
    execute immediate q'[alter table afma_cm_video_submissions add constraint afma_cm_video_submissions_ck_meta_status check (metadata_status in ('NOT_REQUESTED','AWAITING_PROMPT_APPROVAL','ANALYSING','NEEDS_REVIEW','CONFIRMED','CORRECTED','FAILED'))]';
  end if;
  select count(*) into l_count from user_constraints where constraint_name = 'AFMA_CM_VIDEO_SUBMISSIONS_CK_META_CONF';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_video_submissions add constraint afma_cm_video_submissions_ck_meta_conf check (ai_metadata_confidence between 0 and 1)';
  end if;
  select count(*) into l_count from user_constraints where constraint_name = 'AFMA_CM_VIDEO_SUBMISSIONS_CK_PROGRESS';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_video_submissions add constraint afma_cm_video_submissions_ck_progress check (progress_percent between 0 and 100)';
  end if;
  select count(*) into l_count from user_constraints where constraint_name = 'AFMA_CM_VIDEO_SUBMISSIONS_CK_STATUS';
  if l_count = 1 then
    execute immediate 'alter table afma_cm_video_submissions drop constraint afma_cm_video_submissions_ck_status';
  end if;
  execute immediate q'[alter table afma_cm_video_submissions add constraint afma_cm_video_submissions_ck_status check (processing_status in ('AWAITING_PROMPT_APPROVAL','AWAITING_IMPORT','READY_FOR_ANALYSIS','ANALYSING','ANALYSIS_COMPLETE','ANALYSIS_FAILED','DELETED'))]';
end;
/

create or replace trigger afma_cm_video_submissions_biu
  before insert or update on afma_cm_video_submissions
  for each row
begin
  if inserting then
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, coalesce(sys_context('APEX$SESSION','APP_USER'), user));
  end if;
  :new.updated_at := systimestamp;
  :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'), user);
end;
/

create or replace package afma_cm_video_intake_api as
  c_max_upload_bytes constant pls_integer := 36700160;

  function stage_url(
    p_title                    in varchar2,
    p_description              in varchar2,
    p_source_url               in varchar2,
    p_rights_confirmed_yn      in varchar2,
    p_handling_acknowledged_yn in varchar2
  ) return number;

  function stage_upload(
    p_title                    in varchar2,
    p_description              in varchar2,
    p_apex_temp_file_name      in varchar2,
    p_rights_confirmed_yn      in varchar2,
    p_handling_acknowledged_yn in varchar2
  ) return number;

  procedure delete_submission(
    p_submission_id in number
  );

  procedure approve_submission(
    p_submission_id   in number,
    p_acknowledged_yn in varchar2
  );

  procedure save_reviewed_metadata(
    p_submission_id in number,
    p_title         in varchar2,
    p_description   in varchar2,
    p_region        in varchar2,
    p_fishery       in varchar2,
    p_gear_method   in varchar2
  );
end afma_cm_video_intake_api;
/

create or replace package body afma_cm_video_intake_api as
  function actor_name return varchar2 is
  begin
    return coalesce(sys_context('APEX$SESSION','APP_USER'), user);
  end actor_name;

  procedure assert_acknowledgements(
    p_rights_confirmed_yn      in varchar2,
    p_handling_acknowledged_yn in varchar2
  ) is
  begin
    if upper(coalesce(p_rights_confirmed_yn, 'N')) <> 'Y' then
      raise_application_error(-20060, 'Confirm that AFMA is authorised to use this video for internal evaluation.');
    end if;
    if upper(coalesce(p_handling_acknowledged_yn, 'N')) <> 'Y' then
      raise_application_error(-20061, 'Acknowledge the displayed storage and processing notice before submitting.');
    end if;
  end assert_acknowledgements;

  function new_ref return varchar2 is
  begin
    return 'CM-SUB-' || lower(substr(rawtohex(sys_guid()), 1, 12));
  end new_ref;

  procedure ensure_review_scenario(
    p_submission_id in number
  ) is
    l_submission afma_cm_video_submissions%rowtype;
    l_trip_id number;
    l_report_version_id number;
    l_media_asset_id number;
    l_analysis_run_id number;
  begin
    select *
      into l_submission
      from afma_cm_video_submissions
     where submission_id = p_submission_id
       and processing_status in ('AWAITING_IMPORT','READY_FOR_ANALYSIS','ANALYSING','ANALYSIS_COMPLETE')
     for update;

    if l_submission.analysis_run_id is not null then
      return;
    end if;

    begin
      insert into afma_cm_trips (
        trip_ref, source_type, fishery_name, gear_method, region_name,
        status, retention_review_at, notes
      ) values (
        l_submission.submission_ref,
        'RECEIVED_RECORD',
        coalesce(l_submission.fishery_text, l_submission.display_title),
        coalesce(l_submission.gear_method_text, 'Method not yet determined'),
        coalesce(l_submission.region_text, 'Location not yet determined'),
        'READY_FOR_REVIEW',
        l_submission.retention_review_at,
        substr(coalesce(l_submission.description_text || ' ', '') ||
          'Source approved for controlled internal testing. Analysis has not started.', 1, 2000)
      ) returning trip_id into l_trip_id;
    exception
      when dup_val_on_index then
        select trip_id into l_trip_id from afma_cm_trips where trip_ref = l_submission.submission_ref;
    end;

    begin
      select report_version_id
        into l_report_version_id
        from afma_cm_report_versions
       where trip_id = l_trip_id
         and version_no = 1;
    exception
      when no_data_found then
        insert into afma_cm_report_versions (
          trip_id, version_no, report_status, source_type, source_provenance
        ) values (
          l_trip_id, 1, 'DRAFT', 'RECEIVED_RECORD',
          'Created from approved Catch Monitor submission ' || l_submission.submission_ref || '; fisher-reported comparison data not yet entered.'
        ) returning report_version_id into l_report_version_id;

        insert into afma_cm_operations (
          report_version_id, operation_no, location_text, gear_method, effort_text
        ) values (
          l_report_version_id, 1,
          l_submission.region_text,
          l_submission.gear_method_text,
          'Awaiting normal fisher-reported inputs for comparison.'
        );
    end;

    begin
      select media_asset_id
        into l_media_asset_id
        from afma_cm_media_assets
       where trip_id = l_trip_id
         and asset_role = 'SOURCE_VIDEO'
       fetch first 1 row only;
    exception
      when no_data_found then
        insert into afma_cm_media_assets (
          trip_id, asset_type, asset_role, title, source_system,
          source_record_url, embed_url, creator_provider, australian_region,
          rights_status, licence_text, approved_purposes, restrictions,
          rights_checked_at, mime_type, file_bytes, quality_rating,
          expert_review_status, dataset_split, coverage_status
        ) values (
          l_trip_id,
          'VIDEO',
          'SOURCE_VIDEO',
          l_submission.display_title,
          case when l_submission.input_method = 'URL' then 'AFMA registered test URL' else 'AFMA uploaded test video' end,
          coalesce(l_submission.source_url, 'urn:afma:catch-monitor:' || l_submission.submission_ref),
          null,
          l_submission.created_by,
          l_submission.region_text,
          'UNCONFIRMED_INTERNAL_ONLY',
          'Submitter confirmed AFMA authority for controlled internal evaluation; independent licence review not completed.',
          'Controlled internal Catch Monitor testing and reviewer assessment.',
          case when l_submission.input_method = 'URL' then 'URL metadata only. Open the registered host separately; video bytes are not stored in AIDEMODB.' else 'Uploaded bytes stored in AIDEMODB; reviewer-controlled processing only.' end,
          trunc(sysdate),
          l_submission.mime_type,
          l_submission.file_bytes,
          'PENDING',
          'PENDING',
          'DEMO',
          'MEDIA_GAP'
        ) returning media_asset_id into l_media_asset_id;
    end;

    insert into afma_cm_analysis_runs (
      trip_id, report_version_id, media_asset_id, analysis_mode,
      model_version, media_manifest, run_status, run_notes
    ) values (
      l_trip_id,
      l_report_version_id,
      l_media_asset_id,
      'VISION_MODEL',
      'analysis-not-started',
      'submission-' || l_submission.submission_ref,
      'QUEUED',
      'Source approved for controlled internal testing. No model call has been started and no evidence events have been published.'
    ) returning analysis_run_id into l_analysis_run_id;

    update afma_cm_video_submissions
       set analysis_run_id = l_analysis_run_id
     where submission_id = p_submission_id;
  end ensure_review_scenario;

  function stage_url(
    p_title                    in varchar2,
    p_description              in varchar2,
    p_source_url               in varchar2,
    p_rights_confirmed_yn      in varchar2,
    p_handling_acknowledged_yn in varchar2
  ) return number is
    l_submission_id number;
    l_url varchar2(2000) := trim(p_source_url);
    l_submission_ref varchar2(40) := new_ref;
  begin
    assert_acknowledgements(p_rights_confirmed_yn, p_handling_acknowledged_yn);

    if l_url is null or not regexp_like(l_url, '^https://[^[:space:]]+$', 'i') then
      raise_application_error(-20063, 'Enter an HTTPS video or video-page URL.');
    end if;
    if regexp_like(l_url, '^https://[^/]*@', 'i') then
      raise_application_error(-20064, 'Do not submit URLs containing embedded usernames, passwords or tokens.');
    end if;

    insert into afma_cm_video_submissions (
      submission_ref,
      input_method,
      submitted_title,
      submitted_description,
      display_title,
      description_text,
      source_url,
      processing_status,
      processing_stage,
      progress_percent,
      processing_message,
      processing_started_at,
      last_progress_at,
      metadata_status,
      rights_confirmed_yn,
      handling_acknowledged_yn
    ) values (
      l_submission_ref,
      'URL',
      trim(p_title),
      trim(p_description),
      coalesce(trim(p_title), 'Untitled URL submission'),
      trim(p_description),
      l_url,
      'AWAITING_IMPORT',
      'AWAITING_PROJECT_IMPORT',
      5,
      'The source URL is registered for this project to import when requested. No video bytes are stored and no model call has started.',
      systimestamp,
      systimestamp,
      'NOT_REQUESTED',
      'Y',
      'Y'
    ) returning submission_id into l_submission_id;

    ensure_review_scenario(l_submission_id);

    return l_submission_id;
  end stage_url;

  function stage_upload(
    p_title                    in varchar2,
    p_description              in varchar2,
    p_apex_temp_file_name      in varchar2,
    p_rights_confirmed_yn      in varchar2,
    p_handling_acknowledged_yn in varchar2
  ) return number is
    l_submission_id number;
    l_filename apex_application_temp_files.filename%type;
    l_mime_type apex_application_temp_files.mime_type%type;
    l_blob blob;
    l_bytes number;
    l_extension varchar2(20);
    l_submission_ref varchar2(40) := new_ref;
  begin
    assert_acknowledgements(p_rights_confirmed_yn, p_handling_acknowledged_yn);

    if p_apex_temp_file_name is null then
      raise_application_error(-20065, 'Choose a video file to upload.');
    end if;

    begin
      select filename,
             mime_type,
             blob_content,
             dbms_lob.getlength(blob_content)
        into l_filename,
             l_mime_type,
             l_blob,
             l_bytes
        from apex_application_temp_files
       where name = p_apex_temp_file_name
          or filename = p_apex_temp_file_name
       order by created_on desc
       fetch first 1 row only;
    exception
      when no_data_found then
        raise_application_error(-20066, 'The temporary upload could not be found. Select the file again.');
    end;

    if l_bytes is null or l_bytes = 0 then
      raise_application_error(-20067, 'The selected file is empty.');
    end if;
    if l_bytes > c_max_upload_bytes then
      raise_application_error(-20068, 'The current direct-analysis limit is 35 MiB. Use a shorter clip or register an HTTPS URL.');
    end if;

    l_extension := lower(regexp_substr(l_filename, '\.[^.]+$'));
    if lower(coalesce(l_mime_type, 'application/octet-stream')) not like 'video/%'
       and coalesce(l_extension, '~') not in ('.mp4','.mpeg','.mpg','.mov','.avi','.webm','.wmv','.3gp','.3gpp','.flv') then
      raise_application_error(-20069, 'Unsupported video type. Use MP4, MPEG, MOV, AVI, WebM, WMV, 3GPP or FLV.');
    end if;

    insert into afma_cm_video_submissions (
      submission_ref,
      input_method,
      submitted_title,
      submitted_description,
      display_title,
      description_text,
      original_filename,
      mime_type,
      video_blob,
      file_bytes,
      processing_status,
      processing_stage,
      progress_percent,
      processing_message,
      processing_started_at,
      last_progress_at,
      metadata_status,
      rights_confirmed_yn,
      handling_acknowledged_yn
    ) values (
      l_submission_ref,
      'UPLOAD',
      trim(p_title),
      trim(p_description),
      coalesce(trim(p_title), l_filename),
      trim(p_description),
      l_filename,
      l_mime_type,
      l_blob,
      l_bytes,
      'ANALYSING',
      'QUEUED_FOR_ANALYSIS',
      20,
      'Video bytes are stored in AIDEMODB and queued for the asynchronous analysis worker. No model call has started.',
      systimestamp,
      systimestamp,
      'NOT_REQUESTED',
      'Y',
      'Y'
    ) returning submission_id into l_submission_id;

    ensure_review_scenario(l_submission_id);

    return l_submission_id;
  end stage_upload;

  procedure delete_submission(
    p_submission_id in number
  ) is
    l_actor varchar2(255) := actor_name;
    l_analysis_run_id number;
  begin
    select analysis_run_id
      into l_analysis_run_id
      from afma_cm_video_submissions
     where submission_id = p_submission_id
       and processing_status <> 'DELETED';

    update afma_cm_video_submissions
       set video_blob = null,
           source_url = null,
           file_bytes = null,
           processing_status = 'DELETED',
           processing_stage = 'CANCELLED',
           processing_message = 'Payload deleted by an authorised reviewer.',
           last_progress_at = systimestamp,
           deleted_at = systimestamp,
           deleted_by = l_actor
     where submission_id = p_submission_id
       and processing_status <> 'DELETED';

    if sql%rowcount = 0 then
      raise_application_error(-20070, 'The test-video submission was not found or is already deleted.');
    end if;

    if l_analysis_run_id is not null then
      update afma_cm_trips
         set status = 'ARCHIVED'
       where trip_id = (
         select trip_id from afma_cm_analysis_runs where analysis_run_id = l_analysis_run_id
       );
    end if;
  exception
    when no_data_found then
      raise_application_error(-20070, 'The test-video submission was not found or is already deleted.');
  end delete_submission;

  procedure approve_submission(
    p_submission_id   in number,
    p_acknowledged_yn in varchar2
  ) is
    l_eligible_count number;
  begin
    if upper(coalesce(p_acknowledged_yn, 'N')) <> 'Y' then
      raise_application_error(-20073, 'Confirm that you reviewed the submitted source and intake disclosures.');
    end if;

    update afma_cm_video_submissions
       set processing_status = case when input_method = 'URL' then 'AWAITING_IMPORT' else 'ANALYSING' end,
           processing_stage = case when input_method = 'URL' then 'AWAITING_PROJECT_IMPORT' else 'QUEUED_FOR_ANALYSIS' end,
           progress_percent = case when input_method = 'URL' then 5 else 20 end,
           processing_message = case
             when input_method = 'URL' then 'The source URL is registered for this project to import when requested. No video bytes are stored and no model call has started.'
             else 'Video bytes are stored in AIDEMODB and queued for the asynchronous analysis worker. No model call has started.'
           end,
           processing_started_at = coalesce(processing_started_at, systimestamp),
           last_progress_at = systimestamp,
           metadata_status = case when metadata_status = 'AWAITING_PROMPT_APPROVAL' then 'NOT_REQUESTED' else metadata_status end
     where submission_id = p_submission_id
       and processing_status in ('AWAITING_PROMPT_APPROVAL','READY_FOR_ANALYSIS')
       and rights_confirmed_yn = 'Y'
       and handling_acknowledged_yn = 'Y';

    if sql%rowcount = 0 then
      select count(*)
        into l_eligible_count
        from afma_cm_video_submissions
       where submission_id = p_submission_id
         and processing_status in ('AWAITING_IMPORT','ANALYSING','ANALYSIS_COMPLETE')
         and rights_confirmed_yn = 'Y'
         and handling_acknowledged_yn = 'Y';
      if l_eligible_count = 0 then
        raise_application_error(-20074, 'The submission was not found, has been deleted, or lacks the required intake acknowledgements.');
      end if;
    end if;

    ensure_review_scenario(p_submission_id);
  end approve_submission;

  procedure save_reviewed_metadata(
    p_submission_id in number,
    p_title         in varchar2,
    p_description   in varchar2,
    p_region        in varchar2,
    p_fishery       in varchar2,
    p_gear_method   in varchar2
  ) is
    l_actor varchar2(255) := actor_name;
  begin
    if trim(p_title) is null then
      raise_application_error(-20071, 'Enter a reviewer-approved video title.');
    end if;

    update afma_cm_video_submissions
       set display_title = trim(p_title),
           description_text = trim(p_description),
           region_text = trim(p_region),
           fishery_text = trim(p_fishery),
           gear_method_text = trim(p_gear_method),
           metadata_status = case
             when ai_display_title is null then 'CORRECTED'
             when trim(p_title) = trim(ai_display_title)
              and coalesce(trim(p_description), '~') = coalesce(trim(ai_description_text), '~')
              and coalesce(trim(p_region), '~') = coalesce(trim(ai_region_text), '~')
              and coalesce(trim(p_fishery), '~') = coalesce(trim(ai_fishery_text), '~')
              and coalesce(trim(p_gear_method), '~') = coalesce(trim(ai_gear_method_text), '~') then 'CONFIRMED'
             else 'CORRECTED'
           end,
           metadata_reviewed_at = systimestamp,
           metadata_reviewed_by = l_actor
     where submission_id = p_submission_id
       and processing_status <> 'DELETED';

    if sql%rowcount = 0 then
      raise_application_error(-20072, 'The test-video submission was not found or its payload has been deleted.');
    end if;

    update afma_cm_trips
       set fishery_name = coalesce(trim(p_fishery), trim(p_title)),
           region_name = coalesce(trim(p_region), 'Location not yet determined'),
           gear_method = coalesce(trim(p_gear_method), 'Method not yet determined'),
           notes = substr(coalesce(trim(p_description) || ' ', '') ||
             'Source approved for controlled internal testing. Analysis has not started.', 1, 2000)
     where trip_id = (
       select ar.trip_id
         from afma_cm_video_submissions vs
         join afma_cm_analysis_runs ar on ar.analysis_run_id = vs.analysis_run_id
        where vs.submission_id = p_submission_id
     );

    update afma_cm_media_assets
       set title = trim(p_title),
           australian_region = trim(p_region)
     where media_asset_id = (
       select ar.media_asset_id
         from afma_cm_video_submissions vs
         join afma_cm_analysis_runs ar on ar.analysis_run_id = vs.analysis_run_id
        where vs.submission_id = p_submission_id
     );
  end save_reviewed_metadata;
end afma_cm_video_intake_api;
/

-- Earlier demo builds staged submissions behind a second approval step. The
-- internal demo now relies on the persistent disclosure and a processing
-- clearance queue. Existing sources enter that queue without starting AI
-- processing; only completed sources become selectable review scenarios.
begin
  update afma_cm_video_submissions
     set processing_status = 'AWAITING_IMPORT',
         processing_stage = 'AWAITING_PROJECT_IMPORT',
         progress_percent = 5,
         processing_message = 'The source URL is registered for this project to import when requested. No video bytes are stored and no model call has started.',
         processing_started_at = coalesce(processing_started_at, systimestamp),
         last_progress_at = systimestamp,
         metadata_status = case when metadata_status = 'AWAITING_PROMPT_APPROVAL' then 'NOT_REQUESTED' else metadata_status end
   where input_method = 'URL'
     and processing_status in ('AWAITING_PROMPT_APPROVAL','READY_FOR_ANALYSIS','ANALYSING')
     and rights_confirmed_yn = 'Y'
     and handling_acknowledged_yn = 'Y';

  update afma_cm_video_submissions
     set processing_status = 'ANALYSING',
         processing_stage = 'QUEUED_FOR_ANALYSIS',
         progress_percent = 20,
         processing_message = 'Video bytes are stored in AIDEMODB and queued for the asynchronous analysis worker. No model call has started.',
         processing_started_at = coalesce(processing_started_at, systimestamp),
         last_progress_at = systimestamp,
         metadata_status = case when metadata_status = 'AWAITING_PROMPT_APPROVAL' then 'NOT_REQUESTED' else metadata_status end
   where input_method = 'UPLOAD'
     and processing_status in ('AWAITING_PROMPT_APPROVAL','READY_FOR_ANALYSIS')
     and rights_confirmed_yn = 'Y'
     and handling_acknowledged_yn = 'Y';

  for r in (
    select submission_id
      from afma_cm_video_submissions
     where processing_status in ('AWAITING_IMPORT','ANALYSING')
       and analysis_run_id is null
  ) loop
    afma_cm_video_intake_api.approve_submission(r.submission_id, 'Y');
  end loop;
end;
/

comment on table afma_cm_video_submissions is 'Authorised AFMA internal test-video intake and processing-clearance state. Upload BLOBs are stored in AIDEMODB; video-page URLs store metadata only and remain at media acquisition until authorised bytes are supplied.';
/

prompt AFMA 115 complete
