set define off

-- Execution authority: AFMA parsing schema owner through the verified AFMA APEX SQL Commands session.
-- Target: AIDEMODB workspace/schema AFMA; governed Catch Monitor prompt approval and metadata proposal generation.
prompt AFMA 116 - Add Catch Monitor prompt governance

declare
  l_count number;
begin
  select count(*) into l_count from user_tables where table_name = 'AFMA_CM_PROMPT_CONTRACTS';
  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_prompt_contracts (
        prompt_contract_id    number generated by default on null as identity,
        prompt_key            varchar2(100 char) not null,
        prompt_version        varchar2(100 char) not null,
        purpose_text          varchar2(1000 char) not null,
        service_static_id     varchar2(255 char) not null,
        model_id              varchar2(255 char) not null,
        system_prompt         clob not null,
        task_prompt_template  clob not null,
        response_json_schema  clob not null,
        contract_status       varchar2(20 char) default 'DRAFT' not null,
        created_at            timestamp with local time zone default systimestamp not null,
        created_by            varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        approved_at           timestamp with local time zone,
        approved_by           varchar2(255 char),
        activated_at          timestamp with local time zone,
        activated_by          varchar2(255 char),
        retired_at            timestamp with local time zone,
        retired_by            varchar2(255 char),
        constraint afma_cm_prompt_contracts_pk primary key (prompt_contract_id),
        constraint afma_cm_prompt_contracts_uq unique (prompt_key, prompt_version),
        constraint afma_cm_prompt_contracts_ck_status check (contract_status in ('DRAFT','APPROVED','ACTIVE','RETIRED'))
      )
    ]';
  end if;
end;
/

merge into afma_cm_prompt_contracts d
using (
  select
    'catch-monitor-metadata' prompt_key,
    'catch-monitor-metadata-v1' prompt_version,
    'Propose editable catalogue metadata from the submitted video and audio; never publish it as fact without AFMA reviewer confirmation.' purpose_text,
    'google_gemini_2_5_pro' service_static_id,
    'google.gemini-2.5-pro' model_id,
    to_clob(q'~You are an evidence-first fisheries video cataloguer. Describe only what is supported by the attached video and its audible speech. Separate visible or audible evidence from inference. Use an empty string for anything not supported. Never invent a location, fishery, fishing method, vessel, person, species, count, measurement, catch disposition, wildlife interaction, legal status, quota or compliance conclusion. Do not identify people. Your output is an editable proposal for an authorised AFMA reviewer, not a finding.~') system_prompt,
    to_clob(q'~Review the attached video from beginning to end and propose catalogue metadata derived from the video and audio itself. Return: (1) a short neutral title; (2) a factual description of what the footage visibly and audibly contains; (3) region or location only when directly shown, stated or unambiguously evidenced; (4) fishery or fishing activity only when supported; (5) fishing method or gear only when supported; (6) a concise reviewer summary; (7) overall metadata confidence from 0 to 1; (8) evidence_basis entries identifying whether each claim came from vision, on-screen text or speech; and (9) uncertainties. Do not treat the submitted filename, URL, working title or reviewer notes as evidence. Do not count catches or make species determinations in this metadata task; those belong to the separately governed catch-evidence analysis. Return only JSON matching the supplied schema.~') task_prompt_template,
    to_clob(q'~{
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "description": {"type": "string"},
    "region_text": {"type": "string"},
    "fishery_text": {"type": "string"},
    "gear_method_text": {"type": "string"},
    "reviewer_summary": {"type": "string"},
    "confidence": {"type": "number", "minimum": 0, "maximum": 1},
    "evidence_basis": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "field": {"type": "string", "enum": ["title", "description", "region_text", "fishery_text", "gear_method_text"]},
          "source": {"type": "string", "enum": ["VISION", "ON_SCREEN_TEXT", "SPEECH"]},
          "evidence": {"type": "string"}
        },
        "required": ["field", "source", "evidence"],
        "additionalProperties": false
      }
    },
    "uncertainties": {"type": "array", "items": {"type": "string"}}
  },
  "required": ["title", "description", "region_text", "fishery_text", "gear_method_text", "reviewer_summary", "confidence", "evidence_basis", "uncertainties"],
  "additionalProperties": false
}~') response_json_schema
  from dual
) s
on (d.prompt_key = s.prompt_key and d.prompt_version = s.prompt_version)
when not matched then insert (
  prompt_key, prompt_version, purpose_text, service_static_id, model_id,
  system_prompt, task_prompt_template, response_json_schema, contract_status
) values (
  s.prompt_key, s.prompt_version, s.purpose_text, s.service_static_id, s.model_id,
  s.system_prompt, s.task_prompt_template, s.response_json_schema, 'DRAFT'
);

create or replace package afma_cm_prompt_api authid definer as
  procedure approve_and_activate(
    p_prompt_contract_id in number,
    p_acknowledged_yn     in varchar2
  );

  procedure run_metadata(
    p_submission_id in number
  );
end afma_cm_prompt_api;
/

create or replace package body afma_cm_prompt_api as
  function actor_name return varchar2 is
  begin
    return coalesce(apex_application.g_user, sys_context('APEX$SESSION','APP_USER'), user);
  end actor_name;

  procedure approve_and_activate(
    p_prompt_contract_id in number,
    p_acknowledged_yn     in varchar2
  ) is
    l_actor      varchar2(255) := actor_name;
    l_prompt_key varchar2(100);
    l_status     varchar2(20);
  begin
    if upper(coalesce(p_acknowledged_yn, 'N')) <> 'Y' then
      raise_application_error(-20100, 'Confirm that you reviewed the exact system prompt, task prompt, JSON schema and activation effect.');
    end if;
    if upper(coalesce(l_actor, 'ANONYMOUS')) in ('ANONYMOUS','NOBODY','PUBLIC_USER') then
      raise_application_error(-20101, 'An authenticated authorised reviewer is required.');
    end if;

    select prompt_key, contract_status
      into l_prompt_key, l_status
      from afma_cm_prompt_contracts
     where prompt_contract_id = p_prompt_contract_id
       for update;

    if l_status = 'RETIRED' then
      raise_application_error(-20102, 'A retired prompt cannot be reactivated; create a new version.');
    end if;

    update afma_cm_prompt_contracts
       set contract_status = 'RETIRED',
           retired_at = systimestamp,
           retired_by = l_actor
     where prompt_key = l_prompt_key
       and contract_status = 'ACTIVE'
       and prompt_contract_id <> p_prompt_contract_id;

    update afma_cm_prompt_contracts
       set contract_status = 'ACTIVE',
           approved_at = coalesce(approved_at, systimestamp),
           approved_by = coalesce(approved_by, l_actor),
           activated_at = systimestamp,
           activated_by = l_actor
     where prompt_contract_id = p_prompt_contract_id;
  exception
    when no_data_found then
      raise_application_error(-20103, 'The prompt contract was not found.');
  end approve_and_activate;

  procedure run_metadata(
    p_submission_id in number
  ) is
    l_prompt_id      number;
    l_prompt_version varchar2(100);
    l_service_id     varchar2(255);
    l_model_id       varchar2(255);
    l_system_prompt  clob;
    l_task_prompt    clob;
    l_schema         clob;
    l_input_method   varchar2(10);
    l_video           blob;
    l_mime_type       varchar2(200);
    l_filename        varchar2(500);
    l_response        clob;
    l_root            json_object_t;
    l_confidence      number;
    l_attachments     apex_ai.t_attachments := apex_ai.t_attachments();
  begin
    select prompt_contract_id, prompt_version, service_static_id, model_id,
           system_prompt, task_prompt_template, response_json_schema
      into l_prompt_id, l_prompt_version, l_service_id, l_model_id,
           l_system_prompt, l_task_prompt, l_schema
      from afma_cm_prompt_contracts
     where prompt_key = 'catch-monitor-metadata'
       and contract_status = 'ACTIVE';

    select input_method, video_blob, mime_type, original_filename
      into l_input_method, l_video, l_mime_type, l_filename
     from afma_cm_video_submissions
     where submission_id = p_submission_id
       and processing_status = 'READY_FOR_ANALYSIS'
       for update;

    if l_input_method <> 'UPLOAD' or l_video is null then
      raise_application_error(-20104, 'This APEX path can analyse an uploaded video BLOB. A registered video-page URL is metadata-only; upload the file or use a future governed URI-ingestion path.');
    end if;

    update afma_cm_video_submissions
       set metadata_status = 'ANALYSING',
           metadata_model_id = l_model_id,
           metadata_prompt_version = l_prompt_version
     where submission_id = p_submission_id;

    l_attachments.extend;
    l_attachments(1) := apex_ai.t_attachment(
      mime_type    => l_mime_type,
      content_blob => l_video,
      file_name    => substr(l_filename, 1, 255),
      detail_level => apex_ai.c_detail_level_high
    );

    l_response := apex_ai.generate(
      p_prompt               => l_task_prompt,
      p_system_prompt        => l_system_prompt,
      p_service_static_id    => l_service_id,
      p_temperature          => 0,
      p_attachments          => l_attachments,
      p_response_json_schema => l_schema
    );

    l_root := json_object_t.parse(l_response);
    l_confidence := l_root.get_number('confidence');
    if l_confidence < 0 or l_confidence > 1 then
      raise_application_error(-20105, 'Model metadata confidence was outside 0..1.');
    end if;

    update afma_cm_video_submissions
       set ai_display_title = substr(l_root.get_string('title'), 1, 500),
           ai_description_text = substr(l_root.get_string('description'), 1, 2000),
           ai_region_text = substr(l_root.get_string('region_text'), 1, 500),
           ai_fishery_text = substr(l_root.get_string('fishery_text'), 1, 500),
           ai_gear_method_text = substr(l_root.get_string('gear_method_text'), 1, 500),
           ai_video_summary = substr(l_root.get_string('reviewer_summary'), 1, 4000),
           ai_metadata_confidence = l_confidence,
           metadata_response_json = l_response,
           metadata_status = 'NEEDS_REVIEW',
           metadata_model_id = l_model_id,
           metadata_prompt_version = l_prompt_version,
           metadata_generated_at = systimestamp
     where submission_id = p_submission_id;
  exception
    when no_data_found then
      raise_application_error(-20106, 'No active metadata prompt or eligible submission was found.');
    when others then
      if sqlcode not in (-20104, -20106) then
        update afma_cm_video_submissions
           set metadata_status = 'FAILED'
         where submission_id = p_submission_id
           and processing_status <> 'DELETED';
      end if;
      raise;
  end run_metadata;
end afma_cm_prompt_api;
/

comment on table afma_cm_prompt_contracts is 'Immutable Catch Monitor prompt contracts with named human approval and activation provenance.';
/

prompt AFMA 116 complete
