set define off

-- Execution authority: AFMA parsing schema owner through the verified AFMA APEX SQL Commands session.
-- Target: AIDEMODB workspace/schema AFMA; controlled binary media storage for application 101.
prompt AFMA 117 - Add Catch Monitor media objects

declare
  l_count number;
begin
  select count(*)
    into l_count
    from user_tables
   where table_name = 'AFMA_CM_MEDIA_OBJECTS';

  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_media_objects (
        media_object_id       number generated by default on null as identity,
        submission_id         number not null,
        media_asset_id        number not null,
        object_key            varchar2(100 char) not null,
        object_role           varchar2(30 char) not null,
        original_filename     varchar2(500 char) not null,
        mime_type             varchar2(200 char) not null,
        file_bytes            number not null,
        sha256                varchar2(64 char) not null,
        duration_seconds      number,
        source_start_second   number,
        source_end_second     number,
        content_blob          blob not null,
        source_url_snapshot   varchar2(2000 char),
        source_video_id       varchar2(200 char),
        acquisition_method    varchar2(40 char) not null,
        acquisition_note      varchar2(2000 char),
        audio_present_yn      varchar2(7 char) default 'N' not null,
        storage_region        varchar2(40 char) default 'ap-sydney-1' not null,
        retention_review_at   date not null,
        created_at            timestamp with local time zone default systimestamp not null,
        created_by            varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint afma_cm_media_objects_pk primary key (media_object_id),
        constraint afma_cm_media_objects_uq unique (submission_id, object_key),
        constraint afma_cm_media_objects_fk_submission foreign key (submission_id) references afma_cm_video_submissions (submission_id),
        constraint afma_cm_media_objects_fk_asset foreign key (media_asset_id) references afma_cm_media_assets (media_asset_id),
        constraint afma_cm_media_objects_ck_role check (object_role in ('SOURCE_IMPORT','ANALYSIS_CLIP','EVIDENCE_FRAME')),
        constraint afma_cm_media_objects_ck_method check (acquisition_method in ('NATIVE_UPLOAD','CONTROLLED_PROJECT_IMPORT','OBJECT_STORAGE_COPY')),
        constraint afma_cm_media_objects_ck_audio check (audio_present_yn in ('Y','N','UNKNOWN')),
        constraint afma_cm_media_objects_ck_range check (source_start_second is null or source_end_second is null or source_end_second >= source_start_second)
      )
    ]';
  end if;
end;
/

declare
  l_length number;
begin
  select char_length
    into l_length
    from user_tab_columns
   where table_name = 'AFMA_CM_MEDIA_OBJECTS'
     and column_name = 'AUDIO_PRESENT_YN';
  if l_length < 7 then
    execute immediate 'alter table afma_cm_media_objects modify audio_present_yn varchar2(7 char)';
  end if;
end;
/

declare
  l_count number;
begin
  select count(*)
    into l_count
    from user_tables
   where table_name = 'AFMA_CM_MEDIA_IMPORTS';

  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_media_imports (
        import_id             number generated by default on null as identity,
        import_ref            varchar2(40 char) not null,
        target_submission_id  number not null,
        original_filename     varchar2(500 char) not null,
        mime_type             varchar2(200 char) not null,
        expected_file_bytes   number not null,
        expected_sha256       varchar2(64 char) not null,
        duration_seconds      number not null,
        source_video_id       varchar2(200 char),
        acquisition_note      varchar2(2000 char),
        content_blob          blob not null,
        received_bytes        number default 0 not null,
        next_chunk_no         number default 1 not null,
        created_at            timestamp with local time zone default systimestamp not null,
        created_by            varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint afma_cm_media_imports_pk primary key (import_id),
        constraint afma_cm_media_imports_uq unique (import_ref),
        constraint afma_cm_media_imports_fk_submission foreign key (target_submission_id) references afma_cm_video_submissions (submission_id),
        constraint afma_cm_media_imports_ck_bytes check (expected_file_bytes > 0 and received_bytes >= 0 and received_bytes <= expected_file_bytes),
        constraint afma_cm_media_imports_ck_chunk check (next_chunk_no > 0)
      )
    ]';
  end if;
end;
/

create or replace trigger afma_cm_media_objects_biu
  before insert or update on afma_cm_media_objects
  for each row
begin
  if inserting then
    :new.created_at := coalesce(:new.created_at, systimestamp);
    :new.created_by := coalesce(:new.created_by, coalesce(sys_context('APEX$SESSION','APP_USER'), user));
  end if;
end;
/

create or replace trigger afma_cm_submission_payload_del
  after update of processing_status on afma_cm_video_submissions
  for each row
begin
  if :new.processing_status = 'DELETED'
     and coalesce(:old.processing_status, '~') <> 'DELETED' then
    delete from afma_cm_media_objects
     where submission_id = :new.submission_id;
  end if;
end;
/

create or replace package afma_cm_media_import_api as
  function create_native_upload_target(
    p_title                    in varchar2,
    p_description              in varchar2,
    p_original_filename        in varchar2,
    p_mime_type                in varchar2,
    p_expected_file_bytes      in number,
    p_rights_confirmed_yn      in varchar2,
    p_handling_acknowledged_yn in varchar2
  ) return varchar2;

  function begin_chunked_import(
    p_target_submission_ref in varchar2,
    p_original_filename     in varchar2,
    p_mime_type             in varchar2,
    p_expected_file_bytes   in number,
    p_expected_sha256       in varchar2,
    p_duration_seconds      in number,
    p_source_video_id       in varchar2,
    p_acquisition_note      in varchar2
  ) return varchar2;

  procedure append_chunk(
    p_import_ref   in varchar2,
    p_chunk_no     in number,
    p_base64_chunk in clob
  );

  procedure complete_chunked_import(
    p_import_ref in varchar2
  );

  procedure abort_chunked_import(
    p_import_ref in varchar2
  );

  procedure adopt_uploaded_media(
    p_target_submission_ref in varchar2,
    p_upload_submission_ref in varchar2,
    p_source_video_id       in varchar2,
    p_duration_seconds      in number,
    p_expected_file_bytes   in number,
    p_expected_sha256       in varchar2,
    p_acquisition_note      in varchar2
  );
end afma_cm_media_import_api;
/

create or replace package body afma_cm_media_import_api as
  function actor_name return varchar2 is
  begin
    return coalesce(sys_context('APEX$SESSION','APP_USER'), user);
  end actor_name;

  function new_ref(p_prefix in varchar2) return varchar2 is
  begin
    return p_prefix || lower(substr(rawtohex(sys_guid()), 1, 12));
  end new_ref;

  function create_native_upload_target(
    p_title                    in varchar2,
    p_description              in varchar2,
    p_original_filename        in varchar2,
    p_mime_type                in varchar2,
    p_expected_file_bytes      in number,
    p_rights_confirmed_yn      in varchar2,
    p_handling_acknowledged_yn in varchar2
  ) return varchar2 is
    l_submission_id  number;
    l_submission_ref varchar2(40) := new_ref('CM-SUB-');
    l_filename       varchar2(500) := substr(trim(p_original_filename), 1, 500);
    l_mime_type      varchar2(200) := coalesce(substr(trim(p_mime_type), 1, 200), 'video/mp4');
    l_extension      varchar2(20);
  begin
    if upper(coalesce(p_rights_confirmed_yn, 'N')) <> 'Y'
       or upper(coalesce(p_handling_acknowledged_yn, 'N')) <> 'Y' then
      raise_application_error(-20215, 'Confirm both authority and data-handling acknowledgements.');
    end if;
    if p_expected_file_bytes is null or p_expected_file_bytes <= 0
       or p_expected_file_bytes > afma_cm_video_intake_api.c_max_upload_bytes then
      raise_application_error(-20216, 'The video must be between one byte and the configured 35 MiB limit.');
    end if;
    if l_filename is null then
      raise_application_error(-20217, 'Choose a named video file.');
    end if;
    l_extension := lower(regexp_substr(l_filename, '\.[^.]+$'));
    if lower(l_mime_type) not like 'video/%'
       and coalesce(l_extension, '~') not in ('.mp4','.mpeg','.mpg','.mov','.avi','.webm','.wmv','.3gp','.3gpp','.flv') then
      raise_application_error(-20218, 'Unsupported video type. Use MP4, MPEG, MOV, AVI, WebM, WMV, 3GPP or FLV.');
    end if;

    insert into afma_cm_video_submissions (
      submission_ref, input_method, submitted_title, submitted_description,
      display_title, description_text, original_filename, mime_type,
      video_blob, file_bytes, processing_status, processing_stage,
      progress_percent, processing_message, processing_started_at,
      last_progress_at, metadata_status, rights_confirmed_yn,
      handling_acknowledged_yn
    ) values (
      l_submission_ref, 'UPLOAD', trim(p_title), trim(p_description),
      coalesce(trim(p_title), l_filename), trim(p_description), l_filename, l_mime_type,
      empty_blob(), p_expected_file_bytes, 'ANALYSING', 'QUEUED_FOR_ANALYSIS',
      5, 'Native upload target created; resumable video transfer has not started.', systimestamp,
      systimestamp, 'NOT_REQUESTED', 'Y', 'Y'
    ) returning submission_id into l_submission_id;

    afma_cm_video_intake_api.approve_submission(l_submission_id, 'Y');

    update afma_cm_video_submissions
       set processing_status = 'AWAITING_IMPORT',
           processing_stage = 'IMPORTING_VIDEO_BYTES',
           progress_percent = 5,
           processing_message = 'Native upload target created. Video bytes will be transferred in resumable chunks; no model call has started.',
           last_progress_at = systimestamp
     where submission_id = l_submission_id;

    return l_submission_ref;
  end create_native_upload_target;

  function begin_chunked_import(
    p_target_submission_ref in varchar2,
    p_original_filename     in varchar2,
    p_mime_type             in varchar2,
    p_expected_file_bytes   in number,
    p_expected_sha256       in varchar2,
    p_duration_seconds      in number,
    p_source_video_id       in varchar2,
    p_acquisition_note      in varchar2
  ) return varchar2 is
    l_target_id number;
    l_import_ref varchar2(40) := new_ref('CM-IMP-');
    l_sha256 varchar2(64) := lower(trim(p_expected_sha256));
  begin
    if p_expected_file_bytes is null or p_expected_file_bytes <= 0
       or p_expected_file_bytes > afma_cm_video_intake_api.c_max_upload_bytes then
      raise_application_error(-20206, 'The controlled import must be between one byte and the configured 35 MiB limit.');
    end if;
    if not regexp_like(l_sha256, '^[0-9a-f]{64}$') then
      raise_application_error(-20207, 'A valid lowercase SHA-256 value is required.');
    end if;
    if p_duration_seconds is null or p_duration_seconds <= 0 then
      raise_application_error(-20208, 'A positive source duration is required.');
    end if;

    select submission_id
      into l_target_id
      from afma_cm_video_submissions
     where submission_ref = trim(p_target_submission_ref)
       and input_method in ('URL','UPLOAD')
       and processing_status = 'AWAITING_IMPORT'
       and rights_confirmed_yn = 'Y'
       and handling_acknowledged_yn = 'Y';

    insert into afma_cm_media_imports (
      import_ref,
      target_submission_id,
      original_filename,
      mime_type,
      expected_file_bytes,
      expected_sha256,
      duration_seconds,
      source_video_id,
      acquisition_note,
      content_blob
    ) values (
      l_import_ref,
      l_target_id,
      substr(trim(p_original_filename), 1, 500),
      coalesce(substr(trim(p_mime_type), 1, 200), 'video/mp4'),
      p_expected_file_bytes,
      l_sha256,
      p_duration_seconds,
      substr(trim(p_source_video_id), 1, 200),
      substr(trim(p_acquisition_note), 1, 2000),
      empty_blob()
    );

    update afma_cm_video_submissions
       set processing_stage = 'IMPORTING_VIDEO_BYTES',
           progress_percent = 10,
           processing_message = 'Controlled project import has started. Video-only bytes are being transferred into AIDEMODB; no model call has started.',
           worker_job_ref = l_import_ref,
           last_progress_at = systimestamp
     where submission_id = l_target_id;

    return l_import_ref;
  exception
    when no_data_found then
      raise_application_error(-20209, 'The target submission was not found in an eligible import state.');
  end begin_chunked_import;

  procedure append_chunk(
    p_import_ref   in varchar2,
    p_chunk_no     in number,
    p_base64_chunk in clob
  ) is
    l_target_blob blob;
    l_chunk_blob blob;
    l_expected_bytes number;
    l_received_bytes number;
    l_next_chunk_no number;
    l_chunk_bytes number;
    l_target_submission_id number;
    l_progress number;
  begin
    if p_base64_chunk is null then
      raise_application_error(-20210, 'An import chunk cannot be empty.');
    end if;

    select content_blob,
           expected_file_bytes,
           received_bytes,
           next_chunk_no,
           target_submission_id
      into l_target_blob,
           l_expected_bytes,
           l_received_bytes,
           l_next_chunk_no,
           l_target_submission_id
      from afma_cm_media_imports
     where import_ref = trim(p_import_ref)
     for update;

    if p_chunk_no <> l_next_chunk_no then
      raise_application_error(-20211, 'Import chunks must be appended once and in sequence.');
    end if;

    l_chunk_blob := apex_web_service.clobbase642blob(p_base64_chunk);
    l_chunk_bytes := dbms_lob.getlength(l_chunk_blob);
    if l_received_bytes + l_chunk_bytes > l_expected_bytes then
      raise_application_error(-20212, 'The received media exceeds the controlled import manifest byte length.');
    end if;

    dbms_lob.append(l_target_blob, l_chunk_blob);
    l_received_bytes := l_received_bytes + l_chunk_bytes;
    l_progress := least(28, 10 + floor((l_received_bytes / l_expected_bytes) * 18));

    update afma_cm_media_imports
       set received_bytes = l_received_bytes,
           next_chunk_no = l_next_chunk_no + 1
     where import_ref = trim(p_import_ref);

    update afma_cm_video_submissions
       set progress_percent = l_progress,
           processing_message = 'Controlled project import is transferring video-only bytes into AIDEMODB (' ||
             to_char(l_received_bytes) || ' of ' || to_char(l_expected_bytes) || ' bytes). No model call has started.',
           last_progress_at = systimestamp
     where submission_id = l_target_submission_id;

    if dbms_lob.istemporary(l_chunk_blob) = 1 then
      dbms_lob.freetemporary(l_chunk_blob);
    end if;
  end append_chunk;

  procedure complete_chunked_import(
    p_import_ref in varchar2
  ) is
    l_import afma_cm_media_imports%rowtype;
    l_target_ref varchar2(40);
    l_target_title varchar2(500);
    l_upload_ref varchar2(40) := new_ref('CM-SUB-');
    l_upload_id number;
  begin
    select *
      into l_import
      from afma_cm_media_imports
     where import_ref = trim(p_import_ref)
     for update;

    if l_import.received_bytes <> l_import.expected_file_bytes
       or dbms_lob.getlength(l_import.content_blob) <> l_import.expected_file_bytes then
      raise_application_error(-20213, 'The controlled import is incomplete; stored byte length does not match the manifest.');
    end if;

    select submission_ref, display_title
      into l_target_ref, l_target_title
      from afma_cm_video_submissions
     where submission_id = l_import.target_submission_id
       and processing_status = 'AWAITING_IMPORT'
     for update;

    insert into afma_cm_video_submissions (
      submission_ref,
      input_method,
      submitted_title,
      submitted_description,
      display_title,
      description_text,
      original_filename,
      mime_type,
      video_blob,
      file_bytes,
      processing_status,
      processing_stage,
      progress_percent,
      processing_message,
      processing_started_at,
      last_progress_at,
      metadata_status,
      rights_confirmed_yn,
      handling_acknowledged_yn
    ) values (
      l_upload_ref,
      'UPLOAD',
      'IMPORT TRANSFER — ' || l_target_title,
      l_import.acquisition_note,
      'IMPORT TRANSFER — ' || l_target_title,
      l_import.acquisition_note,
      l_import.original_filename,
      l_import.mime_type,
      l_import.content_blob,
      l_import.expected_file_bytes,
      'ANALYSING',
      'QUEUED_FOR_ANALYSIS',
      20,
      'Temporary controlled project transfer row. No model call has started.',
      systimestamp,
      systimestamp,
      'NOT_REQUESTED',
      'Y',
      'Y'
    ) returning submission_id into l_upload_id;

    afma_cm_video_intake_api.approve_submission(l_upload_id, 'Y');
    adopt_uploaded_media(
      p_target_submission_ref => l_target_ref,
      p_upload_submission_ref => l_upload_ref,
      p_source_video_id       => l_import.source_video_id,
      p_duration_seconds      => l_import.duration_seconds,
      p_expected_file_bytes   => l_import.expected_file_bytes,
      p_expected_sha256       => l_import.expected_sha256,
      p_acquisition_note      => l_import.acquisition_note
    );

    delete from afma_cm_media_imports
     where import_id = l_import.import_id;
  exception
    when no_data_found then
      raise_application_error(-20214, 'The controlled media import was not found or its target is no longer eligible.');
  end complete_chunked_import;

  procedure abort_chunked_import(
    p_import_ref in varchar2
  ) is
    l_target_submission_id number;
    l_input_method         varchar2(10);
  begin
    select mi.target_submission_id,
           vs.input_method
      into l_target_submission_id,
           l_input_method
      from afma_cm_media_imports mi
      join afma_cm_video_submissions vs
        on vs.submission_id = mi.target_submission_id
     where import_ref = trim(p_import_ref)
     for update of mi.content_blob;

    delete from afma_cm_media_imports
     where import_ref = trim(p_import_ref);

    if l_input_method = 'UPLOAD' then
      afma_cm_video_intake_api.delete_submission(l_target_submission_id);
    else
      update afma_cm_video_submissions
         set processing_stage = 'AWAITING_PROJECT_IMPORT',
             progress_percent = 5,
             processing_message = 'The source URL is registered for this project to import when requested. No video bytes are stored and no model call has started.',
             worker_job_ref = null,
             last_progress_at = systimestamp
       where submission_id = l_target_submission_id
         and processing_status = 'AWAITING_IMPORT';
    end if;
  exception
    when no_data_found then
      null;
  end abort_chunked_import;

  procedure adopt_uploaded_media(
    p_target_submission_ref in varchar2,
    p_upload_submission_ref in varchar2,
    p_source_video_id       in varchar2,
    p_duration_seconds      in number,
    p_expected_file_bytes   in number,
    p_expected_sha256       in varchar2,
    p_acquisition_note      in varchar2
  ) is
    l_target_id            number;
    l_target_url           varchar2(2000);
    l_target_retention     date;
    l_target_run_id        number;
    l_target_input_method  varchar2(10);
    l_media_asset_id       number;
    l_upload_id            number;
    l_upload_run_id        number;
    l_upload_filename      varchar2(500);
    l_upload_mime_type     varchar2(200);
    l_upload_blob          blob;
    l_upload_bytes         number;
    l_media_object_id      number;
    l_existing_sha256      varchar2(64);
    l_sha256               varchar2(64) := lower(trim(p_expected_sha256));
    l_actor                varchar2(255) := actor_name;
  begin
    if not regexp_like(l_sha256, '^[0-9a-f]{64}$') then
      raise_application_error(-20200, 'A valid lowercase SHA-256 value is required for a controlled project import.');
    end if;

    select vs.submission_id,
           vs.source_url,
           vs.retention_review_at,
           vs.analysis_run_id,
           vs.input_method,
           ar.media_asset_id
      into l_target_id,
           l_target_url,
           l_target_retention,
           l_target_run_id,
           l_target_input_method,
           l_media_asset_id
      from afma_cm_video_submissions vs
      join afma_cm_analysis_runs ar
        on ar.analysis_run_id = vs.analysis_run_id
     where vs.submission_ref = trim(p_target_submission_ref)
       and vs.input_method in ('URL','UPLOAD')
       and vs.processing_status in ('AWAITING_IMPORT','READY_FOR_ANALYSIS')
       and vs.rights_confirmed_yn = 'Y'
       and vs.handling_acknowledged_yn = 'Y'
     for update of vs.processing_status;

    begin
      select media_object_id, sha256
        into l_media_object_id, l_existing_sha256
        from afma_cm_media_objects
       where submission_id = l_target_id
         and object_key = 'SOURCE';

      if l_existing_sha256 <> l_sha256 then
        raise_application_error(-20201, 'This source already has a different stored media object. Delete it through the governed payload workflow before replacing it.');
      end if;

      update afma_cm_video_submissions
         set processing_status = 'READY_FOR_ANALYSIS',
             processing_stage = 'AWAITING_ANALYSIS_PROMPT_REVIEW',
             progress_percent = 30,
             processing_message = case
               when l_target_input_method = 'UPLOAD' then 'Submitted source bytes are stored in AIDEMODB. Audio presence is not yet probed. Analysis awaits review of the general evidence prompt; no model call has started.'
               else 'Video-only source bytes are stored in AIDEMODB. Analysis awaits review of the general evidence prompt; no model call has started.'
             end,
             last_progress_at = systimestamp
       where submission_id = l_target_id;
      return;
    exception
      when no_data_found then
        null;
    end;

    select submission_id,
           analysis_run_id,
           original_filename,
           coalesce(mime_type, 'video/mp4'),
           video_blob,
           dbms_lob.getlength(video_blob)
      into l_upload_id,
           l_upload_run_id,
           l_upload_filename,
           l_upload_mime_type,
           l_upload_blob,
           l_upload_bytes
      from afma_cm_video_submissions
     where submission_ref = trim(p_upload_submission_ref)
       and input_method = 'UPLOAD'
       and processing_status in ('ANALYSING','READY_FOR_ANALYSIS')
       and video_blob is not null
     for update;

    if l_upload_bytes <> p_expected_file_bytes then
      raise_application_error(-20202, 'Uploaded byte length does not match the controlled import manifest.');
    end if;
    if l_upload_bytes > afma_cm_video_intake_api.c_max_upload_bytes then
      raise_application_error(-20203, 'Uploaded media exceeds the configured direct-analysis limit.');
    end if;
    if p_duration_seconds is null or p_duration_seconds <= 0 then
      raise_application_error(-20204, 'A positive source duration is required.');
    end if;

    insert into afma_cm_media_objects (
      submission_id,
      media_asset_id,
      object_key,
      object_role,
      original_filename,
      mime_type,
      file_bytes,
      sha256,
      duration_seconds,
      content_blob,
      source_url_snapshot,
      source_video_id,
      acquisition_method,
      acquisition_note,
      audio_present_yn,
      storage_region,
      retention_review_at
    ) values (
      l_target_id,
      l_media_asset_id,
      'SOURCE',
      'SOURCE_IMPORT',
      l_upload_filename,
      l_upload_mime_type,
      l_upload_bytes,
      l_sha256,
      p_duration_seconds,
      l_upload_blob,
      l_target_url,
      trim(p_source_video_id),
      case when l_target_input_method = 'UPLOAD' then 'NATIVE_UPLOAD' else 'CONTROLLED_PROJECT_IMPORT' end,
      substr(trim(p_acquisition_note), 1, 2000),
      case when l_target_input_method = 'UPLOAD' then 'UNKNOWN' else 'N' end,
      'ap-sydney-1',
      l_target_retention
    ) returning media_object_id into l_media_object_id;

    update afma_cm_media_assets
       set source_system = case when l_target_input_method = 'UPLOAD' then 'Native APEX upload' else 'Controlled project import' end,
           private_object_uri = 'urn:afma:catch-monitor-media-object:' || l_media_object_id,
           mime_type = l_upload_mime_type,
           duration_seconds = p_duration_seconds,
           file_bytes = l_upload_bytes,
           sha256 = l_sha256,
           restrictions = case
             when l_target_input_method = 'UPLOAD' then 'Controlled internal demo media. Original submitted container; audio presence is not yet probed. Preserve reviewer access controls.'
             else 'Controlled internal demo media. Video-only rendition; no audio track is stored. Preserve source attribution and reviewer access controls.'
           end,
           quality_rating = 'PENDING',
           expert_review_status = 'PENDING',
           coverage_status = 'MEDIA_GAP'
     where media_asset_id = l_media_asset_id;

    update afma_cm_analysis_runs
       set model_version = 'analysis-not-started',
           media_manifest = 'media-object-' || l_media_object_id,
           run_status = 'QUEUED',
           run_notes = case
             when l_target_input_method = 'UPLOAD' then 'Native source media uploaded into AIDEMODB. Audio presence is not yet probed. General evidence prompt review is required before Gemini Pro analysis; no model call has started.'
             else 'Video-only source media imported into AIDEMODB. General evidence prompt review is required before Gemini Pro analysis; no model call has started.'
           end
     where analysis_run_id = l_target_run_id;

    update afma_cm_video_submissions
       set original_filename = l_upload_filename,
           mime_type = l_upload_mime_type,
           file_bytes = l_upload_bytes,
           video_blob = case when l_target_input_method = 'UPLOAD' then l_upload_blob else video_blob end,
           processing_status = 'READY_FOR_ANALYSIS',
           processing_stage = 'AWAITING_ANALYSIS_PROMPT_REVIEW',
           progress_percent = 30,
           processing_message = case
             when l_target_input_method = 'UPLOAD' then 'Submitted source bytes are stored in AIDEMODB. Audio presence is not yet probed. Analysis awaits review of the general evidence prompt; no model call has started.'
             else 'Video-only source bytes are stored in AIDEMODB. Analysis awaits review of the general evidence prompt; no model call has started.'
           end,
           worker_job_ref = case
             when l_target_input_method = 'UPLOAD' then 'NATIVE-UPLOAD-' || l_media_object_id
             else 'CONTROLLED-IMPORT-' || trim(p_source_video_id)
           end,
           last_progress_at = systimestamp
     where submission_id = l_target_id;

    update afma_cm_analysis_runs
       set run_notes = 'Temporary native-upload transfer row adopted by submission ' || trim(p_target_submission_ref) || '; no model call was made.'
     where analysis_run_id = l_upload_run_id;

    update afma_cm_trips
       set status = 'ARCHIVED'
     where trip_id = (
       select trip_id
         from afma_cm_analysis_runs
        where analysis_run_id = l_upload_run_id
     );

    update afma_cm_video_submissions
       set video_blob = null,
           file_bytes = null,
           processing_status = 'DELETED',
           processing_stage = 'IMPORT_SOURCE_ADOPTED',
           progress_percent = 100,
           processing_message = 'Temporary upload adopted into ' || trim(p_target_submission_ref) || '; transfer payload cleared.',
           processing_completed_at = systimestamp,
           last_progress_at = systimestamp,
           deleted_at = systimestamp,
           deleted_by = l_actor
     where submission_id = l_upload_id;
  exception
    when no_data_found then
      raise_application_error(-20205, 'The target submission or temporary transfer upload was not found in an eligible state.');
  end adopt_uploaded_media;
end afma_cm_media_import_api;
/

comment on table afma_cm_media_objects is 'Controlled Catch Monitor binary media store. URL provenance remains on the submission/media asset; video-only source and clip BLOBs are retained in AIDEMODB for governed demo analysis.';
/

comment on column afma_cm_media_objects.audio_present_yn is 'Whether the stored object contains an audio track. Production AFMA electronic-monitoring media is expected to be N.';
/

prompt AFMA 117 complete
