set define off

-- Execution authority: AFMA parsing schema owner through the verified AFMA APEX SQL Commands session.
-- Target: AIDEMODB workspace/schema AFMA; governed full-video evidence analysis for application 101.
prompt AFMA 118 - Add Catch Monitor evidence analysis

declare
  l_count number;
begin
  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_SCIENTIFIC_NAME';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_scientific_name varchar2(300 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_SIZE_VALUE';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_size_value number';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_SIZE_UNIT';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_size_unit varchar2(10 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_SIZE_BASIS';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_size_basis varchar2(30 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_DISPOSITION';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_disposition varchar2(40 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_UNCERTAINTY';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_uncertainty varchar2(1000 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'POSSIBLE_DUPLICATE_OF_INDEX';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add possible_duplicate_of_index number';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_COUNT_BASIS';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_count_basis varchar2(30 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_COUNT_LOWER_BOUND';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_count_lower_bound number';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_COUNT_UPPER_BOUND';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_count_upper_bound number';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_COUNT_SCOPE';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_count_scope varchar2(30 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and column_name = 'AI_EVENT_GRANULARITY';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_observations add ai_event_granularity varchar2(30 char)';
  end if;

  select count(*) into l_count
    from user_constraints
   where table_name = 'AFMA_CM_OBSERVATIONS'
     and constraint_name = 'AFMA_CM_OBS_CK_EVIDENCE_ROLE';
  if l_count = 1 then
    execute immediate 'alter table afma_cm_observations drop constraint afma_cm_obs_ck_evidence_role';
  end if;
  execute immediate q'[alter table afma_cm_observations add constraint afma_cm_obs_ck_evidence_role check (evidence_role in ('PRIMARY','PREVIEW_OR_REPLAY','POSSIBLE_DUPLICATE','UNCERTAIN'))]';
end;
/

declare
  l_count number;
begin
  select count(*) into l_count
    from user_tables
   where table_name = 'AFMA_CM_EVIDENCE_RUNS';
  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_evidence_runs (
        evidence_run_id       number generated by default on null as identity,
        submission_id         number not null,
        analysis_run_id       number not null,
        media_object_id       number not null,
        prompt_contract_id    number not null,
        service_static_id     varchar2(255 char) not null,
        model_id              varchar2(255 char) not null,
        prompt_version        varchar2(100 char) not null,
        run_status            varchar2(30 char) default 'RUNNING' not null,
        validation_status     varchar2(30 char),
        validation_issues     varchar2(4000 char),
        response_json         clob,
        proposed_event_count  number,
        started_at            timestamp with local time zone default systimestamp not null,
        completed_at          timestamp with local time zone,
        created_by            varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint afma_cm_evidence_runs_pk primary key (evidence_run_id),
        constraint afma_cm_evidence_runs_fk_submission foreign key (submission_id) references afma_cm_video_submissions (submission_id),
        constraint afma_cm_evidence_runs_fk_analysis foreign key (analysis_run_id) references afma_cm_analysis_runs (analysis_run_id),
        constraint afma_cm_evidence_runs_fk_media foreign key (media_object_id) references afma_cm_media_objects (media_object_id),
        constraint afma_cm_evidence_runs_fk_prompt foreign key (prompt_contract_id) references afma_cm_prompt_contracts (prompt_contract_id),
        constraint afma_cm_evidence_runs_ck_status check (run_status in ('RUNNING','COMPLETE','FAILED')),
        constraint afma_cm_evidence_runs_ck_validation check (validation_status is null or validation_status in ('PASS','REJECTED'))
      )
    ]';
  end if;
end;
/

merge into afma_cm_prompt_contracts d
using (
  select
    'catch-monitor-evidence' prompt_key,
    'catch-monitor-evidence-v3' prompt_version,
    'Propose full-video catch and wildlife evidence events plus editable source metadata from visual evidence only; publish only deterministically validated candidates for AFMA review.' purpose_text,
    'google_gemini_2_5_pro' service_static_id,
    'google.gemini-2.5-pro' model_id,
    to_clob(q'~You are an evidence-first fisheries video analyst supporting an authorised AFMA reviewer. Use only visible frames and visible on-screen text in the attached video. Never use, infer, quote or rely on audio, speech, captions derived from speech, filename, URL, working title or submitter notes. Preserve every visibly depicted catch or wildlife candidate, including edited previews, replays and possible duplicates, and label those relationships instead of silently discarding visible evidence. A fight, landing, close-up and later display may be one evidence sequence; use the same evidence_group_ref where supported. Never make a compliance finding or infer quota, legal size, weight, retained/released status, injury, survival or post-release condition. Estimate length only when a visible scale or a defensible known-size reference is present in the same evidence. Species identities are candidates for deterministic CAAB matching and officer review. Do not invent a CAAB code. Your output is an advisory proposal, never a final finding.~') system_prompt,
    to_clob(q'~Review the attached video from beginning to end using vision and visible on-screen text only.

Return neutral editable source metadata and an events array. Create one event row with count 1 for each visibly depicted individual catch or wildlife evidence sequence. Use CATCH only when a fish or other catch is visibly landed, brought aboard, removed from gear, or clearly displayed as the result of fishing. Use WILDLIFE for a visible non-catch animal, including a sighting or possible interaction. Do not create an event from off-screen information.

For edited footage, retain a preview, replay or possible duplicate as its own depicted-evidence row. Set evidence_role, evidence_group_ref and possible_duplicate_of_event_index so the reviewer can see and adjudicate the duplication. Event indexes are one-based in array order; use 0 when there is no possible duplicate. Give a start and end time covering the visible evidence, with 0 at the first attached frame. Use an empty common_name or scientific_name when identity is not visually supportable. Do not output a CAAB code. Set audio_used to false for every event.

For size, set size_status to NOT_ESTIMABLE, length_value to 0 and length_unit to NONE unless a visible scale or defensible known reference supports a measurement. For disposition, report only an action visibly shown in the event window; otherwise UNKNOWN. For wildlife interaction, distinguish SIGHTING, POSSIBLE_INTERACTION, CONFIRMED_INTERACTION and INCONCLUSIVE conservatively. A catch event uses NOT_APPLICABLE. Confidence must express visual support and must not exceed 0.98.

Return only JSON matching the supplied schema.~') task_prompt_template,
    to_clob(q'~{
  "type": "object",
  "properties": {
    "source_metadata": {
      "type": "object",
      "properties": {
        "title": {"type": "string"},
        "description": {"type": "string"},
        "region_text": {"type": "string"},
        "fishery_text": {"type": "string"},
        "gear_method_text": {"type": "string"},
        "reviewer_summary": {"type": "string"},
        "confidence": {"type": "number", "minimum": 0, "maximum": 0.98}
      },
      "required": ["title", "description", "region_text", "fishery_text", "gear_method_text", "reviewer_summary", "confidence"],
      "additionalProperties": false
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "start_second": {"type": "number"},
          "end_second": {"type": "number"},
          "event_type": {"type": "string", "enum": ["CATCH", "WILDLIFE"]},
          "common_name": {"type": "string"},
          "scientific_name": {"type": "string"},
          "count": {"type": "integer", "minimum": 1, "maximum": 1},
          "confidence": {"type": "number", "minimum": 0, "maximum": 0.98},
          "interaction_class": {"type": "string", "enum": ["NOT_APPLICABLE", "SIGHTING", "POSSIBLE_INTERACTION", "CONFIRMED_INTERACTION", "INCONCLUSIVE"]},
          "evidence_role": {"type": "string", "enum": ["PRIMARY", "PREVIEW_OR_REPLAY", "POSSIBLE_DUPLICATE", "UNCERTAIN"]},
          "evidence_group_ref": {"type": "string"},
          "possible_duplicate_of_event_index": {"type": "integer", "minimum": 0},
          "visual_evidence": {"type": "string"},
          "uncertainty": {"type": "string"},
          "size_status": {"type": "string", "enum": ["NOT_ESTIMABLE", "VISIBLE_SCALE", "KNOWN_REFERENCE"]},
          "length_value": {"type": "number", "minimum": 0},
          "length_unit": {"type": "string", "enum": ["NONE", "MM", "CM"]},
          "observed_disposition": {"type": "string", "enum": ["UNKNOWN", "PLACED_ON_DECK", "PLACED_IN_CONTAINER", "RELEASED_VISIBLE", "OTHER_VISIBLE"]},
          "audio_used": {"type": "boolean"}
        },
        "required": ["start_second", "end_second", "event_type", "common_name", "scientific_name", "count", "confidence", "interaction_class", "evidence_role", "evidence_group_ref", "possible_duplicate_of_event_index", "visual_evidence", "uncertainty", "size_status", "length_value", "length_unit", "observed_disposition", "audio_used"],
        "additionalProperties": false
      }
    },
    "limitations": {"type": "array", "items": {"type": "string"}}
  },
  "required": ["source_metadata", "events", "limitations"],
  "additionalProperties": false
}~') response_json_schema
  from dual
) s
on (d.prompt_key = s.prompt_key and d.prompt_version = s.prompt_version)
when not matched then insert (
  prompt_key, prompt_version, purpose_text, service_static_id, model_id,
  system_prompt, task_prompt_template, response_json_schema, contract_status
) values (
  s.prompt_key, s.prompt_version, s.purpose_text, s.service_static_id, s.model_id,
  s.system_prompt, s.task_prompt_template, s.response_json_schema, 'DRAFT'
);
/

merge into afma_cm_prompt_contracts d
using (
  select
    'catch-monitor-evidence' prompt_key,
    'catch-monitor-evidence-v4-batch-counting' prompt_version,
    'Propose time-bounded individual or batch catch counts and wildlife evidence from visual evidence only; distinguish newly observed catches from accumulated deck inventory.' purpose_text,
    'google_gemini_2_5_pro' service_static_id,
    'google.gemini-2.5-pro' model_id,
    to_clob(q'~You are an evidence-first fisheries video analyst supporting an authorised AFMA reviewer. Use only visible frames and visible on-screen text in the attached video. Never use, infer, quote or rely on audio, speech, captions derived from speech, filename, URL, working title or submitter notes. Analyse high-throughput fishing as time-bounded batches; do not create one output row per fish when several fish of the same candidate taxon are caught in the same short interval. Count newly visible catch transitions and distinguish them from fish already accumulated on deck so the same fish are not repeatedly added to catch totals. Preserve edited previews, replays and possible duplicates as visible evidence and label their relationship instead of silently discarding them. Never make a compliance finding or infer quota, legal size, weight, retained/released status, injury, survival or post-release condition. Estimate length only when a visible scale or a defensible known-size reference is present in the same evidence. Species identities are candidates for deterministic CAAB matching and officer review. Do not invent a CAAB code. Your output is an advisory proposal, never a final finding.~') system_prompt,
    to_clob(q'~Review the attached video from beginning to end using vision and visible on-screen text only.

Return neutral editable source metadata and an events array. For ordinary isolated catches, create one INDIVIDUAL event. When several catches occur rapidly, create one BATCH event per candidate taxon and coherent time window, normally 10 to 60 seconds, instead of one row per fish. The count is the number of newly observed catch transitions in that window: fish visibly landed, brought aboard, removed from gear or clearly displayed as the immediate result of fishing. Do not recount fish that were already visible on deck in an earlier window.

If a static or growing deck pile is visible but individual arrival transitions cannot be counted, create at most one VISIBLE_ACCUMULATION row per candidate taxon and coherent window. This is contextual inventory evidence, not a new-catch total. Use count_basis EXACT_VISIBLE only when every counted individual is clearly distinguishable; MINIMUM_VISIBLE when the number is a defensible lower bound and no upper bound is supportable; or ESTIMATED_RANGE when a point estimate and defensible lower/upper range are visually supportable. Use count_upper_bound 0 only for MINIMUM_VISIBLE. Keep event count values compact by grouping batches; do not emit hundreds of individual rows.

Use CATCH only for catch or visible accumulation evidence. Use WILDLIFE for a visible non-catch animal, including a sighting or possible interaction. For edited footage, retain a preview, replay or possible duplicate as its own depicted-evidence row and link it using evidence_role, evidence_group_ref and possible_duplicate_of_event_index. Event indexes are one-based in array order; use 0 when there is no possible duplicate. Give start and end times covering the visible evidence, with 0 at the first attached frame. Use an empty common_name or scientific_name when identity is not visually supportable. Do not output a CAAB code. Set audio_used to false for every event.

For size, set size_status to NOT_ESTIMABLE, length_value to 0 and length_unit to NONE unless a visible scale or defensible known reference supports a measurement. For disposition, report only an action visibly shown in the event window; otherwise UNKNOWN. For wildlife interaction, distinguish SIGHTING, POSSIBLE_INTERACTION, CONFIRMED_INTERACTION and INCONCLUSIVE conservatively. A catch event uses NOT_APPLICABLE. Confidence must express visual support and must not exceed 0.98.

Return only JSON matching the supplied schema.~') task_prompt_template,
    to_clob(q'~{
  "type": "object",
  "properties": {
    "source_metadata": {
      "type": "object",
      "properties": {
        "title": {"type": "string"},
        "description": {"type": "string"},
        "region_text": {"type": "string"},
        "fishery_text": {"type": "string"},
        "gear_method_text": {"type": "string"},
        "reviewer_summary": {"type": "string"},
        "confidence": {"type": "number", "minimum": 0, "maximum": 0.98}
      },
      "required": ["title", "description", "region_text", "fishery_text", "gear_method_text", "reviewer_summary", "confidence"],
      "additionalProperties": false
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "start_second": {"type": "number"},
          "end_second": {"type": "number"},
          "event_type": {"type": "string", "enum": ["CATCH", "WILDLIFE"]},
          "event_granularity": {"type": "string", "enum": ["INDIVIDUAL", "BATCH"]},
          "common_name": {"type": "string"},
          "scientific_name": {"type": "string"},
          "count": {"type": "integer", "minimum": 1, "maximum": 100000},
          "count_lower_bound": {"type": "integer", "minimum": 1, "maximum": 100000},
          "count_upper_bound": {"type": "integer", "minimum": 0, "maximum": 100000},
          "count_basis": {"type": "string", "enum": ["EXACT_VISIBLE", "MINIMUM_VISIBLE", "ESTIMATED_RANGE"]},
          "count_scope": {"type": "string", "enum": ["NEW_CATCHES", "VISIBLE_ACCUMULATION", "WILDLIFE"]},
          "confidence": {"type": "number", "minimum": 0, "maximum": 0.98},
          "interaction_class": {"type": "string", "enum": ["NOT_APPLICABLE", "SIGHTING", "POSSIBLE_INTERACTION", "CONFIRMED_INTERACTION", "INCONCLUSIVE"]},
          "evidence_role": {"type": "string", "enum": ["PRIMARY", "PREVIEW_OR_REPLAY", "POSSIBLE_DUPLICATE", "UNCERTAIN"]},
          "evidence_group_ref": {"type": "string"},
          "possible_duplicate_of_event_index": {"type": "integer", "minimum": 0},
          "visual_evidence": {"type": "string"},
          "uncertainty": {"type": "string"},
          "size_status": {"type": "string", "enum": ["NOT_ESTIMABLE", "VISIBLE_SCALE", "KNOWN_REFERENCE"]},
          "length_value": {"type": "number", "minimum": 0},
          "length_unit": {"type": "string", "enum": ["NONE", "MM", "CM"]},
          "observed_disposition": {"type": "string", "enum": ["UNKNOWN", "PLACED_ON_DECK", "PLACED_IN_CONTAINER", "RELEASED_VISIBLE", "OTHER_VISIBLE"]},
          "audio_used": {"type": "boolean"}
        },
        "required": ["start_second", "end_second", "event_type", "event_granularity", "common_name", "scientific_name", "count", "count_lower_bound", "count_upper_bound", "count_basis", "count_scope", "confidence", "interaction_class", "evidence_role", "evidence_group_ref", "possible_duplicate_of_event_index", "visual_evidence", "uncertainty", "size_status", "length_value", "length_unit", "observed_disposition", "audio_used"],
        "additionalProperties": false
      }
    },
    "limitations": {"type": "array", "items": {"type": "string"}}
  },
  "required": ["source_metadata", "events", "limitations"],
  "additionalProperties": false
}~') response_json_schema
  from dual
) s
on (d.prompt_key = s.prompt_key and d.prompt_version = s.prompt_version)
when not matched then insert (
  prompt_key, prompt_version, purpose_text, service_static_id, model_id,
  system_prompt, task_prompt_template, response_json_schema, contract_status
) values (
  s.prompt_key, s.prompt_version, s.purpose_text, s.service_static_id, s.model_id,
  s.system_prompt, s.task_prompt_template, s.response_json_schema, 'DRAFT'
);
/

create or replace package afma_cm_evidence_api authid definer as
  procedure approve_and_run(
    p_submission_id      in number,
    p_prompt_contract_id in number
  );

  procedure run_submission(
    p_submission_id in number
  );

  procedure adopt_analysis_rendition(
    p_target_submission_ref    in varchar2,
    p_rendition_submission_ref in varchar2,
    p_object_key               in varchar2 default 'ANALYSIS_480P',
    p_source_start_second      in number default 0
  );
end afma_cm_evidence_api;
/

create or replace package body afma_cm_evidence_api as
  function actor_name return varchar2 is
  begin
    return coalesce(apex_application.g_user, sys_context('APEX$SESSION','APP_USER'), user);
  end actor_name;

  function caab_spcode(
    p_common_name     in varchar2,
    p_scientific_name in varchar2
  ) return varchar2 is
    l_count  number;
    l_spcode varchar2(20);
  begin
    if trim(p_scientific_name) is not null then
      select count(distinct spcode), min(spcode)
        into l_count, l_spcode
        from csiro_caab_taxa_active_v
       where lower(trim(scientific_name)) = lower(trim(p_scientific_name));
      if l_count = 1 then
        return l_spcode;
      end if;
    end if;

    if trim(p_common_name) is not null then
      select count(distinct spcode), min(spcode)
        into l_count, l_spcode
        from (
          select spcode
            from csiro_caab_taxa_active_v
           where lower(trim(common_name)) = lower(trim(p_common_name))
          union
          select spcode
            from csiro_caab_common_name_search_v
           where normalized_common_name = csiro_caab_normalize_name(p_common_name)
        );
      if l_count = 1 then
        return l_spcode;
      end if;
    end if;
    return null;
  end caab_spcode;

  procedure adopt_analysis_rendition(
    p_target_submission_ref    in varchar2,
    p_rendition_submission_ref in varchar2,
    p_object_key               in varchar2 default 'ANALYSIS_480P',
    p_source_start_second      in number default 0
  ) is
    l_target_id       number;
    l_target_asset_id number;
    l_target_url      varchar2(2000);
    l_target_retention date;
    l_rendition_id    number;
    l_rendition_trip  number;
    l_object_key      varchar2(100) := upper(trim(p_object_key));
    l_existing_sha    varchar2(64);
    l_source_sha      varchar2(64);
    l_actor           varchar2(255) := actor_name;
    l_reviewed_count  number;
  begin
    if not regexp_like(l_object_key, '^ANALYSIS_[A-Z0-9_]+$') then
      raise_application_error(-20312, 'Analysis rendition object keys must start with ANALYSIS_.');
    end if;

    select vs.submission_id, ar.media_asset_id, vs.source_url, vs.retention_review_at
      into l_target_id, l_target_asset_id, l_target_url, l_target_retention
      from afma_cm_video_submissions vs
      join afma_cm_analysis_runs ar on ar.analysis_run_id = vs.analysis_run_id
     where vs.submission_ref = trim(p_target_submission_ref)
       and vs.processing_status in ('READY_FOR_ANALYSIS','ANALYSIS_FAILED','ANALYSIS_COMPLETE')
     for update of vs.processing_status;

    select count(*)
      into l_reviewed_count
      from afma_cm_observations o
      join afma_cm_video_submissions vs on vs.analysis_run_id = o.analysis_run_id
     where vs.submission_id = l_target_id
       and o.reviewer_status <> 'NEEDS_REVIEW';
    if l_reviewed_count > 0 then
      raise_application_error(-20321, 'Analysis renditions cannot be added after an officer has reviewed an event.');
    end if;

    select vs.submission_id, ar.trip_id, mo.sha256
      into l_rendition_id, l_rendition_trip, l_source_sha
      from afma_cm_video_submissions vs
      join afma_cm_analysis_runs ar on ar.analysis_run_id = vs.analysis_run_id
      join afma_cm_media_objects mo
        on mo.submission_id = vs.submission_id
       and mo.object_key = 'SOURCE'
     where vs.submission_ref = trim(p_rendition_submission_ref)
       and vs.input_method = 'UPLOAD'
       and vs.processing_status = 'READY_FOR_ANALYSIS';

    begin
      select sha256 into l_existing_sha
        from afma_cm_media_objects
       where submission_id = l_target_id
         and object_key = l_object_key;
      if l_existing_sha <> l_source_sha then
        raise_application_error(-20313, 'A different rendition already uses this object key.');
      end if;
    exception
      when no_data_found then
        insert into afma_cm_media_objects (
          submission_id, media_asset_id, object_key, object_role,
          original_filename, mime_type, file_bytes, sha256, duration_seconds,
          source_start_second, source_end_second, content_blob,
          source_url_snapshot, source_video_id, acquisition_method,
          acquisition_note, audio_present_yn, storage_region, retention_review_at
        )
        select l_target_id, l_target_asset_id, l_object_key, 'ANALYSIS_CLIP',
               mo.original_filename, mo.mime_type, mo.file_bytes, mo.sha256, mo.duration_seconds,
               p_source_start_second, p_source_start_second + mo.duration_seconds, mo.content_blob,
               l_target_url, mo.source_video_id, 'CONTROLLED_PROJECT_IMPORT',
               'Time-bounded low-bitrate analysis rendition derived from the retained source. Original source bytes remain stored separately.',
               mo.audio_present_yn, mo.storage_region, l_target_retention
          from afma_cm_media_objects mo
         where mo.submission_id = l_rendition_id
           and mo.object_key = 'SOURCE';
    end;

    update afma_cm_video_submissions
       set processing_status = 'READY_FOR_ANALYSIS',
           processing_stage = 'ANALYSIS_RENDITION_READY',
           progress_percent = 40,
           processing_message = 'Original source retained. One or more lower-bitrate analysis renditions are ready for Gemini Pro; no evidence events have been published.',
           processing_completed_at = null,
           last_progress_at = systimestamp
     where submission_id = l_target_id;

    update afma_cm_video_submissions
       set video_blob = null,
           file_bytes = null,
           processing_status = 'DELETED',
           processing_stage = 'ANALYSIS_RENDITION_ADOPTED',
           progress_percent = 100,
           processing_message = 'Temporary rendition upload adopted by ' || trim(p_target_submission_ref) || '; temporary payload cleared.',
           processing_completed_at = systimestamp,
           last_progress_at = systimestamp,
           deleted_at = systimestamp,
           deleted_by = l_actor
     where submission_id = l_rendition_id;

    update afma_cm_trips
       set status = 'ARCHIVED'
     where trip_id = l_rendition_trip;
    commit;
  exception
    when no_data_found then
      raise_application_error(-20314, 'The target or completed temporary rendition upload was not found.');
  end adopt_analysis_rendition;

  procedure run_submission(
    p_submission_id in number
  ) is
    l_analysis_run_id number;
    l_source_duration  number;
    l_prompt_id        number;
    l_prompt_version   varchar2(100);
    l_service_id       varchar2(255);
    l_model_id         varchar2(255);
    l_system_prompt    clob;
    l_task_prompt      clob;
    l_effective_prompt clob;
    l_schema           clob;
    l_response         clob;
    l_root             json_object_t;
    l_metadata         json_object_t;
    l_events           json_array_t;
    l_event            json_object_t;
    l_attachments      apex_ai.t_attachments := apex_ai.t_attachments();
    l_evidence_run_id  number;
    l_reviewed_count   number;
    l_clip_count       number := 0;
    l_clip_no          number := 0;
    l_clip_event_base  number := 0;
    l_event_count      number := 0;
    l_start_second     number;
    l_end_second       number;
    l_proposed_count   number;
    l_count_lower      number;
    l_count_upper      number;
    l_confidence       number;
    l_length_value     number;
    l_duplicate_index  number;
    l_event_type       varchar2(30);
    l_event_granularity varchar2(30);
    l_count_basis      varchar2(30);
    l_count_scope      varchar2(30);
    l_common_name      varchar2(300);
    l_scientific_name  varchar2(300);
    l_interaction      varchar2(40);
    l_evidence_role    varchar2(30);
    l_group_ref        varchar2(100);
    l_visual_evidence  varchar2(1000);
    l_uncertainty      varchar2(1000);
    l_size_status      varchar2(30);
    l_length_unit      varchar2(10);
    l_disposition      varchar2(40);
    l_spcode           varchar2(20);
    l_error            varchar2(4000);
    l_meta_title       varchar2(500);
    l_meta_description varchar2(2000);
    l_meta_region      varchar2(500);
    l_meta_fishery     varchar2(500);
    l_meta_gear        varchar2(500);
    l_meta_summary     varchar2(4000);
    l_meta_confidence  number;
    l_cached_response  boolean;
    l_new_model_calls  number := 0;
    c_max_model_calls_per_request constant pls_integer := 6;
  begin
    if upper(coalesce(actor_name, 'ANONYMOUS')) in ('ANONYMOUS','NOBODY','PUBLIC_USER') then
      raise_application_error(-20300, 'An authenticated authorised reviewer is required.');
    end if;

    update afma_cm_evidence_runs
       set run_status = 'FAILED',
           validation_status = 'REJECTED',
           validation_issues = 'The prior synchronous request exceeded the demo gateway window. Its validated earlier segment responses remain cached for a bounded resume.',
           completed_at = systimestamp
     where submission_id = p_submission_id
       and run_status = 'RUNNING'
       and started_at < systimestamp - numtodsinterval(7, 'MINUTE');
    update afma_cm_video_submissions
       set processing_status = 'ANALYSIS_FAILED',
           processing_stage = 'ANALYSIS_FAILED',
           processing_message = 'The prior browser request stopped reporting progress. Resume analysis to reuse validated segments and continue in bounded batches.',
           processing_completed_at = systimestamp,
           last_progress_at = systimestamp
     where submission_id = p_submission_id
       and processing_status = 'ANALYSING'
       and last_progress_at < systimestamp - numtodsinterval(7, 'MINUTE');
    commit;

    select vs.analysis_run_id, mo.duration_seconds
      into l_analysis_run_id, l_source_duration
      from afma_cm_video_submissions vs
      join afma_cm_media_objects mo
        on mo.submission_id = vs.submission_id
       and mo.object_key = 'SOURCE'
     where vs.submission_id = p_submission_id
       and vs.processing_status in ('READY_FOR_ANALYSIS','ANALYSIS_FAILED','ANALYSIS_COMPLETE')
       and vs.rights_confirmed_yn = 'Y'
       and vs.handling_acknowledged_yn = 'Y'
     for update of vs.processing_status;

    select prompt_contract_id, prompt_version, service_static_id, model_id,
           system_prompt, task_prompt_template, response_json_schema
      into l_prompt_id, l_prompt_version, l_service_id, l_model_id,
           l_system_prompt, l_task_prompt, l_schema
      from afma_cm_prompt_contracts
     where prompt_key = 'catch-monitor-evidence'
       and contract_status = 'ACTIVE';

    select count(*) into l_reviewed_count
      from afma_cm_observations
     where analysis_run_id = l_analysis_run_id
       and reviewer_status <> 'NEEDS_REVIEW';
    if l_reviewed_count > 0 then
      raise_application_error(-20301, 'This analysis already has officer decisions and cannot be replaced by a rerun.');
    end if;

    delete from afma_cm_observations
     where analysis_run_id = l_analysis_run_id
       and reviewer_status = 'NEEDS_REVIEW';

    select count(*)
      into l_clip_count
      from afma_cm_media_objects mo
     where mo.submission_id = p_submission_id
       and mo.object_key like 'ANALYSIS_SEG_%';
    if l_clip_count = 0 then
      l_clip_count := 1;
    end if;

    update afma_cm_video_submissions
       set processing_status = 'ANALYSING',
           processing_stage = 'GEMINI_ANALYSIS',
           progress_percent = 55,
           processing_message = 'Gemini Pro is reviewing ' || l_clip_count || ' time-bounded visual-only analysis segment(s).',
           processing_started_at = coalesce(processing_started_at, systimestamp),
           processing_completed_at = null,
           worker_job_ref = 'EVIDENCE-' || lower(substr(rawtohex(sys_guid()), 1, 12)),
           last_progress_at = systimestamp
     where submission_id = p_submission_id;

    update afma_cm_analysis_runs
       set run_status = 'RUNNING',
           model_version = l_model_id,
           run_notes = 'Segmented full-video visual-only Gemini evidence analysis is running under ' || l_prompt_version || '.'
     where analysis_run_id = l_analysis_run_id;
    commit;

    for m in (
      select mo.*
        from afma_cm_media_objects mo
       where mo.submission_id = p_submission_id
         and (
           (exists (select 1 from afma_cm_media_objects sx where sx.submission_id = p_submission_id and sx.object_key like 'ANALYSIS_SEG_%') and mo.object_key like 'ANALYSIS_SEG_%')
           or
           (not exists (select 1 from afma_cm_media_objects sx where sx.submission_id = p_submission_id and sx.object_key like 'ANALYSIS_SEG_%')
            and mo.media_object_id = (
              select max(mx.media_object_id) keep (dense_rank first order by case when mx.object_role = 'ANALYSIS_CLIP' then 0 else 1 end, mx.media_object_id desc)
                from afma_cm_media_objects mx
               where mx.submission_id = p_submission_id
            ))
         )
       order by coalesce(mo.source_start_second, 0), mo.media_object_id
    ) loop
      l_clip_no := l_clip_no + 1;
      l_clip_event_base := l_event_count;
      l_cached_response := false;
      begin
        select evidence_run_id, response_json
          into l_evidence_run_id, l_response
          from (
            select evidence_run_id, response_json
              from afma_cm_evidence_runs
             where submission_id = p_submission_id
               and media_object_id = m.media_object_id
               and prompt_contract_id = l_prompt_id
               and run_status = 'COMPLETE'
               and validation_status = 'PASS'
               and response_json is not null
             order by evidence_run_id desc
          )
         where rownum = 1;
        l_cached_response := true;
      exception
        when no_data_found then
          l_cached_response := false;
      end;

      if not l_cached_response then
        insert into afma_cm_evidence_runs (
          submission_id, analysis_run_id, media_object_id, prompt_contract_id,
          service_static_id, model_id, prompt_version, run_status
        ) values (
          p_submission_id, l_analysis_run_id, m.media_object_id, l_prompt_id,
          l_service_id, l_model_id, l_prompt_version, 'RUNNING'
        ) returning evidence_run_id into l_evidence_run_id;

        update afma_cm_video_submissions
           set progress_percent = least(70, 54 + floor((l_clip_no / l_clip_count) * 16)),
               processing_message = 'Gemini Pro is reviewing visual-only segment ' || l_clip_no || ' of ' || l_clip_count ||
                 ' (source seconds ' || to_char(coalesce(m.source_start_second, 0)) || '–' || to_char(coalesce(m.source_end_second, m.duration_seconds)) || ').',
               last_progress_at = systimestamp
         where submission_id = p_submission_id;
        commit;

        l_attachments := apex_ai.t_attachments();
        l_attachments.extend;
        l_attachments(1) := apex_ai.t_attachment(
          mime_type    => m.mime_type,
          content_blob => m.content_blob,
          file_name    => substr(m.original_filename, 1, 255),
          detail_level => apex_ai.c_detail_level_high
        );
        l_effective_prompt := l_task_prompt || chr(10) || chr(10) ||
          'This attachment is segment ' || l_clip_no || ' of ' || l_clip_count || '. Treat its first frame as relative second 0. ' ||
          'Its source-video range is ' || to_char(coalesce(m.source_start_second, 0)) || ' through ' ||
          to_char(coalesce(m.source_end_second, m.duration_seconds)) || ' seconds. Return event start_second and end_second relative to this attachment; the application will add the audited source offset.';

        l_response := apex_ai.generate(
          p_prompt               => l_effective_prompt,
          p_system_prompt        => l_system_prompt,
          p_service_static_id    => l_service_id,
          p_temperature          => 0,
          p_attachments          => l_attachments,
          p_response_json_schema => l_schema
        );
        l_new_model_calls := l_new_model_calls + 1;

        update afma_cm_evidence_runs
           set response_json = l_response
         where evidence_run_id = l_evidence_run_id;
      else
        update afma_cm_video_submissions
           set processing_message = 'Reusing validated Gemini response for segment ' || l_clip_no || ' of ' || l_clip_count || '; no duplicate model call.',
               last_progress_at = systimestamp
         where submission_id = p_submission_id;
      end if;

      l_root := json_object_t.parse(l_response);
      l_metadata := l_root.get_object('source_metadata');
      l_events := l_root.get_array('events');

      if l_clip_no = 1 then
        l_meta_title := substr(l_metadata.get_string('title'), 1, 500);
        l_meta_description := substr(l_metadata.get_string('description'), 1, 2000);
        l_meta_region := substr(l_metadata.get_string('region_text'), 1, 500);
        l_meta_fishery := substr(l_metadata.get_string('fishery_text'), 1, 500);
        l_meta_gear := substr(l_metadata.get_string('gear_method_text'), 1, 500);
        l_meta_summary := substr(l_metadata.get_string('reviewer_summary'), 1, 4000);
        l_meta_confidence := l_metadata.get_number('confidence');
        update afma_cm_video_submissions
           set ai_display_title = l_meta_title,
               ai_description_text = l_meta_description,
               ai_region_text = l_meta_region,
               ai_fishery_text = l_meta_fishery,
               ai_gear_method_text = l_meta_gear,
               ai_video_summary = l_meta_summary,
               ai_metadata_confidence = l_meta_confidence,
               metadata_response_json = l_response,
               metadata_status = 'ANALYSING',
               metadata_model_id = l_model_id,
               metadata_prompt_version = l_prompt_version,
               metadata_generated_at = systimestamp
         where submission_id = p_submission_id;
      end if;

      for i in 0 .. l_events.get_size - 1 loop
        l_event := treat(l_events.get(i) as json_object_t);
        l_start_second := l_event.get_number('start_second');
        l_end_second := l_event.get_number('end_second');
        l_event_type := l_event.get_string('event_type');
        l_event_granularity := l_event.get_string('event_granularity');
        l_proposed_count := l_event.get_number('count');
        l_count_lower := l_event.get_number('count_lower_bound');
        l_count_upper := l_event.get_number('count_upper_bound');
        l_count_basis := l_event.get_string('count_basis');
        l_count_scope := l_event.get_string('count_scope');
        l_common_name := trim(l_event.get_string('common_name'));
        l_scientific_name := trim(l_event.get_string('scientific_name'));
        l_confidence := l_event.get_number('confidence');
        l_interaction := l_event.get_string('interaction_class');
        l_evidence_role := l_event.get_string('evidence_role');
        l_group_ref := nullif(trim(l_event.get_string('evidence_group_ref')), '');
        l_duplicate_index := l_event.get_number('possible_duplicate_of_event_index');
        l_visual_evidence := l_event.get_string('visual_evidence');
        l_uncertainty := l_event.get_string('uncertainty');
        l_size_status := l_event.get_string('size_status');
        l_length_value := l_event.get_number('length_value');
        l_length_unit := nullif(l_event.get_string('length_unit'), 'NONE');
        l_disposition := l_event.get_string('observed_disposition');

        if l_proposed_count < 1 or l_count_lower < 1 then
          raise_application_error(-20302, 'Every evidence event must propose a positive count and lower bound.');
        end if;
        if l_count_basis = 'EXACT_VISIBLE' and l_count_lower = l_proposed_count and l_count_upper = 0 then
          l_count_upper := l_proposed_count;
          l_uncertainty := substr(
            trim(l_uncertainty || ' Deterministic repair: the exact-visible upper bound was normalised from zero to the stated count; raw model JSON is retained in the evidence-run audit.'),
            1,
            1000
          );
        elsif l_count_basis = 'EXACT_VISIBLE' and (l_count_lower <> l_proposed_count or l_count_upper <> l_proposed_count) then
          raise_application_error(-20316, 'An exact visible count must have equal point, lower and upper values.');
        elsif l_count_basis = 'MINIMUM_VISIBLE' and (l_proposed_count <> l_count_lower or l_count_upper <> 0) then
          raise_application_error(-20317, 'A minimum visible count must use its lower bound as count and zero as the unknown upper bound.');
        elsif l_count_basis = 'ESTIMATED_RANGE' and (l_count_upper < l_count_lower or l_proposed_count < l_count_lower or l_proposed_count > l_count_upper) then
          raise_application_error(-20318, 'An estimated batch count must fall within its non-empty lower and upper range.');
        end if;
        if l_event_granularity = 'INDIVIDUAL' and l_proposed_count <> 1 then
          raise_application_error(-20319, 'An individual event must have count 1; multiple catches must use a batch event.');
        end if;
        if (l_event_type = 'WILDLIFE' and l_count_scope <> 'WILDLIFE') or
           (l_event_type = 'CATCH' and l_count_scope = 'WILDLIFE') then
          raise_application_error(-20320, 'Count scope does not match the evidence event type.');
        end if;
        if l_event.get_boolean('audio_used') then
          raise_application_error(-20303, 'The response declared audio use; AFMA evidence analysis is visual-only.');
        end if;
        if l_start_second < 0 or l_end_second < l_start_second or l_end_second > m.duration_seconds + 1 then
          raise_application_error(-20304, 'An event timestamp falls outside its stored analysis segment.');
        end if;
        if coalesce(m.source_start_second, 0) + l_end_second > l_source_duration + 1 then
          raise_application_error(-20315, 'An absolute event timestamp falls outside the retained source duration.');
        end if;
        if l_confidence < 0 or l_confidence > 0.98 then
          raise_application_error(-20305, 'An event confidence falls outside 0..0.98.');
        end if;
        if l_event_type = 'CATCH' and l_interaction <> 'NOT_APPLICABLE' then
          raise_application_error(-20306, 'Catch events must use NOT_APPLICABLE interaction classification.');
        end if;
        if l_size_status = 'NOT_ESTIMABLE' and (l_length_value <> 0 or l_length_unit is not null) then
          raise_application_error(-20307, 'An unestimable size cannot contain a length value or unit.');
        end if;
        if l_duplicate_index > i then
          raise_application_error(-20308, 'A possible duplicate must refer to an earlier one-based event index in its segment.');
        end if;

        l_spcode := caab_spcode(l_common_name, l_scientific_name);
        insert into afma_cm_observations (
          analysis_run_id, observation_type, start_second, end_second,
          ai_taxon_text, ai_scientific_name, ai_spcode, ai_count,
          ai_count_basis, ai_count_lower_bound, ai_count_upper_bound, ai_count_scope,
          ai_event_granularity,
          ai_confidence,
          ai_catch_state, ai_interaction_class, evidence_role, evidence_group_ref,
          evidence_text, ai_uncertainty, ai_size_value, ai_size_unit,
          ai_size_basis, ai_disposition, possible_duplicate_of_index, reviewer_status
        ) values (
          l_analysis_run_id, l_event_type,
          coalesce(m.source_start_second, 0) + l_start_second,
          coalesce(m.source_start_second, 0) + l_end_second,
          substr(coalesce(l_common_name, l_scientific_name, 'Unresolved'), 1, 300),
          substr(l_scientific_name, 1, 300), l_spcode, l_proposed_count,
          l_count_basis, l_count_lower, nullif(l_count_upper, 0), l_count_scope,
          l_event_granularity,
          l_confidence,
          'UNKNOWN', l_interaction, l_evidence_role,
          substr(case when l_group_ref is not null then m.object_key || ':' || l_group_ref end, 1, 100),
          substr(l_visual_evidence, 1, 1000), substr(l_uncertainty, 1, 1000),
          case when l_size_status = 'NOT_ESTIMABLE' then null else l_length_value end,
          l_length_unit, l_size_status, l_disposition,
          case when l_duplicate_index = 0 then null else l_clip_event_base + l_duplicate_index end,
          'NEEDS_REVIEW'
        );
        l_event_count := l_event_count + 1;
      end loop;

      update afma_cm_evidence_runs
         set run_status = 'COMPLETE',
             validation_status = 'PASS',
             validation_issues = null,
             proposed_event_count = l_event_count - l_clip_event_base,
             completed_at = systimestamp
       where evidence_run_id = l_evidence_run_id;
      commit;

      if l_new_model_calls >= c_max_model_calls_per_request and l_clip_no < l_clip_count then
        exit;
      end if;
    end loop;

    if l_clip_no < l_clip_count then
      update afma_cm_video_submissions
         set processing_status = 'READY_FOR_ANALYSIS',
             processing_stage = 'ANALYSIS_BATCH_READY',
             progress_percent = least(69, 54 + floor((l_clip_no / l_clip_count) * 16)),
             processing_message = 'Analysis checkpoint saved after segment ' || l_clip_no || ' of ' || l_clip_count ||
               '. Validated segment responses are cached; continue to process the next bounded batch.',
             processing_completed_at = null,
             last_progress_at = systimestamp
       where submission_id = p_submission_id;
      update afma_cm_analysis_runs
         set run_status = 'RUNNING',
             run_notes = 'Checkpointed segmented visual analysis under ' || l_prompt_version ||
               ' after ' || l_clip_no || ' of ' || l_clip_count || ' segments. Successful responses are cached.'
       where analysis_run_id = l_analysis_run_id;
      commit;
      return;
    end if;

    update afma_cm_video_submissions
       set metadata_status = 'NEEDS_REVIEW',
           processing_stage = 'CAAB_MATCHING',
           progress_percent = 75,
           processing_message = 'All segment responses are stored. Candidate species names have been matched deterministically to CAAB.',
           last_progress_at = systimestamp
     where submission_id = p_submission_id;

    update afma_cm_video_submissions
       set processing_stage = 'VALIDATING_RESULTS',
           progress_percent = 90,
           processing_message = 'CAAB matching is complete. Event timing, counts, evidence roles and visual-only constraints passed per-segment validation.',
           last_progress_at = systimestamp
     where submission_id = p_submission_id;

    update afma_cm_analysis_runs
       set run_status = 'COMPLETE',
           model_version = l_model_id,
           completed_at = systimestamp,
           run_notes = l_event_count || ' visual evidence event(s) proposed by ' || l_prompt_version || '; CAAB matching and deterministic validation passed. Officer review is required.'
     where analysis_run_id = l_analysis_run_id;

    update afma_cm_video_submissions
       set processing_status = 'ANALYSIS_COMPLETE',
           processing_stage = 'READY_FOR_REVIEW',
           progress_percent = 100,
           processing_message = l_event_count || ' proposed evidence event(s) passed deterministic checks and are ready for AFMA review. No event is confirmed automatically.',
           processing_completed_at = systimestamp,
           last_progress_at = systimestamp
     where submission_id = p_submission_id;
    commit;
  exception
    when no_data_found then
      raise_application_error(-20309, 'No active evidence prompt or eligible stored video was found.');
    when others then
      l_error := substr(sqlerrm || chr(10) || dbms_utility.format_error_backtrace, 1, 4000);
      if l_analysis_run_id is not null then
        delete from afma_cm_observations
         where analysis_run_id = l_analysis_run_id
           and reviewer_status = 'NEEDS_REVIEW';
        update afma_cm_analysis_runs
           set run_status = 'FAILED',
               completed_at = systimestamp,
               run_notes = substr('Evidence analysis failed: ' || l_error, 1, 2000)
         where analysis_run_id = l_analysis_run_id;
      end if;
      update afma_cm_evidence_runs
         set run_status = 'FAILED',
             validation_status = 'REJECTED',
             validation_issues = l_error,
             completed_at = systimestamp
       where submission_id = p_submission_id
         and run_status = 'RUNNING';
      update afma_cm_video_submissions
         set processing_status = 'ANALYSIS_FAILED',
             processing_stage = 'ANALYSIS_FAILED',
             processing_message = case
               when instr(l_error, 'ORA-20959') > 0 then
                 'Gemini Pro did not complete the current video segment. No review events were published. Retry after reviewing the prompt or use shorter analysis segments; technical details are retained in the evidence-run audit.'
               else
                 'Analysis stopped without publishing review events. Technical details are retained in the evidence-run audit.'
             end,
             processing_completed_at = systimestamp,
             last_progress_at = systimestamp
       where submission_id = p_submission_id;
      commit;
      raise;
  end run_submission;

  procedure approve_and_run(
    p_submission_id      in number,
    p_prompt_contract_id in number
  ) is
    l_status varchar2(20);
    l_key    varchar2(100);
  begin
    select prompt_key, contract_status
      into l_key, l_status
      from afma_cm_prompt_contracts
     where prompt_contract_id = p_prompt_contract_id;
    if l_key <> 'catch-monitor-evidence' then
      raise_application_error(-20310, 'The selected contract is not the Catch Monitor evidence prompt.');
    end if;
    if l_status <> 'ACTIVE' then
      afma_cm_prompt_api.approve_and_activate(p_prompt_contract_id, 'Y');
      commit;
    end if;
    run_submission(p_submission_id);
  end approve_and_run;
end afma_cm_evidence_api;
/

comment on table afma_cm_evidence_runs is 'Auditable full-video Gemini evidence runs. Raw model output is retained before deterministic validation and reviewer-queue publication.';
/
comment on column afma_cm_observations.ai_size_basis is 'Visual measurement basis: NOT_ESTIMABLE, VISIBLE_SCALE or KNOWN_REFERENCE. Never a legal-size finding.';
/
comment on column afma_cm_observations.possible_duplicate_of_index is 'One-based model event index for a possible edited preview/replay duplicate; reviewer adjudication remains required.';
/
comment on column afma_cm_observations.ai_count_basis is 'Visual count basis: EXACT_VISIBLE, MINIMUM_VISIBLE or ESTIMATED_RANGE.';
/
comment on column afma_cm_observations.ai_count_scope is 'NEW_CATCHES, VISIBLE_ACCUMULATION or WILDLIFE. Visible accumulation is excluded from new-catch reconciliation totals.';
/
comment on column afma_cm_observations.ai_event_granularity is 'INDIVIDUAL or BATCH visual evidence grouping proposed by the model.';
/

prompt AFMA 118 complete
