set define off

-- Execution authority: AFMA parsing schema owner through the verified AFMA APEX SQL Commands session.
-- Target: AIDEMODB workspace/schema AFMA; persistent human/AI Evidence Review Studio for application 101.
prompt AFMA 119 - Add Catch Monitor Evidence Review Studio

declare
  l_count number;
begin
  select count(*) into l_count from user_tables where table_name = 'AFMA_CM_REVIEW_SESSIONS';
  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_review_sessions (
        review_session_id    number generated by default on null as identity,
        observation_id       number not null,
        submission_id        number,
        media_object_id      number,
        session_status       varchar2(30 char) default 'OPEN' not null,
        service_static_id    varchar2(255 char) default 'google_gemini_2_5_pro' not null,
        model_id             varchar2(255 char) default 'google.gemini-2.5-pro' not null,
        prompt_version       varchar2(100 char) default 'catch-monitor-review-agent-v1' not null,
        created_at           timestamp with local time zone default systimestamp not null,
        created_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        updated_at           timestamp with local time zone default systimestamp not null,
        updated_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        accepted_at          timestamp with local time zone,
        accepted_by          varchar2(255 char),
        constraint afma_cm_review_sessions_pk primary key (review_session_id),
        constraint afma_cm_review_sessions_fk_obs foreign key (observation_id) references afma_cm_observations (observation_id),
        constraint afma_cm_review_sessions_fk_sub foreign key (submission_id) references afma_cm_video_submissions (submission_id),
        constraint afma_cm_review_sessions_fk_media foreign key (media_object_id) references afma_cm_media_objects (media_object_id),
        constraint afma_cm_review_sessions_ck_status check (session_status in ('OPEN','ANALYSING','PROPOSAL_READY','ACCEPTED','CLOSED','ERROR'))
      )
    ]';
    execute immediate q'[create index afma_cm_review_sessions_ix1 on afma_cm_review_sessions (observation_id, updated_at)]';
  end if;

  select count(*) into l_count from user_tables where table_name = 'AFMA_CM_REVIEW_MESSAGES';
  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_review_messages (
        review_message_id    number generated by default on null as identity,
        review_session_id    number not null,
        message_role         varchar2(20 char) not null,
        message_text         clob not null,
        time_start_second    number,
        time_end_second      number,
        created_at           timestamp with local time zone default systimestamp not null,
        created_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint afma_cm_review_messages_pk primary key (review_message_id),
        constraint afma_cm_review_messages_fk_session foreign key (review_session_id) references afma_cm_review_sessions (review_session_id),
        constraint afma_cm_review_messages_ck_role check (message_role in ('REVIEWER','AGENT','SYSTEM','TOOL')),
        constraint afma_cm_review_messages_ck_time check (time_start_second is null or (time_start_second >= 0 and (time_end_second is null or time_end_second >= time_start_second)))
      )
    ]';
    execute immediate q'[create index afma_cm_review_messages_ix1 on afma_cm_review_messages (review_session_id, review_message_id)]';
  end if;

  select count(*) into l_count from user_tables where table_name = 'AFMA_CM_REVIEW_TOOL_RUNS';
  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_review_tool_runs (
        tool_run_id          number generated by default on null as identity,
        review_session_id    number not null,
        tool_name            varchar2(64 char) not null,
        arguments_json       clob,
        result_json          clob,
        run_status           varchar2(20 char) default 'RUNNING' not null,
        evidence_run_id      number,
        started_at           timestamp with local time zone default systimestamp not null,
        completed_at         timestamp with local time zone,
        error_message        varchar2(4000 char),
        created_by           varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint afma_cm_review_tool_runs_pk primary key (tool_run_id),
        constraint afma_cm_review_tool_runs_fk_session foreign key (review_session_id) references afma_cm_review_sessions (review_session_id),
        constraint afma_cm_review_tool_runs_fk_evidence foreign key (evidence_run_id) references afma_cm_evidence_runs (evidence_run_id),
        constraint afma_cm_review_tool_runs_ck_status check (run_status in ('RUNNING','COMPLETE','FAILED')),
        constraint afma_cm_review_tool_runs_ck_args check (arguments_json is json),
        constraint afma_cm_review_tool_runs_ck_result check (result_json is json)
      )
    ]';
    execute immediate q'[create index afma_cm_review_tool_runs_ix1 on afma_cm_review_tool_runs (review_session_id, tool_run_id)]';
  end if;

  select count(*) into l_count from user_tables where table_name = 'AFMA_CM_REVIEW_PROPOSALS';
  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_review_proposals (
        review_proposal_id  number generated by default on null as identity,
        review_session_id   number not null,
        source_tool_run_id  number,
        proposal_source     varchar2(30 char) default 'AGENT' not null,
        proposal_status     varchar2(20 char) default 'DRAFT' not null,
        taxon_text          varchar2(500 char),
        spcode              varchar2(20 char),
        proposed_count      number not null,
        start_second        number not null,
        end_second          number not null,
        interaction_class   varchar2(40 char) default 'NOT_APPLICABLE' not null,
        confidence          number,
        evidence_summary    varchar2(4000 char) not null,
        created_at          timestamp with local time zone default systimestamp not null,
        created_by          varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        decided_at          timestamp with local time zone,
        decided_by          varchar2(255 char),
        constraint afma_cm_review_proposals_pk primary key (review_proposal_id),
        constraint afma_cm_review_proposals_fk_session foreign key (review_session_id) references afma_cm_review_sessions (review_session_id),
        constraint afma_cm_review_proposals_fk_tool foreign key (source_tool_run_id) references afma_cm_review_tool_runs (tool_run_id),
        constraint afma_cm_review_proposals_ck_source check (proposal_source in ('AGENT','OFFICER_EDIT')),
        constraint afma_cm_review_proposals_ck_status check (proposal_status in ('DRAFT','ACCEPTED','SUPERSEDED','REJECTED')),
        constraint afma_cm_review_proposals_ck_count check (proposed_count >= 0 and proposed_count = trunc(proposed_count)),
        constraint afma_cm_review_proposals_ck_time check (start_second >= 0 and end_second > start_second),
        constraint afma_cm_review_proposals_ck_interaction check (interaction_class in ('NOT_APPLICABLE','SIGHTING','POSSIBLE_INTERACTION','CONFIRMED_INTERACTION','INCONCLUSIVE')),
        constraint afma_cm_review_proposals_ck_confidence check (confidence is null or confidence between 0 and 1)
      )
    ]';
    execute immediate q'[create index afma_cm_review_proposals_ix1 on afma_cm_review_proposals (review_session_id, review_proposal_id)]';
  end if;
end;
/

create or replace package afma_cm_review_agent_api authid definer as
  function actor_name return varchar2;
  function fmt_second(p_second in number) return varchar2;

  function open_session(
    p_observation_id in number
  ) return number;

  procedure send_message(
    p_review_session_id in number,
    p_message           in varchar2,
    p_time_start_second in number default null,
    p_time_end_second   in number default null
  );

  procedure accept_proposal(
    p_review_session_id  in number,
    p_review_proposal_id in number default null,
    p_taxon_text         in varchar2 default null,
    p_spcode             in varchar2 default null,
    p_count              in number,
    p_start_second       in number,
    p_end_second         in number,
    p_interaction_class  in varchar2 default 'NOT_APPLICABLE',
    p_reviewer_note      in varchar2 default null
  );

  procedure escalate_session(
    p_review_session_id in number,
    p_reviewer_note     in varchar2 default null
  );

  function session_html(
    p_review_session_id in number
  ) return clob;

  procedure get_segment_media(
    p_review_session_id   in number,
    p_filename            out varchar2,
    p_mime_type           out varchar2,
    p_source_start_second out number,
    p_source_end_second   out number,
    p_content             out nocopy blob
  );

  procedure tool_get_review_context(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  );

  procedure tool_inspect_stored_segment(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  );

  procedure tool_lookup_caab_candidates(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  );

  procedure tool_create_corrected_proposal(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  );
end afma_cm_review_agent_api;
/

create or replace package body afma_cm_review_agent_api as
  function actor_name return varchar2 is
  begin
    return coalesce(apex_application.g_user, sys_context('APEX$SESSION','APP_USER'), user);
  end actor_name;

  function h(p_value in varchar2) return varchar2 is
  begin
    return apex_escape.html(p_value);
  end h;

  function a(p_value in varchar2) return varchar2 is
  begin
    return apex_escape.html_attribute(p_value);
  end a;

  procedure add_text(p_html in out nocopy clob, p_text in varchar2) is
  begin
    if p_text is not null then
      dbms_lob.writeappend(p_html, length(p_text), p_text);
    end if;
  end add_text;

  procedure add_line(p_html in out nocopy clob, p_text in varchar2 default null) is
  begin
    add_text(p_html, p_text || chr(10));
  end add_line;

  function fmt_second(p_second in number) return varchar2 is
  begin
    return lpad(trunc(coalesce(p_second, 0) / 60), 2, '0') || ':' ||
           lpad(mod(trunc(coalesce(p_second, 0)), 60), 2, '0');
  end fmt_second;

  function youtube_video_id(p_source_url in varchar2) return varchar2 is
    l_url varchar2(2000) := trim(p_source_url);
    l_id  varchar2(32);
  begin
    if regexp_like(l_url, '^https://youtu\.be/', 'i') then
      l_id := regexp_substr(l_url, 'youtu\.be/([[:alnum:]_-]{11})', 1, 1, 'i', 1);
    elsif regexp_like(l_url, '^https://(www\.|m\.)?youtube\.com/watch([/?]|$)', 'i') then
      l_id := regexp_substr(l_url, '[?&]v=([[:alnum:]_-]{11})', 1, 1, 'i', 1);
    elsif regexp_like(l_url, '^https://(www\.|m\.)?youtube\.com/(shorts|embed|live)/', 'i') then
      l_id := regexp_substr(l_url, '/(shorts|embed|live)/([[:alnum:]_-]{11})', 1, 1, 'i', 2);
    end if;
    return case when regexp_like(l_id, '^[[:alnum:]_-]{11}$') then l_id end;
  end youtube_video_id;

  function session_segment_start(p_review_session_id in number) return number is
    l_start number;
  begin
    select coalesce(mo.source_start_second, o.start_second)
      into l_start
      from afma_cm_review_sessions rs
      join afma_cm_observations o on o.observation_id = rs.observation_id
      left join afma_cm_media_objects mo on mo.media_object_id = rs.media_object_id
     where rs.review_session_id = p_review_session_id;
    return l_start;
  end session_segment_start;

  function session_segment_end(p_review_session_id in number) return number is
    l_end number;
  begin
    select coalesce(mo.source_end_second, o.end_second, o.start_second + 1)
      into l_end
      from afma_cm_review_sessions rs
      join afma_cm_observations o on o.observation_id = rs.observation_id
      left join afma_cm_media_objects mo on mo.media_object_id = rs.media_object_id
     where rs.review_session_id = p_review_session_id;
    return l_end;
  end session_segment_end;

  procedure validate_session(p_review_session_id in number) is
    l_count number;
  begin
    select count(*) into l_count
      from afma_cm_review_sessions
     where review_session_id = p_review_session_id
       and session_status <> 'CLOSED';
    if l_count = 0 then
      raise_application_error(-20400, 'The Evidence Review Studio session is not available.');
    end if;
  end validate_session;

  procedure get_segment_media(
    p_review_session_id   in number,
    p_filename            out varchar2,
    p_mime_type           out varchar2,
    p_source_start_second out number,
    p_source_end_second   out number,
    p_content             out nocopy blob
  ) is
  begin
    validate_session(p_review_session_id);
    select mo.original_filename,
           mo.mime_type,
           mo.source_start_second,
           mo.source_end_second,
           mo.content_blob
      into p_filename,
           p_mime_type,
           p_source_start_second,
           p_source_end_second,
           p_content
      from afma_cm_review_sessions rs
      join afma_cm_media_objects mo on mo.media_object_id = rs.media_object_id
     where rs.review_session_id = p_review_session_id
       and mo.content_blob is not null
       and dbms_lob.getlength(mo.content_blob) > 0;
  exception
    when no_data_found then
      raise_application_error(-20408, 'The stored bounded segment is no longer available for playback.');
  end get_segment_media;

  function open_session(p_observation_id in number) return number is
    l_session_id number;
    l_submission_id number;
    l_media_object_id number;
    l_start number;
    l_end number;
    l_taxon varchar2(500);
    l_count number;
  begin
    select o.start_second, coalesce(o.end_second, o.start_second + 1),
           coalesce(t.common_name, t.scientific_name, o.ai_taxon_text, 'Unresolved taxon'),
           o.ai_count,
           (select max(vs.submission_id)
              from afma_cm_video_submissions vs
             where vs.analysis_run_id = o.analysis_run_id
               and vs.processing_status <> 'DELETED')
      into l_start, l_end, l_taxon, l_count, l_submission_id
      from afma_cm_observations o
      left join csiro_caab_taxa t on t.spcode = coalesce(o.reviewed_spcode, o.ai_spcode)
     where o.observation_id = p_observation_id
       and o.superseded_at is null;

    if l_submission_id is not null then
      select max(mo.media_object_id) keep (
               dense_rank first order by
                 case when mo.content_blob is not null and dbms_lob.getlength(mo.content_blob) > 0 then 0 else 1 end,
                 mo.source_start_second desc,
                 mo.media_object_id desc)
        into l_media_object_id
        from afma_cm_media_objects mo
       where mo.submission_id = l_submission_id
         and mo.object_key like 'ANALYSIS_SEG_%'
         and l_start >= mo.source_start_second
         and l_start < mo.source_end_second;
    end if;

    begin
      select review_session_id
        into l_session_id
        from afma_cm_review_sessions
       where observation_id = p_observation_id
         and session_status in ('OPEN','ANALYSING','PROPOSAL_READY','ERROR')
       order by updated_at desc
       fetch first 1 row only;
      update afma_cm_review_sessions
         set submission_id = l_submission_id,
             media_object_id = coalesce(l_media_object_id, media_object_id),
             updated_at = systimestamp,
             updated_by = actor_name
       where review_session_id = l_session_id;
    exception
      when no_data_found then
        insert into afma_cm_review_sessions (
          observation_id, submission_id, media_object_id
        ) values (
          p_observation_id, l_submission_id, l_media_object_id
        ) returning review_session_id into l_session_id;

        insert into afma_cm_review_messages (
          review_session_id, message_role, message_text, time_start_second, time_end_second
        ) values (
          l_session_id, 'AGENT',
          'I have opened a review of the current proposal: ' || l_taxon || ', count ' || l_count ||
          ', at ' || fmt_second(l_start) || '–' || fmt_second(l_end) || '. Tell me what appears wrong or identify useful timestamps. I can inspect the stored visual-only segment, compare the result with earlier evidence runs, search CAAB and prepare a corrected proposal. Nothing is accepted until an officer explicitly applies the proposed finding.',
          l_start, l_end
        );
    end;
    commit;
    return l_session_id;
  exception
    when no_data_found then
      raise_application_error(-20401, 'The selected current observation could not be opened for review.');
  end open_session;

  function begin_tool_run(
    p_review_session_id in number,
    p_tool_name         in varchar2,
    p_arguments_json    in clob
  ) return number is
    l_tool_run_id number;
  begin
    validate_session(p_review_session_id);
    insert into afma_cm_review_tool_runs (
      review_session_id, tool_name, arguments_json
    ) values (
      p_review_session_id, p_tool_name, p_arguments_json
    ) returning tool_run_id into l_tool_run_id;
    commit;
    return l_tool_run_id;
  end begin_tool_run;

  procedure finish_tool_run(
    p_tool_run_id     in number,
    p_result_json     in clob,
    p_evidence_run_id in number default null
  ) is
  begin
    update afma_cm_review_tool_runs
       set run_status = 'COMPLETE', result_json = p_result_json,
           evidence_run_id = p_evidence_run_id, completed_at = systimestamp
     where tool_run_id = p_tool_run_id;
    commit;
  end finish_tool_run;

  procedure fail_tool_run(p_tool_run_id in number, p_error in varchar2) is
  begin
    update afma_cm_review_tool_runs
       set run_status = 'FAILED', error_message = substr(p_error, 1, 4000), completed_at = systimestamp
     where tool_run_id = p_tool_run_id;
    commit;
  end fail_tool_run;

  procedure tool_get_review_context(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  ) is
    l_session_id number := p_param.args_json.get_number('review_session_id');
    l_tool_run_id number;
    l_result clob;
  begin
    l_tool_run_id := begin_tool_run(l_session_id, 'get_review_context', p_param.args);
    select json_object(
             'reviewSessionId' value rs.review_session_id,
             'observationId' value o.observation_id,
             'observationType' value o.observation_type,
             'currentTaxonText' value coalesce(t.common_name, t.scientific_name, o.ai_taxon_text),
             'currentSpcode' value coalesce(o.reviewed_spcode, o.ai_spcode),
             'currentCount' value coalesce(o.reviewed_count, o.ai_count),
             'eventStartSecond' value o.start_second,
             'eventEndSecond' value o.end_second,
             'segmentStartSecond' value coalesce(mo.source_start_second, o.start_second),
             'segmentEndSecond' value coalesce(mo.source_end_second, o.end_second),
             'reviewerStatus' value o.reviewer_status,
             'evidenceText' value o.evidence_text,
             'uncertainty' value o.ai_uncertainty,
             'storedSegmentAvailable' value case when mo.content_blob is not null and dbms_lob.getlength(mo.content_blob) > 0 then 'true' else 'false' end format json
             returning clob)
      into l_result
      from afma_cm_review_sessions rs
      join afma_cm_observations o on o.observation_id = rs.observation_id
      left join afma_cm_media_objects mo on mo.media_object_id = rs.media_object_id
      left join csiro_caab_taxa t on t.spcode = coalesce(o.reviewed_spcode, o.ai_spcode)
     where rs.review_session_id = l_session_id;
    finish_tool_run(l_tool_run_id, l_result);
    p_result.result := l_result;
  exception
    when others then
      if l_tool_run_id is not null then fail_tool_run(l_tool_run_id, sqlerrm); end if;
      raise;
  end tool_get_review_context;

  procedure tool_inspect_stored_segment(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  ) is
    l_session_id number := p_param.args_json.get_number('review_session_id');
    l_focus_start number := p_param.args_json.get_number('focus_start_second');
    l_focus_end number := p_param.args_json.get_number('focus_end_second');
    l_question varchar2(1000) := p_param.args_json.get_string('inspection_question');
    l_submission_id number;
    l_media_object_id number;
    l_analysis_run_id number;
    l_original_observation_id number;
    l_segment_start number;
    l_segment_end number;
    l_evidence_run_id number;
    l_new_observation_id number;
    l_tool_run_id number;
    l_instruction varchar2(1000);
    l_result clob;
  begin
    l_tool_run_id := begin_tool_run(l_session_id, 'inspect_stored_segment', p_param.args);
    select rs.submission_id, rs.media_object_id, rs.observation_id,
           o.analysis_run_id, coalesce(mo.source_start_second, o.start_second),
           coalesce(mo.source_end_second, o.end_second)
      into l_submission_id, l_media_object_id, l_original_observation_id,
           l_analysis_run_id, l_segment_start, l_segment_end
      from afma_cm_review_sessions rs
      join afma_cm_observations o on o.observation_id = rs.observation_id
      left join afma_cm_media_objects mo on mo.media_object_id = rs.media_object_id
     where rs.review_session_id = l_session_id;

    if l_media_object_id is null then
      raise_application_error(-20402, 'No stored analysis rendition is linked to this review session.');
    end if;
    if l_focus_start is null then l_focus_start := l_segment_start; end if;
    if l_focus_end is null then l_focus_end := l_segment_end; end if;
    if l_focus_start < l_segment_start or l_focus_end > l_segment_end or l_focus_end <= l_focus_start then
      raise_application_error(-20403, 'The requested inspection interval must stay inside the stored segment boundary.');
    end if;

    l_instruction := substr(
      'Evidence Review Studio inspection. Focus especially on source time ' ||
      fmt_second(l_focus_start) || '–' || fmt_second(l_focus_end) || '. ' ||
      'Treat the reviewer question as a hypothesis, not ground truth: ' || trim(l_question) || '. ' ||
      'Count only visibly completed water-to-vessel or water-to-deck landing transitions. Do not extrapolate from crew activity, pole movement, claimed catch rate, narration, title text or accumulated fish already visible on deck. Cite temporal anchors and state uncertainty.',
      1, 1000);

    update afma_cm_review_sessions
       set session_status = 'ANALYSING', updated_at = systimestamp, updated_by = actor_name
     where review_session_id = l_session_id;
    commit;

    afma_cm_evidence_api.rerun_segment(
      p_submission_id        => l_submission_id,
      p_media_object_id      => l_media_object_id,
      p_reviewer_instruction => l_instruction
    );

    select max(evidence_run_id)
      into l_evidence_run_id
      from afma_cm_evidence_runs
     where submission_id = l_submission_id
       and media_object_id = l_media_object_id
       and run_purpose = 'SEGMENT_REANALYSIS'
       and run_status = 'COMPLETE';

    select min(observation_id) keep (
             dense_rank first order by abs(start_second - l_focus_start), observation_id)
      into l_new_observation_id
      from afma_cm_observations
     where analysis_run_id = l_analysis_run_id
       and evidence_run_id = l_evidence_run_id
       and superseded_at is null;

    if l_new_observation_id is not null then
      update afma_cm_review_sessions
         set observation_id = l_new_observation_id
       where review_session_id = l_session_id;
    end if;

    select json_object(
             'evidenceRunId' value l_evidence_run_id,
             'reviewSessionId' value l_session_id,
             'focusStartSecond' value l_focus_start,
             'focusEndSecond' value l_focus_end,
             'publishedProposals' value (
               select json_arrayagg(
                        json_object(
                          'observationId' value o.observation_id,
                          'startSecond' value o.start_second,
                          'endSecond' value o.end_second,
                          'taxonText' value coalesce(t.common_name, t.scientific_name, o.ai_taxon_text),
                          'spcode' value o.ai_spcode,
                          'count' value o.ai_count,
                          'confidence' value o.ai_confidence,
                          'evidence' value o.evidence_text,
                          'uncertainty' value o.ai_uncertainty
                          returning clob)
                        returning clob)
                 from afma_cm_observations o
                 left join csiro_caab_taxa t on t.spcode = o.ai_spcode
                where o.evidence_run_id = l_evidence_run_id
                  and o.superseded_at is null
             ) format json
             returning clob)
      into l_result
      from dual;

    update afma_cm_review_sessions
       set session_status = 'OPEN', updated_at = systimestamp, updated_by = actor_name
     where review_session_id = l_session_id;
    finish_tool_run(l_tool_run_id, l_result, l_evidence_run_id);
    p_result.result := l_result;
  exception
    when others then
      update afma_cm_review_sessions
         set session_status = 'ERROR', updated_at = systimestamp, updated_by = actor_name
       where review_session_id = l_session_id;
      commit;
      if l_tool_run_id is not null then fail_tool_run(l_tool_run_id, sqlerrm); end if;
      raise;
  end tool_inspect_stored_segment;

  procedure tool_lookup_caab_candidates(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  ) is
    l_session_id number := p_param.args_json.get_number('review_session_id');
    l_query varchar2(300) := trim(p_param.args_json.get_string('query_text'));
    l_tool_run_id number;
    l_result clob;
  begin
    l_tool_run_id := begin_tool_run(l_session_id, 'lookup_caab_candidates', p_param.args);
    select json_object(
             'query' value l_query,
             'candidates' value coalesce((
               select json_arrayagg(
                        json_object(
                          'spcode' value spcode,
                          'commonName' value common_name,
                          'scientificName' value scientific_name
                          returning clob)
                        returning clob)
                 from (
                   select distinct t.spcode, t.common_name, t.scientific_name
                     from csiro_caab_taxa_active_v t
                    where lower(t.common_name) like '%' || lower(l_query) || '%'
                       or lower(t.scientific_name) like '%' || lower(l_query) || '%'
                       or t.spcode = l_query
                    order by case when lower(t.common_name) = lower(l_query) then 0 else 1 end,
                             t.common_name, t.scientific_name
                    fetch first 12 rows only
                 )
             ), to_clob('[]')) format json
             returning clob)
      into l_result
      from dual;
    finish_tool_run(l_tool_run_id, l_result);
    p_result.result := l_result;
  exception
    when others then
      if l_tool_run_id is not null then fail_tool_run(l_tool_run_id, sqlerrm); end if;
      raise;
  end tool_lookup_caab_candidates;

  procedure tool_create_corrected_proposal(
    p_param  in            apex_ai.t_tool_exec_param,
    p_result in out nocopy apex_ai.t_tool_exec_result
  ) is
    l_session_id number := p_param.args_json.get_number('review_session_id');
    l_taxon_text varchar2(500) := p_param.args_json.get_string('taxon_text');
    l_spcode varchar2(20) := p_param.args_json.get_string('spcode');
    l_count number := p_param.args_json.get_number('count');
    l_start number := p_param.args_json.get_number('start_second');
    l_end number := p_param.args_json.get_number('end_second');
    l_interaction varchar2(40) := upper(coalesce(p_param.args_json.get_string('interaction_class'), 'NOT_APPLICABLE'));
    l_confidence number := p_param.args_json.get_number('confidence');
    l_summary varchar2(4000) := p_param.args_json.get_string('evidence_summary');
    l_segment_start number;
    l_segment_end number;
    l_valid_spcode number;
    l_tool_run_id number;
    l_proposal_id number;
    l_result clob;
  begin
    l_tool_run_id := begin_tool_run(l_session_id, 'create_corrected_proposal', p_param.args);
    l_segment_start := session_segment_start(l_session_id);
    l_segment_end := session_segment_end(l_session_id);
    if l_count < 0 or l_count <> trunc(l_count) then
      raise_application_error(-20404, 'Proposal count must be a non-negative whole number.');
    end if;
    if l_start < l_segment_start or l_end > l_segment_end or l_end <= l_start then
      raise_application_error(-20405, 'Proposal evidence range must stay inside the stored segment.');
    end if;
    if trim(l_summary) is null then
      raise_application_error(-20406, 'Proposal evidence summary is required.');
    end if;
    if trim(l_spcode) is not null then
      select count(*) into l_valid_spcode from csiro_caab_taxa_active_v where spcode = trim(l_spcode);
      if l_valid_spcode = 0 then
        raise_application_error(-20407, 'Proposal CAAB SPCODE is not active.');
      end if;
    end if;

    update afma_cm_review_proposals
       set proposal_status = 'SUPERSEDED', decided_at = systimestamp, decided_by = actor_name
     where review_session_id = l_session_id
       and proposal_status = 'DRAFT';

    insert into afma_cm_review_proposals (
      review_session_id, source_tool_run_id, proposal_source, taxon_text, spcode,
      proposed_count, start_second, end_second, interaction_class, confidence,
      evidence_summary
    ) values (
      l_session_id, l_tool_run_id, 'AGENT', substr(trim(l_taxon_text),1,500), trim(l_spcode),
      l_count, l_start, l_end, l_interaction, l_confidence,
      substr(trim(l_summary),1,4000)
    ) returning review_proposal_id into l_proposal_id;

    update afma_cm_review_sessions
       set session_status = 'PROPOSAL_READY', updated_at = systimestamp, updated_by = actor_name
     where review_session_id = l_session_id;

    select json_object(
             'proposalId' value l_proposal_id,
             'status' value 'DRAFT',
             'message' value 'The corrected finding is ready for officer review. It has not changed the reviewed observation.'
             returning clob)
      into l_result from dual;
    finish_tool_run(l_tool_run_id, l_result);
    p_result.result := l_result;
  exception
    when others then
      if l_tool_run_id is not null then fail_tool_run(l_tool_run_id, sqlerrm); end if;
      raise;
  end tool_create_corrected_proposal;

  procedure send_message(
    p_review_session_id in number,
    p_message           in varchar2,
    p_time_start_second in number default null,
    p_time_end_second   in number default null
  ) is
    l_message varchar2(4000) := trim(p_message);
    l_message_id number;
    l_messages apex_ai.t_chat_messages := apex_ai.c_chat_messages;
    l_tools apex_ai.t_tools;
    l_response clob;
    l_index pls_integer := 0;
    l_segment_start number;
    l_segment_end number;
    l_system_prompt clob;
    l_error varchar2(1200);
  begin
    validate_session(p_review_session_id);
    if l_message is null then
      raise_application_error(-20408, 'Enter a question, observation or instruction for the review agent.');
    end if;
    l_segment_start := session_segment_start(p_review_session_id);
    l_segment_end := session_segment_end(p_review_session_id);
    if p_time_start_second is not null and
       (p_time_start_second < l_segment_start or
        coalesce(p_time_end_second, p_time_start_second) > l_segment_end or
        coalesce(p_time_end_second, p_time_start_second) < p_time_start_second) then
      raise_application_error(-20409, 'Marked evidence time must stay inside the displayed segment.');
    end if;

    insert into afma_cm_review_messages (
      review_session_id, message_role, message_text, time_start_second, time_end_second
    ) values (
      p_review_session_id, 'REVIEWER', l_message, p_time_start_second, p_time_end_second
    ) returning review_message_id into l_message_id;
    update afma_cm_review_sessions
       set session_status = 'ANALYSING', updated_at = systimestamp, updated_by = actor_name
     where review_session_id = p_review_session_id;
    commit;

    for m in (
      select message_role, message_text
        from afma_cm_review_messages
       where review_session_id = p_review_session_id
         and review_message_id < l_message_id
         and message_role in ('REVIEWER','AGENT')
       order by review_message_id
       fetch first 24 rows only
    ) loop
      l_index := l_index + 1;
      l_messages(l_index) := apex_ai.t_chat_message(
        chat_role => case when m.message_role = 'REVIEWER' then apex_ai.c_role_user else apex_ai.c_role_assistant end,
        message   => m.message_text
      );
    end loop;

    l_system_prompt :=
      'You are the AFMA Catch Monitor Evidence Review Agent inside Oracle APEX. ' ||
      'You collaborate with an authorised officer to investigate one proposed video-evidence event. ' ||
      'Review session id: ' || p_review_session_id || '. Stored segment boundary: ' ||
      fmt_second(l_segment_start) || '–' || fmt_second(l_segment_end) || '. ' ||
      'The footage is visual-only; do not rely on audio, narration, video titles or descriptions as evidence. ' ||
      'Treat every reviewer statement as a useful hypothesis to test, not as ground truth. ' ||
      'Never infer catch totals from crew count, fishing activity, pole movement, claimed catch rate or accumulated fish already on deck. ' ||
      'Count only visible completed water-to-vessel or water-to-deck landing transitions, distinguish new catches from accumulation/replay, and cite timestamps. ' ||
      'Use get_review_context before asserting the current state. Use inspect_stored_segment when the visual result needs reconsideration. ' ||
      'Use lookup_caab_candidates before selecting a CAAB code if identity is uncertain. ' ||
      'When evidence supports a correction, call create_corrected_proposal with a structured finding. ' ||
      'Do not claim that any proposal is accepted or a compliance finding. The officer alone accepts a proposal in the application. ' ||
      'Keep responses concise, explain uncertainty, and say what tool evidence changed your view.';

    l_tools := apex_ai.t_tools(
      apex_ai.t_tool(
        name => 'get_review_context',
        description => 'Returns the current Catch Monitor observation, stored segment boundary, existing officer status and evidence text for this review session.',
        parameters => apex_ai.t_tool_parameters(
          apex_ai.t_tool_parameter(name=>'review_session_id', description=>'Exact numeric review session id supplied in the system prompt.', data_type=>apex_ai.c_tool_param_type_number)
        ),
        callback_procedure => 'AFMA_CM_REVIEW_AGENT_API.TOOL_GET_REVIEW_CONTEXT'
      ),
      apex_ai.t_tool(
        name => 'inspect_stored_segment',
        description => 'Runs a fresh Gemini Pro visual analysis of the stored bounded segment, with special attention to a reviewer-marked interval and question. This is expensive and should be used only when visual reinspection is needed.',
        parameters => apex_ai.t_tool_parameters(
          apex_ai.t_tool_parameter(name=>'review_session_id', description=>'Exact numeric review session id.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'focus_start_second', description=>'Absolute source-video start second inside the stored segment.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'focus_end_second', description=>'Absolute source-video end second inside the stored segment.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'inspection_question', description=>'The visual question or hypothesis to test.', data_type=>apex_ai.c_tool_param_type_varchar2)
        ),
        callback_procedure => 'AFMA_CM_REVIEW_AGENT_API.TOOL_INSPECT_STORED_SEGMENT'
      ),
      apex_ai.t_tool(
        name => 'lookup_caab_candidates',
        description => 'Searches active CAAB taxa by common name, scientific name or exact SPCODE and returns candidate identities.',
        parameters => apex_ai.t_tool_parameters(
          apex_ai.t_tool_parameter(name=>'review_session_id', description=>'Exact numeric review session id.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'query_text', description=>'Species, higher taxon, common-name fragment, scientific-name fragment or SPCODE.', data_type=>apex_ai.c_tool_param_type_varchar2)
        ),
        callback_procedure => 'AFMA_CM_REVIEW_AGENT_API.TOOL_LOOKUP_CAAB_CANDIDATES'
      ),
      apex_ai.t_tool(
        name => 'create_corrected_proposal',
        description => 'Creates a structured corrected finding for officer review. It does not update or accept the official observation.',
        parameters => apex_ai.t_tool_parameters(
          apex_ai.t_tool_parameter(name=>'review_session_id', description=>'Exact numeric review session id.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'taxon_text', description=>'Supported species or higher-taxon name.', data_type=>apex_ai.c_tool_param_type_varchar2),
          apex_ai.t_tool_parameter(name=>'spcode', description=>'Active CAAB SPCODE, or omit when unresolved.', data_type=>apex_ai.c_tool_param_type_varchar2, is_required=>false),
          apex_ai.t_tool_parameter(name=>'count', description=>'Non-negative whole-number count supported by visible evidence.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'start_second', description=>'Absolute source-video evidence start second.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'end_second', description=>'Absolute source-video evidence end second.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'interaction_class', description=>'NOT_APPLICABLE, SIGHTING, POSSIBLE_INTERACTION, CONFIRMED_INTERACTION or INCONCLUSIVE.', data_type=>apex_ai.c_tool_param_type_varchar2),
          apex_ai.t_tool_parameter(name=>'confidence', description=>'Confidence from 0 to 1.', data_type=>apex_ai.c_tool_param_type_number),
          apex_ai.t_tool_parameter(name=>'evidence_summary', description=>'Short evidence explanation with temporal anchors, exclusions and uncertainty.', data_type=>apex_ai.c_tool_param_type_varchar2)
        ),
        callback_procedure => 'AFMA_CM_REVIEW_AGENT_API.TOOL_CREATE_CORRECTED_PROPOSAL'
      )
    );

    l_response := apex_ai.chat(
      p_prompt                => l_message ||
                                 case when p_time_start_second is not null then chr(10) ||
                                   'Reviewer-marked source interval: ' || fmt_second(p_time_start_second) || '–' ||
                                   fmt_second(coalesce(p_time_end_second, p_time_start_second)) || '.' end,
      p_system_prompt         => l_system_prompt,
      p_service_static_id     => 'google_gemini_2_5_pro',
      p_temperature           => 0.1,
      p_messages              => l_messages,
      p_tools                 => l_tools,
      p_max_tool_roundtrips   => 4
    );

    if l_response is null then
      l_response := to_clob('The review agent returned no text response.');
    end if;

    insert into afma_cm_review_messages (
      review_session_id, message_role, message_text
    ) values (
      p_review_session_id, 'AGENT', l_response
    );
    update afma_cm_review_sessions
       set session_status = case when exists (
             select 1 from afma_cm_review_proposals
              where review_session_id = p_review_session_id and proposal_status = 'DRAFT'
           ) then 'PROPOSAL_READY' else 'OPEN' end,
           updated_at = systimestamp, updated_by = actor_name
     where review_session_id = p_review_session_id;
    commit;
  exception
    when others then
      l_error := substr(sqlerrm,1,1200);
      insert into afma_cm_review_messages (
        review_session_id, message_role, message_text
      ) values (
        p_review_session_id, 'AGENT',
        'I could not complete that investigation. The existing result and prior review history remain unchanged. Technical detail: ' || l_error
      );
      update afma_cm_review_sessions
         set session_status = 'ERROR', updated_at = systimestamp, updated_by = actor_name
       where review_session_id = p_review_session_id;
      commit;
  end send_message;

  procedure accept_proposal(
    p_review_session_id  in number,
    p_review_proposal_id in number default null,
    p_taxon_text         in varchar2 default null,
    p_spcode             in varchar2 default null,
    p_count              in number,
    p_start_second       in number,
    p_end_second         in number,
    p_interaction_class  in varchar2 default 'NOT_APPLICABLE',
    p_reviewer_note      in varchar2 default null
  ) is
    l_observation_id number;
    l_trip_id number;
    l_proposal_id number := p_review_proposal_id;
    l_spcode varchar2(20) := trim(p_spcode);
    l_valid number;
    l_source varchar2(30) := 'AGENT';
  begin
    validate_session(p_review_session_id);
    if p_count < 0 or p_count <> trunc(p_count) then
      raise_application_error(-20410, 'Officer decision count must be a non-negative whole number.');
    end if;
    if p_start_second < session_segment_start(p_review_session_id) or
       p_end_second > session_segment_end(p_review_session_id) or
       p_end_second <= p_start_second then
      raise_application_error(-20411, 'Officer evidence range must stay inside the displayed segment.');
    end if;
    if l_spcode is not null then
      select count(*) into l_valid from csiro_caab_taxa_active_v where spcode = l_spcode;
      if l_valid = 0 then raise_application_error(-20412, 'Enter an active CAAB SPCODE or leave it unresolved.'); end if;
    end if;

    select rs.observation_id, ar.trip_id
      into l_observation_id, l_trip_id
      from afma_cm_review_sessions rs
      join afma_cm_observations o on o.observation_id = rs.observation_id
      join afma_cm_analysis_runs ar on ar.analysis_run_id = o.analysis_run_id
     where rs.review_session_id = p_review_session_id;

    if l_proposal_id is null then
      l_source := 'OFFICER_EDIT';
      insert into afma_cm_review_proposals (
        review_session_id, proposal_source, taxon_text, spcode, proposed_count,
        start_second, end_second, interaction_class, evidence_summary
      ) values (
        p_review_session_id, l_source, substr(trim(p_taxon_text),1,500), l_spcode, p_count,
        p_start_second, p_end_second, upper(coalesce(trim(p_interaction_class),'NOT_APPLICABLE')),
        substr(coalesce(trim(p_reviewer_note),'Officer edited the structured finding in the Evidence Review Studio.'),1,4000)
      ) returning review_proposal_id into l_proposal_id;
    else
      update afma_cm_review_proposals
         set taxon_text = substr(trim(p_taxon_text),1,500), spcode = l_spcode,
             proposed_count = p_count, start_second = p_start_second, end_second = p_end_second,
             interaction_class = upper(coalesce(trim(p_interaction_class),'NOT_APPLICABLE')),
             evidence_summary = case when trim(p_reviewer_note) is not null then substr(trim(p_reviewer_note),1,4000) else evidence_summary end
       where review_proposal_id = l_proposal_id
         and review_session_id = p_review_session_id
         and proposal_status = 'DRAFT';
      if sql%rowcount = 0 then raise_application_error(-20413, 'The selected draft proposal is no longer available.'); end if;
    end if;

    update afma_cm_observations
       set start_second = p_start_second,
           end_second = p_end_second
     where observation_id = l_observation_id;

    afma_cm_api.review_observation(
      p_trip_id                    => l_trip_id,
      p_observation_id             => l_observation_id,
      p_reviewer_status            => 'CORRECTED',
      p_reviewed_spcode            => l_spcode,
      p_reviewed_count             => p_count,
      p_reviewed_interaction_class => upper(coalesce(trim(p_interaction_class),'NOT_APPLICABLE')),
      p_reviewer_notes             => substr('Evidence Review Studio session #' || p_review_session_id ||
                                               ', proposal #' || l_proposal_id || '. ' || trim(p_reviewer_note),1,2000)
    );

    update afma_cm_review_proposals
       set proposal_status = case when review_proposal_id = l_proposal_id then 'ACCEPTED' else 'SUPERSEDED' end,
           decided_at = systimestamp, decided_by = actor_name
     where review_session_id = p_review_session_id
       and proposal_status = 'DRAFT';
    update afma_cm_review_sessions
       set session_status = 'ACCEPTED', accepted_at = systimestamp, accepted_by = actor_name,
           updated_at = systimestamp, updated_by = actor_name
     where review_session_id = p_review_session_id;
    insert into afma_cm_review_messages (
      review_session_id, message_role, message_text, time_start_second, time_end_second
    ) values (
      p_review_session_id, 'SYSTEM',
      'Officer accepted corrected finding proposal #' || l_proposal_id || '. Species/CAAB, count, classification and evidence range were written to observation #' || l_observation_id || '.',
      p_start_second, p_end_second
    );
    commit;
  end accept_proposal;

  procedure escalate_session(
    p_review_session_id in number,
    p_reviewer_note     in varchar2 default null
  ) is
    l_observation_id number;
    l_trip_id number;
  begin
    validate_session(p_review_session_id);
    select rs.observation_id, ar.trip_id
      into l_observation_id, l_trip_id
      from afma_cm_review_sessions rs
      join afma_cm_observations o on o.observation_id = rs.observation_id
      join afma_cm_analysis_runs ar on ar.analysis_run_id = o.analysis_run_id
     where rs.review_session_id = p_review_session_id;
    afma_cm_api.review_observation(
      p_trip_id => l_trip_id,
      p_observation_id => l_observation_id,
      p_reviewer_status => 'ESCALATED',
      p_reviewer_notes => substr('Evidence Review Studio session #' || p_review_session_id || '. ' || trim(p_reviewer_note),1,2000)
    );
    update afma_cm_review_sessions
       set session_status = 'CLOSED', updated_at = systimestamp, updated_by = actor_name
     where review_session_id = p_review_session_id;
    commit;
  end escalate_session;

  function session_html(p_review_session_id in number) return clob is
    l_html clob;
    l_status varchar2(30);
    l_observation_id number;
    l_segment_start number;
    l_segment_end number;
    l_event_start number;
    l_event_end number;
    l_taxon_text varchar2(500);
    l_spcode varchar2(20);
    l_count number;
    l_interaction varchar2(40);
    l_source_url varchar2(2000);
    l_video_id varchar2(32);
    l_proposal_id number;
    l_proposal_source varchar2(30);
    l_summary varchar2(4000);
    l_confidence number;
    l_segment_available_yn varchar2(1);
  begin
    validate_session(p_review_session_id);
    select rs.session_status, o.observation_id,
           coalesce(mo.source_start_second,o.start_second), coalesce(mo.source_end_second,o.end_second),
           o.start_second, coalesce(o.end_second,o.start_second+1),
           coalesce(t.common_name,t.scientific_name,o.ai_taxon_text,'Unresolved taxon'),
           coalesce(o.reviewed_spcode,o.ai_spcode), coalesce(o.reviewed_count,o.ai_count),
           coalesce(o.reviewed_interaction_class,o.ai_interaction_class,'NOT_APPLICABLE'),
           ma.source_record_url,
           case when mo.content_blob is not null and dbms_lob.getlength(mo.content_blob) > 0 then 'Y' else 'N' end
      into l_status, l_observation_id, l_segment_start, l_segment_end,
           l_event_start, l_event_end, l_taxon_text, l_spcode, l_count,
           l_interaction, l_source_url, l_segment_available_yn
      from afma_cm_review_sessions rs
      join afma_cm_observations o on o.observation_id = rs.observation_id
      join afma_cm_analysis_runs ar on ar.analysis_run_id = o.analysis_run_id
      join afma_cm_media_assets ma on ma.media_asset_id = ar.media_asset_id
      left join afma_cm_media_objects mo on mo.media_object_id = rs.media_object_id
      left join csiro_caab_taxa t on t.spcode = coalesce(o.reviewed_spcode,o.ai_spcode)
     where rs.review_session_id = p_review_session_id;

    begin
      select review_proposal_id, proposal_source, coalesce(taxon_text,l_taxon_text),
             coalesce(spcode,l_spcode), proposed_count, start_second, end_second,
             interaction_class, evidence_summary, confidence
        into l_proposal_id, l_proposal_source, l_taxon_text, l_spcode, l_count,
             l_event_start, l_event_end, l_interaction, l_summary, l_confidence
        from afma_cm_review_proposals
       where review_session_id = p_review_session_id
         and proposal_status = 'DRAFT'
       order by review_proposal_id desc
       fetch first 1 row only;
    exception
      when no_data_found then
        l_proposal_id := null;
        l_proposal_source := 'CURRENT_RESULT';
        l_summary := 'No corrected proposal has been created yet. The visible fields show the current observation and may be edited by the officer.';
    end;

    l_video_id := youtube_video_id(l_source_url);
    dbms_lob.createtemporary(l_html, true);
    add_line(l_html, '<div class="cm-studio hub-ai-assistant-dialog" data-review-session-id="' || p_review_session_id || '" data-segment-start="' || l_segment_start || '" data-segment-end="' || l_segment_end || '" data-event-start="' || l_event_start || '" data-event-end="' || l_event_end || '" data-segment-available="' || l_segment_available_yn || '">');
    add_line(l_html, '<header class="cm-studio__head"><div><span class="cm-kicker">Persistent evidence review session #' || p_review_session_id || '</span><h2>Investigate event ' || h(fmt_second(l_event_start)) || '–' || h(fmt_second(l_event_end)) || '</h2><p>Discuss the evidence, reprocess the stored visual-only segment and accept only the finding you support.</p></div><span class="cm-badge cm-badge-neutral">' || h(l_status) || '</span></header>');
    add_line(l_html, '<div class="cm-studio__grid"><section class="cm-studio__video"><h3>Segment playback</h3>');
    add_line(l_html, '<div id="cmStudioMedia" class="cm-studio__media" aria-live="polite"><div class="cm-studio__video-loading"><span class="cm-spinner" aria-hidden="true"></span><strong>Loading stored segment…</strong></div></div>');
    if l_video_id is not null then
      add_line(l_html, '<div id="cmStudioSourceFallback" hidden><iframe id="cmStudioSourcePlayer" class="cm-video" title="Bounded source preview" data-src="https://www.youtube-nocookie.com/embed/' || a(l_video_id) || '?rel=0&amp;enablejsapi=1&amp;start=' || trunc(l_segment_start) || '&amp;end=' || ceil(l_segment_end) || '" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe><p class="cm-footnote">Stored-segment playback was unavailable, so this is a time-bounded preview of the public source.</p></div>');
    else
      add_line(l_html, '<div id="cmStudioSourceFallback" class="cm-studio__video-placeholder" hidden><strong>Stored segment ' || h(fmt_second(l_segment_start)) || '–' || h(fmt_second(l_segment_end)) || '</strong><p>Playback is unavailable. The retained rendition may still be used by the governed analysis tool.</p></div>');
    end if;
    add_line(l_html, '<p id="cmStudioPlaybackNote" class="cm-footnote">This player loads the exact stored visual-only analysis rendition for source time ' || h(fmt_second(l_segment_start)) || '–' || h(fmt_second(l_segment_end)) || '.</p>');
    add_line(l_html, '<div class="cm-studio__transport"><button type="button" class="cm-btn cm-studio-seek" data-second="' || l_segment_start || '">Start of segment</button><button type="button" class="cm-btn cm-studio-step" data-delta="-5">−5s</button><button type="button" class="cm-btn cm-studio-step" data-delta="5">+5s</button><span id="cmStudioTime">' || h(fmt_second(l_segment_start)) || '</span></div>');
    add_line(l_html, '<div class="cm-studio__range"><div><span class="cm-kicker">Marked evidence range</span><strong id="cmStudioRangeLabel">' || h(fmt_second(l_event_start)) || '–' || h(fmt_second(l_event_end)) || '</strong></div><div><button type="button" class="cm-btn" id="cmStudioMarkStartButton">Mark range start</button><button type="button" class="cm-btn" id="cmStudioMarkEndButton">Mark range end</button><button type="button" class="cm-btn" id="cmStudioResetRange">Reset to event</button></div><input id="cmStudioMarkStart" type="hidden" value="' || l_event_start || '"><input id="cmStudioMarkEnd" type="hidden" value="' || l_event_end || '"></div>');
    add_line(l_html, '<details class="cm-tool-ledger"><summary>Agent tool activity</summary><div>');
    for tr in (
      select tool_name, run_status, started_at, completed_at, evidence_run_id, error_message
        from afma_cm_review_tool_runs
       where review_session_id = p_review_session_id
       order by tool_run_id
    ) loop
      add_line(l_html, '<article><strong>' || h(replace(initcap(tr.tool_name),'_',' ')) || '</strong><span class="cm-badge ' || case when tr.run_status='COMPLETE' then 'cm-badge-ok' when tr.run_status='FAILED' then 'cm-badge-risk' else 'cm-badge-warn' end || '">' || h(tr.run_status) || '</span><small>' || h(to_char(tr.started_at,'DD Mon HH24:MI:SS')) || case when tr.evidence_run_id is not null then ' · evidence run #' || tr.evidence_run_id end || case when tr.error_message is not null then ' · ' || h(tr.error_message) end || '</small></article>');
    end loop;
    add_line(l_html, '</div></details></section>');

    add_line(l_html, '<section class="cm-studio__conversation hub-ai-assistant-body"><div class="cm-chat-title"><div><h3>Evidence review chat</h3><p>Ask questions, challenge a count or species, and direct the agent to visible evidence.</p></div><span class="cm-badge cm-badge-neutral">Gemini 2.5 Pro</span></div><div class="cm-chat-log hub-ai-assistant-output" id="cmChatLog" role="log" aria-live="polite" aria-label="Evidence review conversation">');
    for m in (
      select message_role, message_text, time_start_second, time_end_second, created_at, created_by
        from afma_cm_review_messages
       where review_session_id = p_review_session_id
       order by review_message_id
    ) loop
      add_line(l_html, '<article class="cm-chat cm-chat--' || lower(m.message_role) || ' hub-ai-message hub-ai-message--' || case when m.message_role='REVIEWER' then 'user' when m.message_role='AGENT' then 'assistant' else 'system' end || '"><div class="cm-chat__meta"><strong>' || h(case m.message_role when 'REVIEWER' then 'Officer' when 'AGENT' then 'Catch Monitor agent' else initcap(m.message_role) end) || '</strong><small>' || h(to_char(m.created_at,'DD Mon HH24:MI:SS')) || '</small></div><p>' || replace(h(dbms_lob.substr(m.message_text,4000,1)),chr(10),'<br>') || '</p>' || case when m.time_start_second is not null then '<button type="button" class="cm-timecode cm-studio-seek" data-second="' || m.time_start_second || '"><span aria-hidden="true">▶</span> ' || h(fmt_second(m.time_start_second)) || case when m.time_end_second is not null and m.time_end_second<>m.time_start_second then '–' || h(fmt_second(m.time_end_second)) end || '</button>' end || '</article>');
    end loop;
    add_line(l_html, '</div><footer class="cm-chat-composer hub-ai-assistant-composer"><div id="cmStudioAttachmentStrip" class="cm-chat-attachments" hidden><span>Attached to this message</span><button type="button" class="cm-timecode" id="cmStudioAttachedRange"></button><button type="button" class="cm-chat-attachment-remove" id="cmStudioRemoveAttachment" title="Remove video range" aria-label="Remove attached video range">×</button></div><div class="cm-chat-prompt-shell"><textarea id="cmStudioMessage" rows="3" maxlength="4000" aria-label="Message Catch Monitor agent" placeholder="Ask about this segment…"></textarea><button type="button" class="cm-chat-send" id="cmStudioSend" title="Send" aria-label="Send"><span class="fa fa-arrow-up" aria-hidden="true"></span><span class="cm-spinner" aria-hidden="true"></span></button></div><div class="cm-chat-composer-bar"><button type="button" class="cm-chat-attach" id="cmStudioAttachRange"><span class="fa fa-paperclip" aria-hidden="true"></span> Attach marked video range</button><span id="cmStudioSendStatus" class="cm-chat-status" role="status" aria-live="polite">Enter sends · Shift+Enter adds a line</span></div></footer></section></div>');

    add_line(l_html, '<section class="cm-proposal" data-proposal-id="' || coalesce(to_char(l_proposal_id),'') || '"><div class="cm-proposal__head"><div><span class="cm-badge ' || case when l_proposal_id is not null then 'cm-badge-warn' else 'cm-badge-neutral' end || '">' || h(case when l_proposal_id is not null then 'Agent proposal' else 'Current result / officer edit' end) || '</span><h3>Structured corrected finding</h3></div><p>' || h(l_summary) || '</p></div><div class="cm-proposal__fields"><label>Species or taxon<input id="cmProposalTaxon" value="' || a(l_taxon_text) || '"></label><label>CAAB SPCODE<input id="cmProposalSpcode" value="' || a(l_spcode) || '" placeholder="Blank if unresolved"></label><label>Count<input id="cmProposalCount" type="number" min="0" step="1" value="' || l_count || '"></label><label>Start second<input id="cmProposalStart" type="number" min="' || l_segment_start || '" max="' || l_segment_end || '" step="0.1" value="' || l_event_start || '"></label><label>End second<input id="cmProposalEnd" type="number" min="' || l_segment_start || '" max="' || l_segment_end || '" step="0.1" value="' || l_event_end || '"></label><label>Interaction<select id="cmProposalInteraction">');
    for c in (
      select 'NOT_APPLICABLE' v, 'Not applicable' d, 1 n from dual union all
      select 'SIGHTING','Wildlife sighting',2 from dual union all
      select 'POSSIBLE_INTERACTION','Possible interaction',3 from dual union all
      select 'CONFIRMED_INTERACTION','Confirmed interaction',4 from dual union all
      select 'INCONCLUSIVE','Inconclusive',5 from dual order by n
    ) loop
      add_line(l_html, '<option value="' || c.v || '"' || case when c.v=l_interaction then ' selected' end || '>' || c.d || '</option>');
    end loop;
    add_line(l_html, '</select></label></div><label>Officer decision note<textarea id="cmProposalNote" maxlength="2000" placeholder="Record why this is the supported final finding."></textarea></label><div class="cm-proposal__actions"><button type="button" class="cm-btn" id="cmStudioKeep">Keep current result</button><button type="button" class="cm-btn cm-btn-danger" id="cmStudioEscalate">Escalate</button><button type="button" class="cm-btn cm-btn-primary" id="cmStudioAccept">' || case when l_proposal_id is not null then 'Accept corrected finding' else 'Save officer decision' end || '</button></div></section></div>');
    return l_html;
  end session_html;
end afma_cm_review_agent_api;
/

comment on table afma_cm_review_sessions is 'Persistent officer/agent evidence-review sessions. The database owns durable conversation context across APEX sessions.';
comment on table afma_cm_review_messages is 'Auditable reviewer, agent, system and tool-summary messages with optional source-video time anchors.';
comment on table afma_cm_review_tool_runs is 'Auditable APEX AI Agent tool invocations, arguments, outcomes and linked video evidence runs.';
comment on table afma_cm_review_proposals is 'Structured corrected findings proposed by the agent or edited by an officer; only explicit officer acceptance updates an observation.';

prompt AFMA 119 complete
