set define off

-- Execution authority: AFMA parsing schema owner through the verified AFMA APEX SQL Commands session.
-- Target: AIDEMODB workspace/schema AFMA; records controlled multimodal model trials without publishing observations.
prompt AFMA 135 - Create Catch Monitor video AI trial API

declare
  l_count number;
begin
  select count(*)
    into l_count
    from user_tables
   where table_name = 'AFMA_CM_AI_TRIALS';

  if l_count = 0 then
    execute immediate q'[
      create table afma_cm_ai_trials (
        trial_id               number generated by default on null as identity,
        trip_id                number not null,
        media_asset_id         number not null,
        source_file_name       varchar2(500 char) not null,
        source_offset_seconds  number default 0 not null,
        clip_duration_seconds  number,
        source_bytes           number,
        service_static_id      varchar2(255 char) not null,
        model_name             varchar2(255 char) not null,
        prompt_version         varchar2(100 char) not null,
        run_status             varchar2(30 char) default 'RUNNING' not null,
        response_json          clob,
        error_text             varchar2(4000 char),
        started_at             timestamp with local time zone default systimestamp not null,
        completed_at           timestamp with local time zone,
        created_by             varchar2(255 char) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
        constraint afma_cm_ai_trials_pk primary key (trial_id),
        constraint afma_cm_ai_trials_fk_trip foreign key (trip_id) references afma_cm_trips (trip_id),
        constraint afma_cm_ai_trials_fk_media foreign key (media_asset_id) references afma_cm_media_assets (media_asset_id),
        constraint afma_cm_ai_trials_ck_status check (run_status in ('RUNNING','COMPLETE','FAILED'))
      )
    ]';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_AI_TRIALS'
     and column_name = 'VALIDATION_STATUS';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_ai_trials add validation_status varchar2(30 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_AI_TRIALS'
     and column_name = 'VALIDATION_ISSUES';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_ai_trials add validation_issues varchar2(4000 char)';
  end if;

  select count(*) into l_count
    from user_tab_columns
   where table_name = 'AFMA_CM_AI_TRIALS'
     and column_name = 'TRANSCRIPT_CONTEXT';
  if l_count = 0 then
    execute immediate 'alter table afma_cm_ai_trials add transcript_context clob';
  end if;
end;
/

create or replace package afma_cm_video_ai_api authid definer as
  function run_trial(
    p_trip_ref               in varchar2,
    p_source_file_name       in varchar2,
    p_source_offset_seconds  in number,
    p_clip_duration_seconds  in number,
    p_service_static_id      in varchar2 default 'google_gemini_2_5_pro',
    p_model_name             in varchar2 default 'google.gemini-2.5-pro',
    p_prompt_version         in varchar2 default 'west-moore-caab-events-v1',
    p_transcript_context     in clob default null
  ) return number;
end afma_cm_video_ai_api;
/

create or replace package body afma_cm_video_ai_api as
  procedure validate_response(
    p_response          in clob,
    p_clip_duration     in number,
    p_require_unit_rows in boolean,
    p_status            out varchar2,
    p_issues            out varchar2
  ) is
    l_root          json_object_t;
    l_events        json_array_t;
    l_summaries     json_array_t;
    l_event         json_object_t;
    l_summary       json_object_t;
    l_event_total   number := 0;
    l_summary_total number := 0;
    l_declared      number;
    l_start         number;
    l_end           number;
    l_count         number;
    l_spcode        varchar2(20);
    l_exists        number;
    l_issues        varchar2(4000);

    procedure issue(p_text in varchar2) is
    begin
      l_issues := substr(l_issues || case when l_issues is null then null else '; ' end || p_text, 1, 4000);
    end issue;
  begin
    l_root := json_object_t.parse(p_response);
    if not l_root.has('events') or not l_root.has('unique_catch_total') or not l_root.has('species_summary') then
      issue('Required event or summary members are missing');
    else
      l_events := l_root.get_array('events');
      l_declared := l_root.get_number('unique_catch_total');
      for i in 0 .. l_events.get_size - 1 loop
        l_event := treat(l_events.get(i) as json_object_t);
        l_start := l_event.get_number('clip_start_second');
        l_end := l_event.get_number('clip_end_second');
        l_count := l_event.get_number('count');
        l_spcode := trim(l_event.get_string('caab_spcode'));

        if l_start < 0 or l_end < l_start or l_end > p_clip_duration then
          issue('Event ' || to_char(i + 1) || ' has timestamps outside the clip');
        end if;
        if l_count < 1 or trunc(l_count) <> l_count then
          issue('Event ' || to_char(i + 1) || ' has a non-positive or fractional count');
        elsif p_require_unit_rows and l_count <> 1 then
          issue('Event ' || to_char(i + 1) || ' must represent exactly one individual');
        end if;
        l_event_total := l_event_total + l_count;

        if l_spcode is not null then
          select count(*) into l_exists
            from csiro_caab_taxa_active_v
           where spcode = l_spcode;
          if l_exists = 0 then
            issue('Event ' || to_char(i + 1) || ' has an unknown or inactive CAAB SPCODE');
          end if;
        end if;
      end loop;

      if l_event_total <> l_declared then
        issue('Event counts do not equal unique_catch_total');
      end if;

      l_summaries := l_root.get_array('species_summary');
      for i in 0 .. l_summaries.get_size - 1 loop
        l_summary := treat(l_summaries.get(i) as json_object_t);
        l_summary_total := l_summary_total + l_summary.get_number('count');
      end loop;
      if l_summary_total <> l_declared then
        issue('Species summary does not equal unique_catch_total');
      end if;
    end if;

    p_issues := l_issues;
    p_status := case when l_issues is null then 'PASS' else 'REJECTED' end;
  exception
    when others then
      p_status := 'REJECTED';
      p_issues := substr('Response validation failed: ' || sqlerrm, 1, 4000);
  end validate_response;

  function run_trial(
    p_trip_ref               in varchar2,
    p_source_file_name       in varchar2,
    p_source_offset_seconds  in number,
    p_clip_duration_seconds  in number,
    p_service_static_id      in varchar2 default 'google_gemini_2_5_pro',
    p_model_name             in varchar2 default 'google.gemini-2.5-pro',
    p_prompt_version         in varchar2 default 'west-moore-caab-events-v1',
    p_transcript_context     in clob default null
  ) return number is
    l_trip_id       number;
    l_media_id      number;
    l_trial_id      number;
    l_video         blob;
    l_mime_type     varchar2(255);
    l_response      clob;
    l_error         varchar2(4000);
    l_validation_status varchar2(30);
    l_validation_issues varchar2(4000);
    l_response_excerpt varchar2(32767);
    l_attachments   apex_ai.t_attachments := apex_ai.t_attachments();
    l_schema        clob := q'~{
      "type": "object",
      "properties": {
        "clip_assessment": {"type": "string"},
        "events": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "clip_start_second": {"type": "number"},
              "clip_end_second": {"type": "number"},
              "source_start_second": {"type": "number"},
              "source_end_second": {"type": "number"},
              "event_type": {"type": "string", "enum": ["CATCH", "WILDLIFE"]},
              "common_name": {"type": "string"},
              "scientific_name": {"type": "string"},
              "caab_spcode": {"type": "string"},
              "count": {"type": "integer"},
              "confidence": {"type": "number"},
              "spoken_narration_used": {"type": "boolean"},
              "evidence": {"type": "string"},
              "uncertainty": {"type": "string"}
            },
            "required": ["clip_start_second", "clip_end_second", "source_start_second", "source_end_second", "event_type", "common_name", "scientific_name", "caab_spcode", "count", "confidence", "spoken_narration_used", "evidence", "uncertainty"],
            "additionalProperties": false
          }
        },
        "unique_catch_total": {"type": "integer"},
        "species_summary": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "common_name": {"type": "string"},
              "caab_spcode": {"type": "string"},
              "count": {"type": "integer"}
            },
            "required": ["common_name", "caab_spcode", "count"],
            "additionalProperties": false
          }
        },
        "limitations": {"type": "array", "items": {"type": "string"}}
      },
      "required": ["clip_assessment", "events", "unique_catch_total", "species_summary", "limitations"],
      "additionalProperties": false
    }~';
    l_prompt clob;
    l_system_prompt clob;
  begin
    select t.trip_id, m.media_asset_id
      into l_trip_id, l_media_id
      from afma_cm_trips t
      join afma_cm_media_assets m
        on m.trip_id = t.trip_id
       and m.asset_role = 'SOURCE_VIDEO'
     where t.trip_ref = p_trip_ref;

    select file_content, mime_type
      into l_video, l_mime_type
      from apex_application_static_files
     where application_id = 101
       and file_name = p_source_file_name;

    insert into afma_cm_ai_trials (
      trip_id, media_asset_id, source_file_name, source_offset_seconds,
      clip_duration_seconds, source_bytes, service_static_id, model_name,
      prompt_version, transcript_context, run_status
    ) values (
      l_trip_id, l_media_id, p_source_file_name, p_source_offset_seconds,
      p_clip_duration_seconds, dbms_lob.getlength(l_video), p_service_static_id,
      p_model_name, p_prompt_version, p_transcript_context, 'RUNNING'
    ) returning trial_id into l_trial_id;

    l_attachments.extend;
    l_attachments(1) := apex_ai.t_attachment(
      mime_type    => l_mime_type,
      content_blob => l_video,
      file_name    => substr(p_source_file_name, instr(p_source_file_name, '/', -1) + 1),
      detail_level => apex_ai.c_detail_level_high
    );

    if p_prompt_version in ('west-moore-caab-events-v2', 'west-moore-caab-events-v3') then
      l_system_prompt :=
        'You are an evidence-first fisheries video analyst. Analyse only the attached clip. ' ||
        'Your first duty is unique-individual counting: a fight, landing, close-up and later held display of the same fish are one event. ' ||
        'Never turn a replay, recap, title sequence, Coming Up preview or spoken reference to an off-screen fish into a catch event. ' ||
        'Obey temporal bounds and arithmetic exactly. When evidence is ambiguous, return Unresolved instead of guessing.';

      l_prompt :=
        'The attached clip is exactly ' || to_char(p_clip_duration_seconds) || ' seconds long. Valid clip times are 0 through ' || to_char(p_clip_duration_seconds) ||
        ', and clip time 0 corresponds to original source second ' || to_char(p_source_offset_seconds) || '. ' ||
        'Return one CATCH row for each unique fish that is visibly landed or clearly displayed as the result of a fishing event. Every CATCH row must have count 1. ' ||
        'If two fish are visible together in a double hook-up, return two rows (count 1 each); their time windows may overlap. ' ||
        'Do not create a new row when either fish is held up again moments later. Ignore preview/teaser/recap footage, especially any segment labelled Coming Up, even if it shows another species. ' ||
        'Do not create an event from narration alone. Use spoken narration only to support a visibly present fish. If a speaker corrects an earlier species name, use the final explicit correction and mention the correction in evidence. ' ||
        'Also record a WILDLIFE row only for a genuinely visible animal, and do not invent physical interaction. ' ||
        'Constrain fish identities to: Common Coral Trout (Plectropomus leopardus, 37311078); Chinamanfish (Symphorus nematophorus, 37346017); ' ||
        'Red Emperor (Lutjanus sebae, 37346004); Spanish Mackerel (Scomberomorus commerson, 37441007). ' ||
        'If identity is not supported, use common_name "Unresolved", scientific_name "", and caab_spcode "". ' ||
        'All clip timestamps must satisfy 0 <= start <= end <= ' || to_char(p_clip_duration_seconds) || '. Add ' || to_char(p_source_offset_seconds) || ' exactly to obtain source times. ' ||
        'unique_catch_total must equal the sum of CATCH counts, and species_summary counts must sum to that same total. ' ||
        'Confidence must be between 0 and 0.98; reserve values above 0.9 for clear visual evidence plus consistent narration. ' ||
        'Before returning JSON, silently check bounds, deduplication and arithmetic. ' ||
        case when p_transcript_context is not null then
          'An independently generated, time-coded transcript follows. It is supporting evidence only and may contain ASR errors. ' ||
          'Read the full correction/banter sequence rather than treating one negated phrase as final. Transcript: ' || p_transcript_context || ' '
        end ||
        'Do not infer legal size, measured length, exact weight, final retention/discard state, quota or compliance. Return only JSON matching the supplied schema.';
    else
      l_system_prompt := 'You are an evidence-first fisheries video analyst. Separate observations from inferences and never fabricate unseen events.';
      l_prompt :=
        'Analyse this ' || to_char(p_clip_duration_seconds) || '-second excerpt from an Australian charter/recreational line-fishing video. ' ||
        'Clip time 00:00 corresponds to original source second ' || to_char(p_source_offset_seconds) || '. ' ||
        'Identify every distinct fish landing or clear on-camera display as a separate CATCH event. Count each unique fish once even if it is shown again, and do not count unresolved hook-ups without a fish visible. ' ||
        'Also record any WILDLIFE event, but do not invent an interaction. Use both visible features and spoken narration; state when narration influenced identity. ' ||
        'Constrain fish identities to this CAAB shortlist unless the evidence is insufficient: Common Coral Trout (Plectropomus leopardus, 37311078); ' ||
        'Chinamanfish (Symphorus nematophorus, 37346017); Red Emperor (Lutjanus sebae, 37346004); Spanish Mackerel (Scomberomorus commerson, 37441007). ' ||
        'If uncertain, use common_name "Unresolved", scientific_name "", and caab_spcode "". ' ||
        'Confidence must be from 0 to 1. Timestamps may be approximate but must be ordered and within the clip. ' ||
        'Do not infer legal size, measured length, exact weight, final retention/discard state, quota or compliance. Return only JSON matching the supplied schema.';
    end if;

    l_response := apex_ai.generate(
      p_prompt               => l_prompt,
      p_system_prompt        => l_system_prompt,
      p_service_static_id    => p_service_static_id,
      p_temperature          => 0,
      p_attachments          => l_attachments,
      p_response_json_schema => l_schema
    );

    validate_response(
      p_response          => l_response,
      p_clip_duration     => p_clip_duration_seconds,
      p_require_unit_rows => p_prompt_version in ('west-moore-caab-events-v2', 'west-moore-caab-events-v3'),
      p_status            => l_validation_status,
      p_issues            => l_validation_issues
    );

    l_response_excerpt := lower(dbms_lob.substr(l_response, 32767, 1));
    if regexp_like(l_response_excerpt, 'legal size|quota|exact weight|released at|fish is released|catch and release') then
      l_validation_status := 'REJECTED';
      l_validation_issues := substr(
        l_validation_issues || case when l_validation_issues is null then null else '; ' end ||
        'Response contains an out-of-scope size, quota, weight or disposition claim',
        1, 4000
      );
    elsif l_validation_status = 'PASS'
      and lower(p_model_name) like '%flash%'
      and regexp_like(l_response_excerpt, 'conflict|contradict|misidentif|corrects|corrected|not a chinaman')
    then
      l_validation_status := 'NEEDS_ADJUDICATION';
      l_validation_issues := 'Species or narration contradiction requires Pro/transcript adjudication';
    end if;

    update afma_cm_ai_trials
       set run_status = 'COMPLETE',
           response_json = l_response,
           validation_status = l_validation_status,
           validation_issues = l_validation_issues,
           completed_at = systimestamp
     where trial_id = l_trial_id;
    commit;
    return l_trial_id;
  exception
    when others then
      l_error := substr(sqlerrm || chr(10) || dbms_utility.format_error_backtrace, 1, 4000);
      if l_trial_id is not null then
        update afma_cm_ai_trials
           set run_status = 'FAILED',
               error_text = l_error,
               completed_at = systimestamp
         where trial_id = l_trial_id;
        commit;
      end if;
      raise;
  end run_trial;
end afma_cm_video_ai_api;
/

comment on table afma_cm_ai_trials is 'Controlled multimodal model trials kept separate from reviewer evidence observations until accepted.';

prompt AFMA 135 complete
