#!/usr/bin/env node

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const workspace = process.cwd();
const inputPath = path.resolve(workspace, process.argv[2] || '.local/caab_species_20260611.csv');
const outputDir = path.resolve(workspace, process.argv[3] || '.local/caab_chunk_batches');
const batchKey = (process.argv[4] || 'CAAB_20260611').toUpperCase();
const fileName = path.basename(inputPath);
const sourceUrl = 'https://www.cmar.csiro.au/data/caab/create_caab_extract.cfm';
const chunkSize = 12000;
const chunksPerScript = 25;

function sqlString(value) {
  return String(value ?? '').replace(/'/g, "''");
}

function writeFile(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents, 'utf8');
}

if (!fs.existsSync(inputPath)) {
  console.error(`CSV not found: ${inputPath}`);
  process.exit(1);
}

if (chunkSize % 4 !== 0) {
  console.error('chunkSize must be a multiple of 4 for base64 decoding.');
  process.exit(1);
}

fs.rmSync(outputDir, { recursive: true, force: true });
fs.mkdirSync(outputDir, { recursive: true });

const csv = fs.readFileSync(inputPath);
const sha256 = crypto.createHash('sha256').update(csv).digest('hex');
const base64 = csv.toString('base64');
const chunks = [];

for (let offset = 0; offset < base64.length; offset += chunkSize) {
  chunks.push(base64.slice(offset, offset + chunkSize));
}

let scriptNo = 1;
for (let start = 0; start < chunks.length; start += chunksPerScript) {
  const batch = chunks.slice(start, start + chunksPerScript);
  const lines = [
    'set define off',
    '',
    `prompt AFMA CAAB CSV chunks ${start + 1}-${start + batch.length} of ${chunks.length}`,
    '',
    'begin'
  ];

  if (start === 0) {
    lines.push(`  csiro_caab_load_api.clear_base64_chunks('${sqlString(batchKey)}');`);
  }

  batch.forEach((chunk, index) => {
    const chunkNo = start + index + 1;
    lines.push(
      `  csiro_caab_load_api.append_base64_chunk(` +
      `p_batch_key => '${sqlString(batchKey)}', ` +
      `p_chunk_no => ${chunkNo}, ` +
      `p_base64_text => '${chunk}');`
    );
  });

  lines.push('end;');
  lines.push('/');
  lines.push('commit;');
  lines.push('');

  const filePath = path.join(outputDir, `caab_chunk_${String(scriptNo).padStart(4, '0')}.sql`);
  writeFile(filePath, `${lines.join('\n')}\n`);
  scriptNo += 1;
}

const finalizeSql = [
  'set define off',
  '',
  'prompt AFMA CAAB CSV chunk finalize load',
  '',
  'declare',
  '  l_load_id number;',
  'begin',
  '  l_load_id := csiro_caab_load_api.load_from_base64_chunks(',
  `    p_batch_key => '${sqlString(batchKey)}',`,
  `    p_file_name => '${sqlString(fileName)}',`,
  `    p_source_url => '${sqlString(sourceUrl)}',`,
  `    p_source_file_sha256 => '${sha256}',`,
  `    p_source_file_bytes => ${csv.length},`,
  `    p_data_as_at_text => 'Downloaded 2026-06-11 from CSIRO CAAB dump',`,
  `    p_replace_existing => 'Y',`,
  `    p_notes => 'AFMA demo load generated by tools/create_caab_chunk_sql_batches.mjs from ${sqlString(path.relative(workspace, inputPath))}.'`,
  '  );',
  `  dbms_output.put_line('CSIRO_CAAB_LOAD_ID=' || l_load_id);`,
  'end;',
  '/',
  'commit;',
  ''
].join('\n');

const finalizePath = path.join(outputDir, 'caab_finalize_load.sql');
writeFile(finalizePath, finalizeSql);

const manifest = {
  inputPath,
  outputDir,
  batchKey,
  fileName,
  bytes: csv.length,
  sha256,
  base64Length: base64.length,
  chunkSize,
  chunksPerScript,
  chunkCount: chunks.length,
  scriptCount: scriptNo - 1,
  firstScript: path.join(outputDir, 'caab_chunk_0001.sql'),
  finalizeScript: finalizePath
};

writeFile(path.join(outputDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(JSON.stringify(manifest, null, 2));
